# Form implementation generated from reading ui file 'app/view/ui/customer_view.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerPage(object):
    def setupUi(self, CustomerPage):
        CustomerPage.setObjectName("CustomerPage")
        CustomerPage.resize(1050, 560)
        self.mainLayout = QtWidgets.QHBoxLayout(CustomerPage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.formPanel = QtWidgets.QFrame(parent=CustomerPage)
        self.formPanel.setMinimumSize(QtCore.QSize(330, 0))
        self.formPanel.setMaximumSize(QtCore.QSize(370, 16777215))
        self.formPanel.setObjectName("formPanel")
        self.formLayout = QtWidgets.QVBoxLayout(self.formPanel)
        self.formLayout.setContentsMargins(14, 12, 14, 12)
        self.formLayout.setSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.lblFormTitle = QtWidgets.QLabel(parent=self.formPanel)
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formLayout.addWidget(self.lblFormTitle)
        self.lblPhone = QtWidgets.QLabel(parent=self.formPanel)
        self.lblPhone.setObjectName("lblPhone")
        self.formLayout.addWidget(self.lblPhone)
        self.phoneLayout = QtWidgets.QHBoxLayout()
        self.phoneLayout.setSpacing(8)
        self.phoneLayout.setObjectName("phoneLayout")
        self.txtPhone = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtPhone.setMinimumSize(QtCore.QSize(0, 38))
        self.txtPhone.setObjectName("txtPhone")
        self.phoneLayout.addWidget(self.txtPhone)
        self.btnSearchCustomer = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnSearchCustomer.setMinimumSize(QtCore.QSize(78, 38))
        self.btnSearchCustomer.setObjectName("btnSearchCustomer")
        self.phoneLayout.addWidget(self.btnSearchCustomer)
        self.formLayout.addLayout(self.phoneLayout)
        self.lblName = QtWidgets.QLabel(parent=self.formPanel)
        self.lblName.setObjectName("lblName")
        self.formLayout.addWidget(self.lblName)
        self.txtName = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtName.setMinimumSize(QtCore.QSize(0, 38))
        self.txtName.setObjectName("txtName")
        self.formLayout.addWidget(self.txtName)
        self.emailAddressTitleLayout = QtWidgets.QHBoxLayout()
        self.emailAddressTitleLayout.setSpacing(8)
        self.emailAddressTitleLayout.setObjectName("emailAddressTitleLayout")
        self.lblEmail = QtWidgets.QLabel(parent=self.formPanel)
        self.lblEmail.setObjectName("lblEmail")
        self.emailAddressTitleLayout.addWidget(self.lblEmail)
        self.lblGroup = QtWidgets.QLabel(parent=self.formPanel)
        self.lblGroup.setObjectName("lblGroup")
        self.emailAddressTitleLayout.addWidget(self.lblGroup)
        self.formLayout.addLayout(self.emailAddressTitleLayout)
        self.emailGroupLayout = QtWidgets.QHBoxLayout()
        self.emailGroupLayout.setSpacing(8)
        self.emailGroupLayout.setObjectName("emailGroupLayout")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtEmail.setMinimumSize(QtCore.QSize(0, 38))
        self.txtEmail.setObjectName("txtEmail")
        self.emailGroupLayout.addWidget(self.txtEmail)
        self.cboCustomerGroup = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboCustomerGroup.setMinimumSize(QtCore.QSize(120, 38))
        self.cboCustomerGroup.setObjectName("cboCustomerGroup")
        self.cboCustomerGroup.addItem("")
        self.cboCustomerGroup.addItem("")
        self.cboCustomerGroup.addItem("")
        self.cboCustomerGroup.addItem("")
        self.emailGroupLayout.addWidget(self.cboCustomerGroup)
        self.formLayout.addLayout(self.emailGroupLayout)
        self.lblAddress = QtWidgets.QLabel(parent=self.formPanel)
        self.lblAddress.setObjectName("lblAddress")
        self.formLayout.addWidget(self.lblAddress)
        self.txtAddress = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtAddress.setMinimumSize(QtCore.QSize(0, 38))
        self.txtAddress.setObjectName("txtAddress")
        self.formLayout.addWidget(self.txtAddress)
        self.lblNote = QtWidgets.QLabel(parent=self.formPanel)
        self.lblNote.setObjectName("lblNote")
        self.formLayout.addWidget(self.lblNote)
        self.txtNote = QtWidgets.QTextEdit(parent=self.formPanel)
        self.txtNote.setMinimumSize(QtCore.QSize(0, 80))
        self.txtNote.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtNote.setObjectName("txtNote")
        self.formLayout.addWidget(self.txtNote)
        self.buttonRow1 = QtWidgets.QHBoxLayout()
        self.buttonRow1.setSpacing(8)
        self.buttonRow1.setObjectName("buttonRow1")
        self.btnAddCustomer = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnAddCustomer.setObjectName("btnAddCustomer")
        self.buttonRow1.addWidget(self.btnAddCustomer)
        self.btnUpdateCustomer = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnUpdateCustomer.setObjectName("btnUpdateCustomer")
        self.buttonRow1.addWidget(self.btnUpdateCustomer)
        self.formLayout.addLayout(self.buttonRow1)
        self.buttonRow2 = QtWidgets.QHBoxLayout()
        self.buttonRow2.setSpacing(8)
        self.buttonRow2.setObjectName("buttonRow2")
        self.btnDeleteCustomer = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnDeleteCustomer.setObjectName("btnDeleteCustomer")
        self.buttonRow2.addWidget(self.btnDeleteCustomer)
        self.btnClearForm = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnClearForm.setObjectName("btnClearForm")
        self.buttonRow2.addWidget(self.btnClearForm)
        self.formLayout.addLayout(self.buttonRow2)
        self.btnVipCustomer = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnVipCustomer.setMinimumSize(QtCore.QSize(0, 38))
        self.btnVipCustomer.setObjectName("btnVipCustomer")
        self.formLayout.addWidget(self.btnVipCustomer)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.addItem(spacerItem)
        self.mainLayout.addWidget(self.formPanel)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.summaryCard1 = QtWidgets.QFrame(parent=CustomerPage)
        self.summaryCard1.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard1.setObjectName("summaryCard1")
        self.summaryCard1Layout = QtWidgets.QVBoxLayout(self.summaryCard1)
        self.summaryCard1Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard1Layout.setObjectName("summaryCard1Layout")
        self.lblTotalCustomers = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalCustomers.setObjectName("lblTotalCustomers")
        self.summaryCard1Layout.addWidget(self.lblTotalCustomers)
        self.lblTotalCustomersText = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalCustomersText.setObjectName("lblTotalCustomersText")
        self.summaryCard1Layout.addWidget(self.lblTotalCustomersText)
        self.summaryLayout.addWidget(self.summaryCard1)
        self.summaryCard2 = QtWidgets.QFrame(parent=CustomerPage)
        self.summaryCard2.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard2.setObjectName("summaryCard2")
        self.summaryCard2Layout = QtWidgets.QVBoxLayout(self.summaryCard2)
        self.summaryCard2Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard2Layout.setObjectName("summaryCard2Layout")
        self.lblVipCustomers = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblVipCustomers.setObjectName("lblVipCustomers")
        self.summaryCard2Layout.addWidget(self.lblVipCustomers)
        self.lblVipCustomersText = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblVipCustomersText.setObjectName("lblVipCustomersText")
        self.summaryCard2Layout.addWidget(self.lblVipCustomersText)
        self.summaryLayout.addWidget(self.summaryCard2)
        self.summaryCard3 = QtWidgets.QFrame(parent=CustomerPage)
        self.summaryCard3.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard3.setObjectName("summaryCard3")
        self.summaryCard3Layout = QtWidgets.QVBoxLayout(self.summaryCard3)
        self.summaryCard3Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard3Layout.setObjectName("summaryCard3Layout")
        self.lblSelectedCustomerSpent = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblSelectedCustomerSpent.setObjectName("lblSelectedCustomerSpent")
        self.summaryCard3Layout.addWidget(self.lblSelectedCustomerSpent)
        self.lblSelectedCustomerSpentText = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblSelectedCustomerSpentText.setObjectName("lblSelectedCustomerSpentText")
        self.summaryCard3Layout.addWidget(self.lblSelectedCustomerSpentText)
        self.summaryLayout.addWidget(self.summaryCard3)
        self.rightLayout.addLayout(self.summaryLayout)
        self.listPanel = QtWidgets.QFrame(parent=CustomerPage)
        self.listPanel.setObjectName("listPanel")
        self.listLayout = QtWidgets.QVBoxLayout(self.listPanel)
        self.listLayout.setContentsMargins(12, 10, 12, 10)
        self.listLayout.setSpacing(8)
        self.listLayout.setObjectName("listLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.lblListTitle = QtWidgets.QLabel(parent=self.listPanel)
        self.lblListTitle.setObjectName("lblListTitle")
        self.filterLayout.addWidget(self.lblListTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem1)
        self.txtSearch = QtWidgets.QLineEdit(parent=self.listPanel)
        self.txtSearch.setMinimumSize(QtCore.QSize(220, 36))
        self.txtSearch.setObjectName("txtSearch")
        self.filterLayout.addWidget(self.txtSearch)
        self.cboFilterGroup = QtWidgets.QComboBox(parent=self.listPanel)
        self.cboFilterGroup.setMinimumSize(QtCore.QSize(130, 36))
        self.cboFilterGroup.setObjectName("cboFilterGroup")
        self.cboFilterGroup.addItem("")
        self.cboFilterGroup.addItem("")
        self.cboFilterGroup.addItem("")
        self.cboFilterGroup.addItem("")
        self.cboFilterGroup.addItem("")
        self.filterLayout.addWidget(self.cboFilterGroup)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnRefresh.setMinimumSize(QtCore.QSize(88, 36))
        self.btnRefresh.setObjectName("btnRefresh")
        self.filterLayout.addWidget(self.btnRefresh)
        self.btnExportCustomer = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnExportCustomer.setMinimumSize(QtCore.QSize(96, 36))
        self.btnExportCustomer.setObjectName("btnExportCustomer")
        self.filterLayout.addWidget(self.btnExportCustomer)
        self.listLayout.addLayout(self.filterLayout)
        self.tableCustomers = QtWidgets.QTableWidget(parent=self.listPanel)
        self.tableCustomers.setMinimumSize(QtCore.QSize(0, 190))
        self.tableCustomers.setColumnCount(9)
        self.tableCustomers.setObjectName("tableCustomers")
        self.tableCustomers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(8, item)
        self.listLayout.addWidget(self.tableCustomers)
        self.rightLayout.addWidget(self.listPanel)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setSpacing(10)
        self.bottomLayout.setObjectName("bottomLayout")
        self.historyPanel = QtWidgets.QFrame(parent=CustomerPage)
        self.historyPanel.setObjectName("historyPanel")
        self.historyLayout = QtWidgets.QVBoxLayout(self.historyPanel)
        self.historyLayout.setContentsMargins(12, 10, 12, 10)
        self.historyLayout.setSpacing(8)
        self.historyLayout.setObjectName("historyLayout")
        self.historyTitleLayout = QtWidgets.QHBoxLayout()
        self.historyTitleLayout.setObjectName("historyTitleLayout")
        self.lblHistoryTitle = QtWidgets.QLabel(parent=self.historyPanel)
        self.lblHistoryTitle.setObjectName("lblHistoryTitle")
        self.historyTitleLayout.addWidget(self.lblHistoryTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.historyTitleLayout.addItem(spacerItem2)
        self.btnViewInvoice = QtWidgets.QPushButton(parent=self.historyPanel)
        self.btnViewInvoice.setMaximumSize(QtCore.QSize(110, 34))
        self.btnViewInvoice.setObjectName("btnViewInvoice")
        self.historyTitleLayout.addWidget(self.btnViewInvoice)
        self.historyLayout.addLayout(self.historyTitleLayout)
        self.tableInvoices = QtWidgets.QTableWidget(parent=self.historyPanel)
        self.tableInvoices.setMinimumSize(QtCore.QSize(0, 130))
        self.tableInvoices.setColumnCount(5)
        self.tableInvoices.setObjectName("tableInvoices")
        self.tableInvoices.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(4, item)
        self.historyLayout.addWidget(self.tableInvoices)
        self.bottomLayout.addWidget(self.historyPanel)
        self.detailPanel = QtWidgets.QFrame(parent=CustomerPage)
        self.detailPanel.setObjectName("detailPanel")
        self.detailLayout = QtWidgets.QVBoxLayout(self.detailPanel)
        self.detailLayout.setContentsMargins(12, 10, 12, 10)
        self.detailLayout.setSpacing(8)
        self.detailLayout.setObjectName("detailLayout")
        self.imeiTitleLayout = QtWidgets.QHBoxLayout()
        self.imeiTitleLayout.setObjectName("imeiTitleLayout")
        self.lblImeiBoughtTitle = QtWidgets.QLabel(parent=self.detailPanel)
        self.lblImeiBoughtTitle.setObjectName("lblImeiBoughtTitle")
        self.imeiTitleLayout.addWidget(self.lblImeiBoughtTitle)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.imeiTitleLayout.addItem(spacerItem3)
        self.btnViewWarranty = QtWidgets.QPushButton(parent=self.detailPanel)
        self.btnViewWarranty.setMaximumSize(QtCore.QSize(130, 34))
        self.btnViewWarranty.setObjectName("btnViewWarranty")
        self.imeiTitleLayout.addWidget(self.btnViewWarranty)
        self.detailLayout.addLayout(self.imeiTitleLayout)
        self.tableBoughtImeis = QtWidgets.QTableWidget(parent=self.detailPanel)
        self.tableBoughtImeis.setMinimumSize(QtCore.QSize(0, 130))
        self.tableBoughtImeis.setColumnCount(5)
        self.tableBoughtImeis.setObjectName("tableBoughtImeis")
        self.tableBoughtImeis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableBoughtImeis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBoughtImeis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBoughtImeis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBoughtImeis.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBoughtImeis.setHorizontalHeaderItem(4, item)
        self.detailLayout.addWidget(self.tableBoughtImeis)
        self.bottomLayout.addWidget(self.detailPanel)
        self.rightLayout.addLayout(self.bottomLayout)
        self.mainLayout.addLayout(self.rightLayout)

        self.retranslateUi(CustomerPage)
        QtCore.QMetaObject.connectSlotsByName(CustomerPage)

    def retranslateUi(self, CustomerPage):
        _translate = QtCore.QCoreApplication.translate
        CustomerPage.setStyleSheet(_translate("CustomerPage", "\n"
"QWidget#CustomerPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#formPanel,\n"
"QFrame#listPanel,\n"
"QFrame#detailPanel,\n"
"QFrame#historyPanel,\n"
"QFrame#summaryCard1,\n"
"QFrame#summaryCard2,\n"
"QFrame#summaryCard3 {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"QComboBox {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"QLabel.statNumber {\n"
"    color: #2563eb;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QComboBox,\n"
"QTextEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus,\n"
"QTextEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnAddCustomer,\n"
"QPushButton#btnUpdateCustomer,\n"
"QPushButton#btnSearchCustomer,\n"
"QPushButton#btnViewInvoice,\n"
"QPushButton#btnViewWarranty {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnUpdateCustomer {\n"
"    background-color: #16a34a;\n"
"}\n"
"\n"
"QPushButton#btnDeleteCustomer {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnClearForm,\n"
"QPushButton#btnRefresh,\n"
"QPushButton#btnExportCustomer {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnVipCustomer {\n"
"    background-color: #7c3aed;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblFormTitle.setText(_translate("CustomerPage", "👤 Hồ sơ khách hàng"))
        self.lblFormTitle.setProperty("class", _translate("CustomerPage", "sectionTitle"))
        self.lblPhone.setText(_translate("CustomerPage", "Số điện thoại"))
        self.lblPhone.setProperty("class", _translate("CustomerPage", "formLabel"))
        self.txtPhone.setPlaceholderText(_translate("CustomerPage", "Nhập SĐT khách hàng"))
        self.btnSearchCustomer.setText(_translate("CustomerPage", "🔍 Tìm"))
        self.lblName.setText(_translate("CustomerPage", "Họ tên"))
        self.lblName.setProperty("class", _translate("CustomerPage", "formLabel"))
        self.txtName.setPlaceholderText(_translate("CustomerPage", "Nguyễn Văn A"))
        self.lblEmail.setText(_translate("CustomerPage", "Email"))
        self.lblEmail.setProperty("class", _translate("CustomerPage", "formLabel"))
        self.lblGroup.setText(_translate("CustomerPage", "Nhóm khách"))
        self.lblGroup.setProperty("class", _translate("CustomerPage", "formLabel"))
        self.txtEmail.setPlaceholderText(_translate("CustomerPage", "email@gmail.com"))
        self.cboCustomerGroup.setItemText(0, _translate("CustomerPage", "Thường"))
        self.cboCustomerGroup.setItemText(1, _translate("CustomerPage", "VIP"))
        self.cboCustomerGroup.setItemText(2, _translate("CustomerPage", "Đại lý"))
        self.cboCustomerGroup.setItemText(3, _translate("CustomerPage", "Blacklist"))
        self.lblAddress.setText(_translate("CustomerPage", "Địa chỉ"))
        self.lblAddress.setProperty("class", _translate("CustomerPage", "formLabel"))
        self.txtAddress.setPlaceholderText(_translate("CustomerPage", "Địa chỉ khách hàng"))
        self.lblNote.setText(_translate("CustomerPage", "Ghi chú"))
        self.lblNote.setProperty("class", _translate("CustomerPage", "formLabel"))
        self.txtNote.setPlaceholderText(_translate("CustomerPage", "Ghi chú: sở thích, yêu cầu bảo hành, thói quen mua..."))
        self.btnAddCustomer.setText(_translate("CustomerPage", "➕ Thêm"))
        self.btnUpdateCustomer.setText(_translate("CustomerPage", "💾 Sửa"))
        self.btnDeleteCustomer.setText(_translate("CustomerPage", "🗑 Xóa"))
        self.btnClearForm.setText(_translate("CustomerPage", "🧹 Xóa form"))
        self.btnVipCustomer.setText(_translate("CustomerPage", "⭐ Đánh dấu khách VIP"))
        self.lblTotalCustomers.setText(_translate("CustomerPage", "0"))
        self.lblTotalCustomers.setProperty("class", _translate("CustomerPage", "statNumber"))
        self.lblTotalCustomersText.setText(_translate("CustomerPage", "Tổng khách hàng"))
        self.lblTotalCustomersText.setProperty("class", _translate("CustomerPage", "statText"))
        self.lblVipCustomers.setText(_translate("CustomerPage", "0"))
        self.lblVipCustomers.setProperty("class", _translate("CustomerPage", "statNumber"))
        self.lblVipCustomersText.setText(_translate("CustomerPage", "Khách VIP"))
        self.lblVipCustomersText.setProperty("class", _translate("CustomerPage", "statText"))
        self.lblSelectedCustomerSpent.setText(_translate("CustomerPage", "0 đ"))
        self.lblSelectedCustomerSpent.setProperty("class", _translate("CustomerPage", "statNumber"))
        self.lblSelectedCustomerSpentText.setText(_translate("CustomerPage", "Tổng chi tiêu khách đang chọn"))
        self.lblSelectedCustomerSpentText.setProperty("class", _translate("CustomerPage", "statText"))
        self.lblListTitle.setText(_translate("CustomerPage", "📋 Danh sách khách hàng"))
        self.lblListTitle.setProperty("class", _translate("CustomerPage", "sectionTitle"))
        self.txtSearch.setPlaceholderText(_translate("CustomerPage", "🔍 Tìm tên, SĐT, email..."))
        self.cboFilterGroup.setItemText(0, _translate("CustomerPage", "Tất cả"))
        self.cboFilterGroup.setItemText(1, _translate("CustomerPage", "Thường"))
        self.cboFilterGroup.setItemText(2, _translate("CustomerPage", "VIP"))
        self.cboFilterGroup.setItemText(3, _translate("CustomerPage", "Đại lý"))
        self.cboFilterGroup.setItemText(4, _translate("CustomerPage", "Blacklist"))
        self.btnRefresh.setText(_translate("CustomerPage", "🔄 Mới"))
        self.btnExportCustomer.setText(_translate("CustomerPage", "📤 Xuất"))
        item = self.tableCustomers.horizontalHeaderItem(0)
        item.setText(_translate("CustomerPage", "ID"))
        item = self.tableCustomers.horizontalHeaderItem(1)
        item.setText(_translate("CustomerPage", "Họ tên"))
        item = self.tableCustomers.horizontalHeaderItem(2)
        item.setText(_translate("CustomerPage", "SĐT"))
        item = self.tableCustomers.horizontalHeaderItem(3)
        item.setText(_translate("CustomerPage", "Email"))
        item = self.tableCustomers.horizontalHeaderItem(4)
        item.setText(_translate("CustomerPage", "Địa chỉ"))
        item = self.tableCustomers.horizontalHeaderItem(5)
        item.setText(_translate("CustomerPage", "Nhóm"))
        item = self.tableCustomers.horizontalHeaderItem(6)
        item.setText(_translate("CustomerPage", "Số đơn"))
        item = self.tableCustomers.horizontalHeaderItem(7)
        item.setText(_translate("CustomerPage", "Tổng chi tiêu"))
        item = self.tableCustomers.horizontalHeaderItem(8)
        item.setText(_translate("CustomerPage", "Ngày tạo"))
        self.lblHistoryTitle.setText(_translate("CustomerPage", "🧾 Lịch sử hóa đơn"))
        self.lblHistoryTitle.setProperty("class", _translate("CustomerPage", "sectionTitle"))
        self.btnViewInvoice.setText(_translate("CustomerPage", "👁 Xem đơn"))
        item = self.tableInvoices.horizontalHeaderItem(0)
        item.setText(_translate("CustomerPage", "Mã đơn"))
        item = self.tableInvoices.horizontalHeaderItem(1)
        item.setText(_translate("CustomerPage", "Ngày mua"))
        item = self.tableInvoices.horizontalHeaderItem(2)
        item.setText(_translate("CustomerPage", "Tổng tiền"))
        item = self.tableInvoices.horizontalHeaderItem(3)
        item.setText(_translate("CustomerPage", "Thanh toán"))
        item = self.tableInvoices.horizontalHeaderItem(4)
        item.setText(_translate("CustomerPage", "Trạng thái"))
        self.lblImeiBoughtTitle.setText(_translate("CustomerPage", "📱 IMEI đã mua"))
        self.lblImeiBoughtTitle.setProperty("class", _translate("CustomerPage", "sectionTitle"))
        self.btnViewWarranty.setText(_translate("CustomerPage", "🛠 Bảo hành"))
        item = self.tableBoughtImeis.horizontalHeaderItem(0)
        item.setText(_translate("CustomerPage", "IMEI"))
        item = self.tableBoughtImeis.horizontalHeaderItem(1)
        item.setText(_translate("CustomerPage", "Sản phẩm"))
        item = self.tableBoughtImeis.horizontalHeaderItem(2)
        item.setText(_translate("CustomerPage", "Ngày mua"))
        item = self.tableBoughtImeis.horizontalHeaderItem(3)
        item.setText(_translate("CustomerPage", "Bảo hành"))
        item = self.tableBoughtImeis.horizontalHeaderItem(4)
        item.setText(_translate("CustomerPage", "Trạng thái"))
