# Form implementation generated from reading ui file 'app/view/ui/dashboard_home.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashboardHomePage(object):
    def setupUi(self, DashboardHomePage):
        DashboardHomePage.setObjectName("DashboardHomePage")
        DashboardHomePage.resize(1050, 680)
        DashboardHomePage.setStyleSheet("\n"
"QWidget#DashboardHomePage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"#cardRevenueToday, #cardOrderToday, #cardProductCount, #cardCustomerCount,\n"
"#chartPanel, #quickActionPanel, #recentActivityPanel, #warningPanel {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"#cardRevenueToday:hover, #cardOrderToday:hover, #cardProductCount:hover, #cardCustomerCount:hover,\n"
"#chartPanel:hover, #quickActionPanel:hover, #recentActivityPanel:hover, #warningPanel:hover {\n"
"    border: 2px solid #60a5fa;\n"
"}\n"
"\n"
"#lblRevenueIcon, #lblOrderIcon, #lblProductIcon, #lblCustomerIcon {\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"#lblRevenueTitle, #lblOrderTitle, #lblProductTitle, #lblCustomerTitle {\n"
"    color: #64748b;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lblRevenueToday, #lblOrderToday, #lblProductCount, #lblCustomerCount {\n"
"    color: #1e3a8a;\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#lblRevenueSub, #lblOrderSub, #lblProductSub, #lblCustomerSub {\n"
"    color: #16a34a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#lblChartTitle, #lblQuickActionTitle, #lblRecentActivityTitle, #lblWarningTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#chartFrame {\n"
"    background-color: #f8fafc;\n"
"    border: 1px dashed #93c5fd;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"#lblChartPlaceholder {\n"
"    color: #64748b;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#btnCreateOrder, #btnAddProduct, #btnAddCustomer {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCreateOrder:hover, #btnAddProduct:hover, #btnAddCustomer:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"#btnCreateOrder:pressed, #btnAddProduct:pressed, #btnAddCustomer:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    color: #334155;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 8px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #dbeafe;\n"
"}\n"
"   ")
        self.mainLayout = QtWidgets.QVBoxLayout(DashboardHomePage)
        self.mainLayout.setContentsMargins(18, 18, 18, 18)
        self.mainLayout.setSpacing(18)
        self.mainLayout.setObjectName("mainLayout")
        self.statCardsLayout = QtWidgets.QHBoxLayout()
        self.statCardsLayout.setSpacing(16)
        self.statCardsLayout.setObjectName("statCardsLayout")
        self.cardRevenueToday = QtWidgets.QFrame(parent=DashboardHomePage)
        self.cardRevenueToday.setMinimumSize(QtCore.QSize(0, 135))
        self.cardRevenueToday.setObjectName("cardRevenueToday")
        self.revenueCardLayout = QtWidgets.QVBoxLayout(self.cardRevenueToday)
        self.revenueCardLayout.setContentsMargins(18, 14, 18, 14)
        self.revenueCardLayout.setObjectName("revenueCardLayout")
        self.lblRevenueIcon = QtWidgets.QLabel(parent=self.cardRevenueToday)
        self.lblRevenueIcon.setObjectName("lblRevenueIcon")
        self.revenueCardLayout.addWidget(self.lblRevenueIcon)
        self.lblRevenueTitle = QtWidgets.QLabel(parent=self.cardRevenueToday)
        self.lblRevenueTitle.setObjectName("lblRevenueTitle")
        self.revenueCardLayout.addWidget(self.lblRevenueTitle)
        self.lblRevenueToday = QtWidgets.QLabel(parent=self.cardRevenueToday)
        self.lblRevenueToday.setObjectName("lblRevenueToday")
        self.revenueCardLayout.addWidget(self.lblRevenueToday)
        self.lblRevenueSub = QtWidgets.QLabel(parent=self.cardRevenueToday)
        self.lblRevenueSub.setObjectName("lblRevenueSub")
        self.revenueCardLayout.addWidget(self.lblRevenueSub)
        self.statCardsLayout.addWidget(self.cardRevenueToday)
        self.cardOrderToday = QtWidgets.QFrame(parent=DashboardHomePage)
        self.cardOrderToday.setMinimumSize(QtCore.QSize(0, 135))
        self.cardOrderToday.setObjectName("cardOrderToday")
        self.orderCardLayout = QtWidgets.QVBoxLayout(self.cardOrderToday)
        self.orderCardLayout.setContentsMargins(18, 14, 18, 14)
        self.orderCardLayout.setObjectName("orderCardLayout")
        self.lblOrderIcon = QtWidgets.QLabel(parent=self.cardOrderToday)
        self.lblOrderIcon.setObjectName("lblOrderIcon")
        self.orderCardLayout.addWidget(self.lblOrderIcon)
        self.lblOrderTitle = QtWidgets.QLabel(parent=self.cardOrderToday)
        self.lblOrderTitle.setObjectName("lblOrderTitle")
        self.orderCardLayout.addWidget(self.lblOrderTitle)
        self.lblOrderToday = QtWidgets.QLabel(parent=self.cardOrderToday)
        self.lblOrderToday.setObjectName("lblOrderToday")
        self.orderCardLayout.addWidget(self.lblOrderToday)
        self.lblOrderSub = QtWidgets.QLabel(parent=self.cardOrderToday)
        self.lblOrderSub.setObjectName("lblOrderSub")
        self.orderCardLayout.addWidget(self.lblOrderSub)
        self.statCardsLayout.addWidget(self.cardOrderToday)
        self.cardProductCount = QtWidgets.QFrame(parent=DashboardHomePage)
        self.cardProductCount.setMinimumSize(QtCore.QSize(0, 135))
        self.cardProductCount.setObjectName("cardProductCount")
        self.productCardLayout = QtWidgets.QVBoxLayout(self.cardProductCount)
        self.productCardLayout.setContentsMargins(18, 14, 18, 14)
        self.productCardLayout.setObjectName("productCardLayout")
        self.lblProductIcon = QtWidgets.QLabel(parent=self.cardProductCount)
        self.lblProductIcon.setObjectName("lblProductIcon")
        self.productCardLayout.addWidget(self.lblProductIcon)
        self.lblProductTitle = QtWidgets.QLabel(parent=self.cardProductCount)
        self.lblProductTitle.setObjectName("lblProductTitle")
        self.productCardLayout.addWidget(self.lblProductTitle)
        self.lblProductCount = QtWidgets.QLabel(parent=self.cardProductCount)
        self.lblProductCount.setObjectName("lblProductCount")
        self.productCardLayout.addWidget(self.lblProductCount)
        self.lblProductSub = QtWidgets.QLabel(parent=self.cardProductCount)
        self.lblProductSub.setObjectName("lblProductSub")
        self.productCardLayout.addWidget(self.lblProductSub)
        self.statCardsLayout.addWidget(self.cardProductCount)
        self.cardCustomerCount = QtWidgets.QFrame(parent=DashboardHomePage)
        self.cardCustomerCount.setMinimumSize(QtCore.QSize(0, 135))
        self.cardCustomerCount.setObjectName("cardCustomerCount")
        self.customerCardLayout = QtWidgets.QVBoxLayout(self.cardCustomerCount)
        self.customerCardLayout.setContentsMargins(18, 14, 18, 14)
        self.customerCardLayout.setObjectName("customerCardLayout")
        self.lblCustomerIcon = QtWidgets.QLabel(parent=self.cardCustomerCount)
        self.lblCustomerIcon.setObjectName("lblCustomerIcon")
        self.customerCardLayout.addWidget(self.lblCustomerIcon)
        self.lblCustomerTitle = QtWidgets.QLabel(parent=self.cardCustomerCount)
        self.lblCustomerTitle.setObjectName("lblCustomerTitle")
        self.customerCardLayout.addWidget(self.lblCustomerTitle)
        self.lblCustomerCount = QtWidgets.QLabel(parent=self.cardCustomerCount)
        self.lblCustomerCount.setObjectName("lblCustomerCount")
        self.customerCardLayout.addWidget(self.lblCustomerCount)
        self.lblCustomerSub = QtWidgets.QLabel(parent=self.cardCustomerCount)
        self.lblCustomerSub.setObjectName("lblCustomerSub")
        self.customerCardLayout.addWidget(self.lblCustomerSub)
        self.statCardsLayout.addWidget(self.cardCustomerCount)
        self.mainLayout.addLayout(self.statCardsLayout)
        self.centerAreaLayout = QtWidgets.QHBoxLayout()
        self.centerAreaLayout.setSpacing(18)
        self.centerAreaLayout.setObjectName("centerAreaLayout")
        self.chartPanel = QtWidgets.QFrame(parent=DashboardHomePage)
        self.chartPanel.setObjectName("chartPanel")
        self.chartPanelLayout = QtWidgets.QVBoxLayout(self.chartPanel)
        self.chartPanelLayout.setContentsMargins(18, 16, 18, 16)
        self.chartPanelLayout.setSpacing(12)
        self.chartPanelLayout.setObjectName("chartPanelLayout")
        self.lblChartTitle = QtWidgets.QLabel(parent=self.chartPanel)
        self.lblChartTitle.setObjectName("lblChartTitle")
        self.chartPanelLayout.addWidget(self.lblChartTitle)
        self.chartFrame = QtWidgets.QFrame(parent=self.chartPanel)
        self.chartFrame.setMinimumSize(QtCore.QSize(0, 230))
        self.chartFrame.setObjectName("chartFrame")
        self.chartFrameLayout = QtWidgets.QVBoxLayout(self.chartFrame)
        self.chartFrameLayout.setObjectName("chartFrameLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chartFrameLayout.addItem(spacerItem)
        self.lblChartPlaceholder = QtWidgets.QLabel(parent=self.chartFrame)
        self.lblChartPlaceholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblChartPlaceholder.setObjectName("lblChartPlaceholder")
        self.chartFrameLayout.addWidget(self.lblChartPlaceholder)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.chartFrameLayout.addItem(spacerItem1)
        self.chartPanelLayout.addWidget(self.chartFrame)
        self.centerAreaLayout.addWidget(self.chartPanel)
        self.quickActionPanel = QtWidgets.QFrame(parent=DashboardHomePage)
        self.quickActionPanel.setMinimumSize(QtCore.QSize(280, 0))
        self.quickActionPanel.setMaximumSize(QtCore.QSize(340, 16777215))
        self.quickActionPanel.setObjectName("quickActionPanel")
        self.quickActionLayout = QtWidgets.QVBoxLayout(self.quickActionPanel)
        self.quickActionLayout.setContentsMargins(18, 16, 18, 16)
        self.quickActionLayout.setSpacing(12)
        self.quickActionLayout.setObjectName("quickActionLayout")
        self.lblQuickActionTitle = QtWidgets.QLabel(parent=self.quickActionPanel)
        self.lblQuickActionTitle.setObjectName("lblQuickActionTitle")
        self.quickActionLayout.addWidget(self.lblQuickActionTitle)
        self.btnCreateOrder = QtWidgets.QPushButton(parent=self.quickActionPanel)
        self.btnCreateOrder.setMinimumSize(QtCore.QSize(0, 46))
        self.btnCreateOrder.setObjectName("btnCreateOrder")
        self.quickActionLayout.addWidget(self.btnCreateOrder)
        self.btnAddProduct = QtWidgets.QPushButton(parent=self.quickActionPanel)
        self.btnAddProduct.setMinimumSize(QtCore.QSize(0, 46))
        self.btnAddProduct.setObjectName("btnAddProduct")
        self.quickActionLayout.addWidget(self.btnAddProduct)
        self.btnAddCustomer = QtWidgets.QPushButton(parent=self.quickActionPanel)
        self.btnAddCustomer.setMinimumSize(QtCore.QSize(0, 46))
        self.btnAddCustomer.setObjectName("btnAddCustomer")
        self.quickActionLayout.addWidget(self.btnAddCustomer)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.quickActionLayout.addItem(spacerItem2)
        self.centerAreaLayout.addWidget(self.quickActionPanel)
        self.mainLayout.addLayout(self.centerAreaLayout)
        self.bottomAreaLayout = QtWidgets.QHBoxLayout()
        self.bottomAreaLayout.setSpacing(18)
        self.bottomAreaLayout.setObjectName("bottomAreaLayout")
        self.recentActivityPanel = QtWidgets.QFrame(parent=DashboardHomePage)
        self.recentActivityPanel.setObjectName("recentActivityPanel")
        self.recentActivityLayout = QtWidgets.QVBoxLayout(self.recentActivityPanel)
        self.recentActivityLayout.setContentsMargins(18, 16, 18, 16)
        self.recentActivityLayout.setSpacing(12)
        self.recentActivityLayout.setObjectName("recentActivityLayout")
        self.lblRecentActivityTitle = QtWidgets.QLabel(parent=self.recentActivityPanel)
        self.lblRecentActivityTitle.setObjectName("lblRecentActivityTitle")
        self.recentActivityLayout.addWidget(self.lblRecentActivityTitle)
        self.listRecentActivity = QtWidgets.QListWidget(parent=self.recentActivityPanel)
        self.listRecentActivity.setObjectName("listRecentActivity")
        self.recentActivityLayout.addWidget(self.listRecentActivity)
        self.bottomAreaLayout.addWidget(self.recentActivityPanel)
        self.warningPanel = QtWidgets.QFrame(parent=DashboardHomePage)
        self.warningPanel.setObjectName("warningPanel")
        self.warningLayout = QtWidgets.QVBoxLayout(self.warningPanel)
        self.warningLayout.setContentsMargins(18, 16, 18, 16)
        self.warningLayout.setSpacing(12)
        self.warningLayout.setObjectName("warningLayout")
        self.lblWarningTitle = QtWidgets.QLabel(parent=self.warningPanel)
        self.lblWarningTitle.setObjectName("lblWarningTitle")
        self.warningLayout.addWidget(self.lblWarningTitle)
        self.listWarning = QtWidgets.QListWidget(parent=self.warningPanel)
        self.listWarning.setObjectName("listWarning")
        self.warningLayout.addWidget(self.listWarning)
        self.bottomAreaLayout.addWidget(self.warningPanel)
        self.mainLayout.addLayout(self.bottomAreaLayout)

        self.retranslateUi(DashboardHomePage)
        QtCore.QMetaObject.connectSlotsByName(DashboardHomePage)

    def retranslateUi(self, DashboardHomePage):
        _translate = QtCore.QCoreApplication.translate
        self.lblRevenueIcon.setText(_translate("DashboardHomePage", "💰"))
        self.lblRevenueTitle.setText(_translate("DashboardHomePage", "Doanh thu hôm nay"))
        self.lblRevenueToday.setText(_translate("DashboardHomePage", "0 ₫"))
        self.lblRevenueSub.setText(_translate("DashboardHomePage", "Realtime update"))
        self.lblOrderIcon.setText(_translate("DashboardHomePage", "🧾"))
        self.lblOrderTitle.setText(_translate("DashboardHomePage", "Số đơn hôm nay"))
        self.lblOrderToday.setText(_translate("DashboardHomePage", "0"))
        self.lblOrderSub.setText(_translate("DashboardHomePage", "Đơn hàng mới"))
        self.lblProductIcon.setText(_translate("DashboardHomePage", "📦"))
        self.lblProductTitle.setText(_translate("DashboardHomePage", "Sản phẩm trong kho"))
        self.lblProductCount.setText(_translate("DashboardHomePage", "0"))
        self.lblProductSub.setText(_translate("DashboardHomePage", "Tồn kho hiện tại"))
        self.lblCustomerIcon.setText(_translate("DashboardHomePage", "👥"))
        self.lblCustomerTitle.setText(_translate("DashboardHomePage", "Khách hàng"))
        self.lblCustomerCount.setText(_translate("DashboardHomePage", "0"))
        self.lblCustomerSub.setText(_translate("DashboardHomePage", "Tổng khách hàng"))
        self.lblChartTitle.setText(_translate("DashboardHomePage", "Doanh thu 7 ngày gần nhất"))
        self.lblChartPlaceholder.setText(_translate("DashboardHomePage", "Biểu đồ sẽ được render bằng Python"))
        self.lblQuickActionTitle.setText(_translate("DashboardHomePage", "Truy cập nhanh"))
        self.btnCreateOrder.setText(_translate("DashboardHomePage", "+ Tạo đơn hàng"))
        self.btnAddProduct.setText(_translate("DashboardHomePage", "+ Thêm sản phẩm"))
        self.btnAddCustomer.setText(_translate("DashboardHomePage", "+ Thêm khách hàng"))
        self.lblRecentActivityTitle.setText(_translate("DashboardHomePage", "Hoạt động gần đây"))
        self.lblWarningTitle.setText(_translate("DashboardHomePage", "Cảnh báo hệ thống"))
