# Form implementation generated from reading ui file 'app/view/ui/discount_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DiscountPage(object):
    def setupUi(self, DiscountPage):
        DiscountPage.setObjectName("DiscountPage")
        DiscountPage.resize(1050, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(DiscountPage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.summaryCard1 = QtWidgets.QFrame(parent=DiscountPage)
        self.summaryCard1.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard1.setObjectName("summaryCard1")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.summaryCard1)
        self.vboxlayout.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblTotalDiscount = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalDiscount.setObjectName("lblTotalDiscount")
        self.vboxlayout.addWidget(self.lblTotalDiscount)
        self.lblTotalDiscountText = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalDiscountText.setObjectName("lblTotalDiscountText")
        self.vboxlayout.addWidget(self.lblTotalDiscountText)
        self.summaryLayout.addWidget(self.summaryCard1)
        self.summaryCard2 = QtWidgets.QFrame(parent=DiscountPage)
        self.summaryCard2.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard2.setObjectName("summaryCard2")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.summaryCard2)
        self.vboxlayout1.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.lblActiveDiscount = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblActiveDiscount.setObjectName("lblActiveDiscount")
        self.vboxlayout1.addWidget(self.lblActiveDiscount)
        self.lblActiveDiscountText = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblActiveDiscountText.setObjectName("lblActiveDiscountText")
        self.vboxlayout1.addWidget(self.lblActiveDiscountText)
        self.summaryLayout.addWidget(self.summaryCard2)
        self.summaryCard3 = QtWidgets.QFrame(parent=DiscountPage)
        self.summaryCard3.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard3.setObjectName("summaryCard3")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.summaryCard3)
        self.vboxlayout2.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.lblExpiredDiscount = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblExpiredDiscount.setObjectName("lblExpiredDiscount")
        self.vboxlayout2.addWidget(self.lblExpiredDiscount)
        self.lblExpiredDiscountText = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblExpiredDiscountText.setObjectName("lblExpiredDiscountText")
        self.vboxlayout2.addWidget(self.lblExpiredDiscountText)
        self.summaryLayout.addWidget(self.summaryCard3)
        self.summaryCard4 = QtWidgets.QFrame(parent=DiscountPage)
        self.summaryCard4.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard4.setObjectName("summaryCard4")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.summaryCard4)
        self.vboxlayout3.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.lblTotalDiscountUsed = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblTotalDiscountUsed.setObjectName("lblTotalDiscountUsed")
        self.vboxlayout3.addWidget(self.lblTotalDiscountUsed)
        self.lblTotalDiscountUsedText = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblTotalDiscountUsedText.setObjectName("lblTotalDiscountUsedText")
        self.vboxlayout3.addWidget(self.lblTotalDiscountUsedText)
        self.summaryLayout.addWidget(self.summaryCard4)
        self.mainLayout.addLayout(self.summaryLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.contentLayout.setObjectName("contentLayout")
        self.formPanel = QtWidgets.QFrame(parent=DiscountPage)
        self.formPanel.setMinimumSize(QtCore.QSize(360, 0))
        self.formPanel.setMaximumSize(QtCore.QSize(390, 16777215))
        self.formPanel.setObjectName("formPanel")
        self.formLayout = QtWidgets.QVBoxLayout(self.formPanel)
        self.formLayout.setContentsMargins(14, 12, 14, 12)
        self.formLayout.setSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.lblFormTitle = QtWidgets.QLabel(parent=self.formPanel)
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formLayout.addWidget(self.lblFormTitle)
        self.lblCode = QtWidgets.QLabel(parent=self.formPanel)
        self.lblCode.setObjectName("lblCode")
        self.formLayout.addWidget(self.lblCode)
        self.txtCode = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtCode.setMinimumSize(QtCore.QSize(0, 38))
        self.txtCode.setObjectName("txtCode")
        self.formLayout.addWidget(self.txtCode)
        self.typeTitleLayout = QtWidgets.QHBoxLayout()
        self.typeTitleLayout.setSpacing(8)
        self.typeTitleLayout.setObjectName("typeTitleLayout")
        self.lblType = QtWidgets.QLabel(parent=self.formPanel)
        self.lblType.setObjectName("lblType")
        self.typeTitleLayout.addWidget(self.lblType)
        self.lblValue = QtWidgets.QLabel(parent=self.formPanel)
        self.lblValue.setObjectName("lblValue")
        self.typeTitleLayout.addWidget(self.lblValue)
        self.formLayout.addLayout(self.typeTitleLayout)
        self.typeValueLayout = QtWidgets.QHBoxLayout()
        self.typeValueLayout.setSpacing(8)
        self.typeValueLayout.setObjectName("typeValueLayout")
        self.cboDiscountType = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboDiscountType.setMinimumSize(QtCore.QSize(150, 38))
        self.cboDiscountType.setObjectName("cboDiscountType")
        self.cboDiscountType.addItem("")
        self.cboDiscountType.addItem("")
        self.typeValueLayout.addWidget(self.cboDiscountType)
        self.spinDiscountValue = QtWidgets.QDoubleSpinBox(parent=self.formPanel)
        self.spinDiscountValue.setMinimumSize(QtCore.QSize(0, 38))
        self.spinDiscountValue.setMaximum(999999999.0)
        self.spinDiscountValue.setSingleStep(10000.0)
        self.spinDiscountValue.setObjectName("spinDiscountValue")
        self.typeValueLayout.addWidget(self.spinDiscountValue)
        self.formLayout.addLayout(self.typeValueLayout)
        self.maxMinTitleLayout = QtWidgets.QHBoxLayout()
        self.maxMinTitleLayout.setSpacing(8)
        self.maxMinTitleLayout.setObjectName("maxMinTitleLayout")
        self.lblMaxDiscount = QtWidgets.QLabel(parent=self.formPanel)
        self.lblMaxDiscount.setObjectName("lblMaxDiscount")
        self.maxMinTitleLayout.addWidget(self.lblMaxDiscount)
        self.lblMinOrder = QtWidgets.QLabel(parent=self.formPanel)
        self.lblMinOrder.setObjectName("lblMinOrder")
        self.maxMinTitleLayout.addWidget(self.lblMinOrder)
        self.formLayout.addLayout(self.maxMinTitleLayout)
        self.maxMinLayout = QtWidgets.QHBoxLayout()
        self.maxMinLayout.setSpacing(8)
        self.maxMinLayout.setObjectName("maxMinLayout")
        self.spinMaxDiscount = QtWidgets.QDoubleSpinBox(parent=self.formPanel)
        self.spinMaxDiscount.setMinimumSize(QtCore.QSize(0, 38))
        self.spinMaxDiscount.setMaximum(999999999.0)
        self.spinMaxDiscount.setSingleStep(100000.0)
        self.spinMaxDiscount.setObjectName("spinMaxDiscount")
        self.maxMinLayout.addWidget(self.spinMaxDiscount)
        self.spinMinOrder = QtWidgets.QDoubleSpinBox(parent=self.formPanel)
        self.spinMinOrder.setMinimumSize(QtCore.QSize(0, 38))
        self.spinMinOrder.setMaximum(999999999.0)
        self.spinMinOrder.setSingleStep(100000.0)
        self.spinMinOrder.setObjectName("spinMinOrder")
        self.maxMinLayout.addWidget(self.spinMinOrder)
        self.formLayout.addLayout(self.maxMinLayout)
        self.usageTitleLayout = QtWidgets.QHBoxLayout()
        self.usageTitleLayout.setSpacing(8)
        self.usageTitleLayout.setObjectName("usageTitleLayout")
        self.lblUsageLimit = QtWidgets.QLabel(parent=self.formPanel)
        self.lblUsageLimit.setObjectName("lblUsageLimit")
        self.usageTitleLayout.addWidget(self.lblUsageLimit)
        self.lblPerCustomerLimit = QtWidgets.QLabel(parent=self.formPanel)
        self.lblPerCustomerLimit.setObjectName("lblPerCustomerLimit")
        self.usageTitleLayout.addWidget(self.lblPerCustomerLimit)
        self.formLayout.addLayout(self.usageTitleLayout)
        self.usageLayout = QtWidgets.QHBoxLayout()
        self.usageLayout.setSpacing(8)
        self.usageLayout.setObjectName("usageLayout")
        self.spinUsageLimit = QtWidgets.QSpinBox(parent=self.formPanel)
        self.spinUsageLimit.setMinimumSize(QtCore.QSize(0, 38))
        self.spinUsageLimit.setMaximum(999999)
        self.spinUsageLimit.setProperty("value", 100)
        self.spinUsageLimit.setObjectName("spinUsageLimit")
        self.usageLayout.addWidget(self.spinUsageLimit)
        self.spinPerCustomerLimit = QtWidgets.QSpinBox(parent=self.formPanel)
        self.spinPerCustomerLimit.setMinimumSize(QtCore.QSize(0, 38))
        self.spinPerCustomerLimit.setMaximum(999999)
        self.spinPerCustomerLimit.setProperty("value", 1)
        self.spinPerCustomerLimit.setObjectName("spinPerCustomerLimit")
        self.usageLayout.addWidget(self.spinPerCustomerLimit)
        self.formLayout.addLayout(self.usageLayout)
        self.dateTitleLayout = QtWidgets.QHBoxLayout()
        self.dateTitleLayout.setSpacing(8)
        self.dateTitleLayout.setObjectName("dateTitleLayout")
        self.lblStartDate = QtWidgets.QLabel(parent=self.formPanel)
        self.lblStartDate.setObjectName("lblStartDate")
        self.dateTitleLayout.addWidget(self.lblStartDate)
        self.lblEndDate = QtWidgets.QLabel(parent=self.formPanel)
        self.lblEndDate.setObjectName("lblEndDate")
        self.dateTitleLayout.addWidget(self.lblEndDate)
        self.formLayout.addLayout(self.dateTitleLayout)
        self.dateLayout = QtWidgets.QHBoxLayout()
        self.dateLayout.setSpacing(8)
        self.dateLayout.setObjectName("dateLayout")
        self.dateStart = QtWidgets.QDateEdit(parent=self.formPanel)
        self.dateStart.setMinimumSize(QtCore.QSize(0, 38))
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName("dateStart")
        self.dateLayout.addWidget(self.dateStart)
        self.dateEnd = QtWidgets.QDateEdit(parent=self.formPanel)
        self.dateEnd.setMinimumSize(QtCore.QSize(0, 38))
        self.dateEnd.setCalendarPopup(True)
        self.dateEnd.setObjectName("dateEnd")
        self.dateLayout.addWidget(self.dateEnd)
        self.formLayout.addLayout(self.dateLayout)
        self.lblStatus = QtWidgets.QLabel(parent=self.formPanel)
        self.lblStatus.setObjectName("lblStatus")
        self.formLayout.addWidget(self.lblStatus)
        self.cboStatus = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboStatus.setMinimumSize(QtCore.QSize(0, 38))
        self.cboStatus.setObjectName("cboStatus")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.formLayout.addWidget(self.cboStatus)
        self.previewBox = QtWidgets.QFrame(parent=self.formPanel)
        self.previewBox.setObjectName("previewBox")
        self.vboxlayout4 = QtWidgets.QVBoxLayout(self.previewBox)
        self.vboxlayout4.setContentsMargins(12, 10, 12, 10)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.lblPreview = QtWidgets.QLabel(parent=self.previewBox)
        self.lblPreview.setWordWrap(True)
        self.lblPreview.setObjectName("lblPreview")
        self.vboxlayout4.addWidget(self.lblPreview)
        self.formLayout.addWidget(self.previewBox)
        self.buttonRow1 = QtWidgets.QHBoxLayout()
        self.buttonRow1.setSpacing(8)
        self.buttonRow1.setObjectName("buttonRow1")
        self.btnAddDiscount = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnAddDiscount.setMinimumSize(QtCore.QSize(0, 38))
        self.btnAddDiscount.setObjectName("btnAddDiscount")
        self.buttonRow1.addWidget(self.btnAddDiscount)
        self.btnUpdateDiscount = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnUpdateDiscount.setMinimumSize(QtCore.QSize(0, 38))
        self.btnUpdateDiscount.setObjectName("btnUpdateDiscount")
        self.buttonRow1.addWidget(self.btnUpdateDiscount)
        self.formLayout.addLayout(self.buttonRow1)
        self.buttonRow2 = QtWidgets.QHBoxLayout()
        self.buttonRow2.setSpacing(8)
        self.buttonRow2.setObjectName("buttonRow2")
        self.btnDeleteDiscount = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnDeleteDiscount.setMinimumSize(QtCore.QSize(0, 38))
        self.btnDeleteDiscount.setObjectName("btnDeleteDiscount")
        self.buttonRow2.addWidget(self.btnDeleteDiscount)
        self.btnClearForm = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnClearForm.setMinimumSize(QtCore.QSize(0, 38))
        self.btnClearForm.setObjectName("btnClearForm")
        self.buttonRow2.addWidget(self.btnClearForm)
        self.formLayout.addLayout(self.buttonRow2)
        self.contentLayout.addWidget(self.formPanel)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.testPanel = QtWidgets.QFrame(parent=DiscountPage)
        self.testPanel.setMaximumSize(QtCore.QSize(16777215, 108))
        self.testPanel.setObjectName("testPanel")
        self.testLayout = QtWidgets.QVBoxLayout(self.testPanel)
        self.testLayout.setContentsMargins(12, 10, 12, 10)
        self.testLayout.setSpacing(8)
        self.testLayout.setObjectName("testLayout")
        self.lblTestTitle = QtWidgets.QLabel(parent=self.testPanel)
        self.lblTestTitle.setObjectName("lblTestTitle")
        self.testLayout.addWidget(self.lblTestTitle)
        self.testRow = QtWidgets.QHBoxLayout()
        self.testRow.setSpacing(8)
        self.testRow.setObjectName("testRow")
        self.txtTestCode = QtWidgets.QLineEdit(parent=self.testPanel)
        self.txtTestCode.setMinimumSize(QtCore.QSize(170, 38))
        self.txtTestCode.setObjectName("txtTestCode")
        self.testRow.addWidget(self.txtTestCode)
        self.spinTestOrderAmount = QtWidgets.QDoubleSpinBox(parent=self.testPanel)
        self.spinTestOrderAmount.setMinimumSize(QtCore.QSize(170, 38))
        self.spinTestOrderAmount.setMaximum(999999999.0)
        self.spinTestOrderAmount.setSingleStep(100000.0)
        self.spinTestOrderAmount.setObjectName("spinTestOrderAmount")
        self.testRow.addWidget(self.spinTestOrderAmount)
        self.btnCheckCode = QtWidgets.QPushButton(parent=self.testPanel)
        self.btnCheckCode.setMinimumSize(QtCore.QSize(110, 38))
        self.btnCheckCode.setObjectName("btnCheckCode")
        self.testRow.addWidget(self.btnCheckCode)
        self.lblTestResult = QtWidgets.QLabel(parent=self.testPanel)
        self.lblTestResult.setMinimumSize(QtCore.QSize(220, 38))
        self.lblTestResult.setObjectName("lblTestResult")
        self.testRow.addWidget(self.lblTestResult)
        self.testLayout.addLayout(self.testRow)
        self.rightLayout.addWidget(self.testPanel)
        self.listPanel = QtWidgets.QFrame(parent=DiscountPage)
        self.listPanel.setObjectName("listPanel")
        self.listLayout = QtWidgets.QVBoxLayout(self.listPanel)
        self.listLayout.setContentsMargins(12, 10, 12, 10)
        self.listLayout.setSpacing(8)
        self.listLayout.setObjectName("listLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.lblListTitle = QtWidgets.QLabel(parent=self.listPanel)
        self.lblListTitle.setObjectName("lblListTitle")
        self.filterLayout.addWidget(self.lblListTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.txtSearch = QtWidgets.QLineEdit(parent=self.listPanel)
        self.txtSearch.setMinimumSize(QtCore.QSize(190, 36))
        self.txtSearch.setObjectName("txtSearch")
        self.filterLayout.addWidget(self.txtSearch)
        self.cboFilterStatus = QtWidgets.QComboBox(parent=self.listPanel)
        self.cboFilterStatus.setMinimumSize(QtCore.QSize(135, 36))
        self.cboFilterStatus.setObjectName("cboFilterStatus")
        self.cboFilterStatus.addItem("")
        self.cboFilterStatus.addItem("")
        self.cboFilterStatus.addItem("")
        self.cboFilterStatus.addItem("")
        self.filterLayout.addWidget(self.cboFilterStatus)
        self.cboFilterType = QtWidgets.QComboBox(parent=self.listPanel)
        self.cboFilterType.setMinimumSize(QtCore.QSize(120, 36))
        self.cboFilterType.setObjectName("cboFilterType")
        self.cboFilterType.addItem("")
        self.cboFilterType.addItem("")
        self.cboFilterType.addItem("")
        self.filterLayout.addWidget(self.cboFilterType)
        self.btnSearch = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnSearch.setMinimumSize(QtCore.QSize(82, 36))
        self.btnSearch.setObjectName("btnSearch")
        self.filterLayout.addWidget(self.btnSearch)
        self.btnClearFilter = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnClearFilter.setMinimumSize(QtCore.QSize(88, 36))
        self.btnClearFilter.setObjectName("btnClearFilter")
        self.filterLayout.addWidget(self.btnClearFilter)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnRefresh.setMinimumSize(QtCore.QSize(82, 36))
        self.btnRefresh.setObjectName("btnRefresh")
        self.filterLayout.addWidget(self.btnRefresh)
        self.listLayout.addLayout(self.filterLayout)
        self.tableDiscount = QtWidgets.QTableWidget(parent=self.listPanel)
        self.tableDiscount.setMinimumSize(QtCore.QSize(0, 240))
        self.tableDiscount.setColumnCount(13)
        self.tableDiscount.setObjectName("tableDiscount")
        self.tableDiscount.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDiscount.setHorizontalHeaderItem(12, item)
        self.listLayout.addWidget(self.tableDiscount)
        self.actionRow = QtWidgets.QHBoxLayout()
        self.actionRow.setSpacing(8)
        self.actionRow.setObjectName("actionRow")
        self.btnToggleStatus = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnToggleStatus.setMinimumSize(QtCore.QSize(150, 38))
        self.btnToggleStatus.setObjectName("btnToggleStatus")
        self.actionRow.addWidget(self.btnToggleStatus)
        self.btnDuplicateDiscount = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnDuplicateDiscount.setMinimumSize(QtCore.QSize(135, 38))
        self.btnDuplicateDiscount.setObjectName("btnDuplicateDiscount")
        self.actionRow.addWidget(self.btnDuplicateDiscount)
        self.btnViewUsage = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnViewUsage.setMinimumSize(QtCore.QSize(150, 38))
        self.btnViewUsage.setObjectName("btnViewUsage")
        self.actionRow.addWidget(self.btnViewUsage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.actionRow.addItem(spacerItem1)
        self.btnExportDiscount = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnExportDiscount.setMinimumSize(QtCore.QSize(130, 38))
        self.btnExportDiscount.setObjectName("btnExportDiscount")
        self.actionRow.addWidget(self.btnExportDiscount)
        self.listLayout.addLayout(self.actionRow)
        self.rightLayout.addWidget(self.listPanel)
        self.statPanel = QtWidgets.QFrame(parent=DiscountPage)
        self.statPanel.setMaximumSize(QtCore.QSize(16777215, 150))
        self.statPanel.setObjectName("statPanel")
        self.statLayout = QtWidgets.QVBoxLayout(self.statPanel)
        self.statLayout.setContentsMargins(12, 10, 12, 10)
        self.statLayout.setSpacing(8)
        self.statLayout.setObjectName("statLayout")
        self.lblUsageTitle = QtWidgets.QLabel(parent=self.statPanel)
        self.lblUsageTitle.setObjectName("lblUsageTitle")
        self.statLayout.addWidget(self.lblUsageTitle)
        self.tableUsageStats = QtWidgets.QTableWidget(parent=self.statPanel)
        self.tableUsageStats.setMinimumSize(QtCore.QSize(0, 85))
        self.tableUsageStats.setColumnCount(5)
        self.tableUsageStats.setObjectName("tableUsageStats")
        self.tableUsageStats.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsageStats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsageStats.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsageStats.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsageStats.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsageStats.setHorizontalHeaderItem(4, item)
        self.statLayout.addWidget(self.tableUsageStats)
        self.rightLayout.addWidget(self.statPanel)
        self.contentLayout.addLayout(self.rightLayout)
        self.mainLayout.addLayout(self.contentLayout)

        self.retranslateUi(DiscountPage)
        QtCore.QMetaObject.connectSlotsByName(DiscountPage)

    def retranslateUi(self, DiscountPage):
        _translate = QtCore.QCoreApplication.translate
        DiscountPage.setStyleSheet(_translate("DiscountPage", "\n"
"QWidget#DiscountPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#formPanel,\n"
"QFrame#listPanel,\n"
"QFrame#testPanel,\n"
"QFrame#statPanel,\n"
"QFrame#summaryCard1,\n"
"QFrame#summaryCard2,\n"
"QFrame#summaryCard3,\n"
"QFrame#summaryCard4 {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame#previewBox {\n"
"    background-color: #eff6ff;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statNumber {\n"
"    color: #2563eb;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel#lblPreview,\n"
"QLabel#lblTestResult {\n"
"    color: #1e3a8a;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QComboBox,\n"
"QDateEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QTextEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus,\n"
"QDateEdit:focus,\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QTextEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down,\n"
"QDateEdit::drop-down,\n"
"QSpinBox::drop-down,\n"
"QDoubleSpinBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox::down-arrow,\n"
"QDateEdit::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px 10px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnAddDiscount,\n"
"QPushButton#btnSearch,\n"
"QPushButton#btnCheckCode,\n"
"QPushButton#btnViewUsage {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnUpdateDiscount,\n"
"QPushButton#btnToggleStatus {\n"
"    background-color: #16a34a;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnDeleteDiscount {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnClearForm,\n"
"QPushButton#btnRefresh,\n"
"QPushButton#btnClearFilter,\n"
"QPushButton#btnExportDiscount {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnDuplicateDiscount {\n"
"    background-color: #7c3aed;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblTotalDiscount.setText(_translate("DiscountPage", "0"))
        self.lblTotalDiscount.setProperty("class", _translate("DiscountPage", "statNumber"))
        self.lblTotalDiscountText.setText(_translate("DiscountPage", "Tổng mã giảm giá"))
        self.lblTotalDiscountText.setProperty("class", _translate("DiscountPage", "statText"))
        self.lblActiveDiscount.setText(_translate("DiscountPage", "0"))
        self.lblActiveDiscount.setProperty("class", _translate("DiscountPage", "statNumber"))
        self.lblActiveDiscountText.setText(_translate("DiscountPage", "Đang bật"))
        self.lblActiveDiscountText.setProperty("class", _translate("DiscountPage", "statText"))
        self.lblExpiredDiscount.setText(_translate("DiscountPage", "0"))
        self.lblExpiredDiscount.setProperty("class", _translate("DiscountPage", "statNumber"))
        self.lblExpiredDiscountText.setText(_translate("DiscountPage", "Đã hết hạn"))
        self.lblExpiredDiscountText.setProperty("class", _translate("DiscountPage", "statText"))
        self.lblTotalDiscountUsed.setText(_translate("DiscountPage", "0"))
        self.lblTotalDiscountUsed.setProperty("class", _translate("DiscountPage", "statNumber"))
        self.lblTotalDiscountUsedText.setText(_translate("DiscountPage", "Tổng lượt đã dùng"))
        self.lblTotalDiscountUsedText.setProperty("class", _translate("DiscountPage", "statText"))
        self.lblFormTitle.setText(_translate("DiscountPage", "🎯 Thêm / sửa mã giảm giá"))
        self.lblFormTitle.setProperty("class", _translate("DiscountPage", "sectionTitle"))
        self.lblCode.setText(_translate("DiscountPage", "Mã giảm giá"))
        self.lblCode.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.txtCode.setPlaceholderText(_translate("DiscountPage", "VD: SALE10, TET2026"))
        self.lblType.setText(_translate("DiscountPage", "Loại giảm"))
        self.lblType.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.lblValue.setText(_translate("DiscountPage", "Giá trị"))
        self.lblValue.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.cboDiscountType.setItemText(0, _translate("DiscountPage", "percent"))
        self.cboDiscountType.setItemText(1, _translate("DiscountPage", "fixed"))
        self.lblMaxDiscount.setText(_translate("DiscountPage", "Giảm tối đa"))
        self.lblMaxDiscount.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.lblMinOrder.setText(_translate("DiscountPage", "Đơn tối thiểu"))
        self.lblMinOrder.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.spinMaxDiscount.setSuffix(_translate("DiscountPage", " đ"))
        self.spinMinOrder.setSuffix(_translate("DiscountPage", " đ"))
        self.lblUsageLimit.setText(_translate("DiscountPage", "Số lượt tối đa"))
        self.lblUsageLimit.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.lblPerCustomerLimit.setText(_translate("DiscountPage", "Mỗi khách"))
        self.lblPerCustomerLimit.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.lblStartDate.setText(_translate("DiscountPage", "Ngày bắt đầu"))
        self.lblStartDate.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.lblEndDate.setText(_translate("DiscountPage", "Ngày kết thúc"))
        self.lblEndDate.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.dateStart.setDisplayFormat(_translate("DiscountPage", "dd/MM/yyyy"))
        self.dateEnd.setDisplayFormat(_translate("DiscountPage", "dd/MM/yyyy"))
        self.lblStatus.setText(_translate("DiscountPage", "Trạng thái bật/tắt"))
        self.lblStatus.setProperty("class", _translate("DiscountPage", "formLabel"))
        self.cboStatus.setItemText(0, _translate("DiscountPage", "active"))
        self.cboStatus.setItemText(1, _translate("DiscountPage", "inactive"))
        self.cboStatus.setItemText(2, _translate("DiscountPage", "expired"))
        self.lblPreview.setText(_translate("DiscountPage", "Preview: nhập thông tin để xem mô tả mã giảm"))
        self.btnAddDiscount.setText(_translate("DiscountPage", "➕ Thêm"))
        self.btnUpdateDiscount.setText(_translate("DiscountPage", "💾 Sửa"))
        self.btnDeleteDiscount.setText(_translate("DiscountPage", "🗑 Xóa"))
        self.btnClearForm.setText(_translate("DiscountPage", "🧹 Xóa form"))
        self.lblTestTitle.setText(_translate("DiscountPage", "🧪 Kiểm tra mã hợp lệ khi bán hàng"))
        self.lblTestTitle.setProperty("class", _translate("DiscountPage", "sectionTitle"))
        self.txtTestCode.setPlaceholderText(_translate("DiscountPage", "Nhập mã cần test"))
        self.spinTestOrderAmount.setSuffix(_translate("DiscountPage", " đ đơn hàng"))
        self.btnCheckCode.setText(_translate("DiscountPage", "✅ Kiểm tra"))
        self.lblTestResult.setText(_translate("DiscountPage", "Kết quả: ---"))
        self.lblListTitle.setText(_translate("DiscountPage", "📋 Danh sách mã giảm giá"))
        self.lblListTitle.setProperty("class", _translate("DiscountPage", "sectionTitle"))
        self.txtSearch.setPlaceholderText(_translate("DiscountPage", "🔍 Tìm mã..."))
        self.cboFilterStatus.setItemText(0, _translate("DiscountPage", "Tất cả"))
        self.cboFilterStatus.setItemText(1, _translate("DiscountPage", "active"))
        self.cboFilterStatus.setItemText(2, _translate("DiscountPage", "inactive"))
        self.cboFilterStatus.setItemText(3, _translate("DiscountPage", "expired"))
        self.cboFilterType.setItemText(0, _translate("DiscountPage", "Tất cả loại"))
        self.cboFilterType.setItemText(1, _translate("DiscountPage", "percent"))
        self.cboFilterType.setItemText(2, _translate("DiscountPage", "fixed"))
        self.btnSearch.setText(_translate("DiscountPage", "🔍 Tìm"))
        self.btnClearFilter.setText(_translate("DiscountPage", "🧹 Xóa lọc"))
        self.btnRefresh.setText(_translate("DiscountPage", "🔄 Mới"))
        item = self.tableDiscount.horizontalHeaderItem(0)
        item.setText(_translate("DiscountPage", "ID"))
        item = self.tableDiscount.horizontalHeaderItem(1)
        item.setText(_translate("DiscountPage", "Mã"))
        item = self.tableDiscount.horizontalHeaderItem(2)
        item.setText(_translate("DiscountPage", "Loại"))
        item = self.tableDiscount.horizontalHeaderItem(3)
        item.setText(_translate("DiscountPage", "Giá trị"))
        item = self.tableDiscount.horizontalHeaderItem(4)
        item.setText(_translate("DiscountPage", "Giảm tối đa"))
        item = self.tableDiscount.horizontalHeaderItem(5)
        item.setText(_translate("DiscountPage", "Đơn tối thiểu"))
        item = self.tableDiscount.horizontalHeaderItem(6)
        item.setText(_translate("DiscountPage", "Đã dùng"))
        item = self.tableDiscount.horizontalHeaderItem(7)
        item.setText(_translate("DiscountPage", "Lượt tối đa"))
        item = self.tableDiscount.horizontalHeaderItem(8)
        item.setText(_translate("DiscountPage", "Mỗi khách"))
        item = self.tableDiscount.horizontalHeaderItem(9)
        item.setText(_translate("DiscountPage", "Bắt đầu"))
        item = self.tableDiscount.horizontalHeaderItem(10)
        item.setText(_translate("DiscountPage", "Kết thúc"))
        item = self.tableDiscount.horizontalHeaderItem(11)
        item.setText(_translate("DiscountPage", "Trạng thái"))
        item = self.tableDiscount.horizontalHeaderItem(12)
        item.setText(_translate("DiscountPage", "Doanh thu áp mã"))
        self.btnToggleStatus.setText(_translate("DiscountPage", "🔁 Bật / tắt mã"))
        self.btnDuplicateDiscount.setText(_translate("DiscountPage", "📋 Nhân bản mã"))
        self.btnViewUsage.setText(_translate("DiscountPage", "📊 Thống kê sử dụng"))
        self.btnExportDiscount.setText(_translate("DiscountPage", "📤 Xuất danh sách"))
        self.lblUsageTitle.setText(_translate("DiscountPage", "📈 Thống kê mã dùng nhiều"))
        self.lblUsageTitle.setProperty("class", _translate("DiscountPage", "sectionTitle"))
        item = self.tableUsageStats.horizontalHeaderItem(0)
        item.setText(_translate("DiscountPage", "Top"))
        item = self.tableUsageStats.horizontalHeaderItem(1)
        item.setText(_translate("DiscountPage", "Mã"))
        item = self.tableUsageStats.horizontalHeaderItem(2)
        item.setText(_translate("DiscountPage", "Số lượt dùng"))
        item = self.tableUsageStats.horizontalHeaderItem(3)
        item.setText(_translate("DiscountPage", "Tổng giảm"))
        item = self.tableUsageStats.horizontalHeaderItem(4)
        item.setText(_translate("DiscountPage", "Doanh thu áp mã"))
