# Form implementation generated from reading ui file 'app/view/ui/human_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HumanPage(object):
    def setupUi(self, HumanPage):
        HumanPage.setObjectName("HumanPage")
        HumanPage.resize(1050, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(HumanPage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.summaryCard1 = QtWidgets.QFrame(parent=HumanPage)
        self.summaryCard1.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard1.setObjectName("summaryCard1")
        self.summaryCard1Layout = QtWidgets.QVBoxLayout(self.summaryCard1)
        self.summaryCard1Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard1Layout.setObjectName("summaryCard1Layout")
        self.lblTotalUsers = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalUsers.setObjectName("lblTotalUsers")
        self.summaryCard1Layout.addWidget(self.lblTotalUsers)
        self.lblTotalUsersText = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalUsersText.setObjectName("lblTotalUsersText")
        self.summaryCard1Layout.addWidget(self.lblTotalUsersText)
        self.summaryLayout.addWidget(self.summaryCard1)
        self.summaryCard2 = QtWidgets.QFrame(parent=HumanPage)
        self.summaryCard2.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard2.setObjectName("summaryCard2")
        self.summaryCard2Layout = QtWidgets.QVBoxLayout(self.summaryCard2)
        self.summaryCard2Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard2Layout.setObjectName("summaryCard2Layout")
        self.lblActiveUsers = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblActiveUsers.setObjectName("lblActiveUsers")
        self.summaryCard2Layout.addWidget(self.lblActiveUsers)
        self.lblActiveUsersText = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblActiveUsersText.setObjectName("lblActiveUsersText")
        self.summaryCard2Layout.addWidget(self.lblActiveUsersText)
        self.summaryLayout.addWidget(self.summaryCard2)
        self.summaryCard3 = QtWidgets.QFrame(parent=HumanPage)
        self.summaryCard3.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard3.setObjectName("summaryCard3")
        self.summaryCard3Layout = QtWidgets.QVBoxLayout(self.summaryCard3)
        self.summaryCard3Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard3Layout.setObjectName("summaryCard3Layout")
        self.lblSaleUsers = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblSaleUsers.setObjectName("lblSaleUsers")
        self.summaryCard3Layout.addWidget(self.lblSaleUsers)
        self.lblSaleUsersText = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblSaleUsersText.setObjectName("lblSaleUsersText")
        self.summaryCard3Layout.addWidget(self.lblSaleUsersText)
        self.summaryLayout.addWidget(self.summaryCard3)
        self.summaryCard4 = QtWidgets.QFrame(parent=HumanPage)
        self.summaryCard4.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard4.setObjectName("summaryCard4")
        self.summaryCard4Layout = QtWidgets.QVBoxLayout(self.summaryCard4)
        self.summaryCard4Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard4Layout.setObjectName("summaryCard4Layout")
        self.lblSelectedRevenue = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblSelectedRevenue.setObjectName("lblSelectedRevenue")
        self.summaryCard4Layout.addWidget(self.lblSelectedRevenue)
        self.lblSelectedRevenueText = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblSelectedRevenueText.setObjectName("lblSelectedRevenueText")
        self.summaryCard4Layout.addWidget(self.lblSelectedRevenueText)
        self.summaryLayout.addWidget(self.summaryCard4)
        self.mainLayout.addLayout(self.summaryLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.contentLayout.setObjectName("contentLayout")
        self.formPanel = QtWidgets.QFrame(parent=HumanPage)
        self.formPanel.setMinimumSize(QtCore.QSize(350, 0))
        self.formPanel.setMaximumSize(QtCore.QSize(385, 16777215))
        self.formPanel.setObjectName("formPanel")
        self.formLayout = QtWidgets.QVBoxLayout(self.formPanel)
        self.formLayout.setContentsMargins(14, 12, 14, 12)
        self.formLayout.setSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.lblFormTitle = QtWidgets.QLabel(parent=self.formPanel)
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formLayout.addWidget(self.lblFormTitle)
        self.lblFullName = QtWidgets.QLabel(parent=self.formPanel)
        self.lblFullName.setObjectName("lblFullName")
        self.formLayout.addWidget(self.lblFullName)
        self.txtFullName = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtFullName.setMinimumSize(QtCore.QSize(0, 38))
        self.txtFullName.setObjectName("txtFullName")
        self.formLayout.addWidget(self.txtFullName)
        self.userTitleLayout = QtWidgets.QHBoxLayout()
        self.userTitleLayout.setSpacing(8)
        self.userTitleLayout.setObjectName("userTitleLayout")
        self.lblUsername = QtWidgets.QLabel(parent=self.formPanel)
        self.lblUsername.setObjectName("lblUsername")
        self.userTitleLayout.addWidget(self.lblUsername)
        self.lblPhone = QtWidgets.QLabel(parent=self.formPanel)
        self.lblPhone.setObjectName("lblPhone")
        self.userTitleLayout.addWidget(self.lblPhone)
        self.formLayout.addLayout(self.userTitleLayout)
        self.userPhoneLayout = QtWidgets.QHBoxLayout()
        self.userPhoneLayout.setSpacing(8)
        self.userPhoneLayout.setObjectName("userPhoneLayout")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtUsername.setMinimumSize(QtCore.QSize(0, 38))
        self.txtUsername.setObjectName("txtUsername")
        self.userPhoneLayout.addWidget(self.txtUsername)
        self.txtPhone = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtPhone.setMinimumSize(QtCore.QSize(0, 38))
        self.txtPhone.setObjectName("txtPhone")
        self.userPhoneLayout.addWidget(self.txtPhone)
        self.formLayout.addLayout(self.userPhoneLayout)
        self.lblEmail = QtWidgets.QLabel(parent=self.formPanel)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.addWidget(self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtEmail.setMinimumSize(QtCore.QSize(0, 38))
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.addWidget(self.txtEmail)
        self.roleStatusTitleLayout = QtWidgets.QHBoxLayout()
        self.roleStatusTitleLayout.setSpacing(8)
        self.roleStatusTitleLayout.setObjectName("roleStatusTitleLayout")
        self.lblRole = QtWidgets.QLabel(parent=self.formPanel)
        self.lblRole.setObjectName("lblRole")
        self.roleStatusTitleLayout.addWidget(self.lblRole)
        self.lblStatus = QtWidgets.QLabel(parent=self.formPanel)
        self.lblStatus.setObjectName("lblStatus")
        self.roleStatusTitleLayout.addWidget(self.lblStatus)
        self.formLayout.addLayout(self.roleStatusTitleLayout)
        self.roleStatusLayout = QtWidgets.QHBoxLayout()
        self.roleStatusLayout.setSpacing(8)
        self.roleStatusLayout.setObjectName("roleStatusLayout")
        self.cboRole = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboRole.setMinimumSize(QtCore.QSize(0, 38))
        self.cboRole.setObjectName("cboRole")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.roleStatusLayout.addWidget(self.cboRole)
        self.cboStatus = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboStatus.setMinimumSize(QtCore.QSize(0, 38))
        self.cboStatus.setObjectName("cboStatus")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.roleStatusLayout.addWidget(self.cboStatus)
        self.formLayout.addLayout(self.roleStatusLayout)
        self.passwordBox = QtWidgets.QFrame(parent=self.formPanel)
        self.passwordBox.setObjectName("passwordBox")
        self.passwordLayout = QtWidgets.QVBoxLayout(self.passwordBox)
        self.passwordLayout.setContentsMargins(12, 10, 12, 10)
        self.passwordLayout.setSpacing(7)
        self.passwordLayout.setObjectName("passwordLayout")
        self.lblPasswordTitle = QtWidgets.QLabel(parent=self.passwordBox)
        self.lblPasswordTitle.setObjectName("lblPasswordTitle")
        self.passwordLayout.addWidget(self.lblPasswordTitle)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.passwordBox)
        self.txtPassword.setMinimumSize(QtCore.QSize(0, 38))
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.passwordLayout.addWidget(self.txtPassword)
        self.txtConfirmPassword = QtWidgets.QLineEdit(parent=self.passwordBox)
        self.txtConfirmPassword.setMinimumSize(QtCore.QSize(0, 38))
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.passwordLayout.addWidget(self.txtConfirmPassword)
        self.btnResetPassword = QtWidgets.QPushButton(parent=self.passwordBox)
        self.btnResetPassword.setMinimumSize(QtCore.QSize(0, 38))
        self.btnResetPassword.setObjectName("btnResetPassword")
        self.passwordLayout.addWidget(self.btnResetPassword)
        self.formLayout.addWidget(self.passwordBox)
        self.buttonRow1 = QtWidgets.QHBoxLayout()
        self.buttonRow1.setSpacing(8)
        self.buttonRow1.setObjectName("buttonRow1")
        self.btnAddUser = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnAddUser.setMinimumSize(QtCore.QSize(0, 38))
        self.btnAddUser.setObjectName("btnAddUser")
        self.buttonRow1.addWidget(self.btnAddUser)
        self.btnUpdateUser = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnUpdateUser.setMinimumSize(QtCore.QSize(0, 38))
        self.btnUpdateUser.setObjectName("btnUpdateUser")
        self.buttonRow1.addWidget(self.btnUpdateUser)
        self.formLayout.addLayout(self.buttonRow1)
        self.buttonRow2 = QtWidgets.QHBoxLayout()
        self.buttonRow2.setSpacing(8)
        self.buttonRow2.setObjectName("buttonRow2")
        self.btnDeleteUser = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnDeleteUser.setMinimumSize(QtCore.QSize(0, 38))
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.buttonRow2.addWidget(self.btnDeleteUser)
        self.btnClearForm = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnClearForm.setMinimumSize(QtCore.QSize(0, 38))
        self.btnClearForm.setObjectName("btnClearForm")
        self.buttonRow2.addWidget(self.btnClearForm)
        self.formLayout.addLayout(self.buttonRow2)
        self.btnToggleStatus = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnToggleStatus.setMinimumSize(QtCore.QSize(0, 38))
        self.btnToggleStatus.setObjectName("btnToggleStatus")
        self.formLayout.addWidget(self.btnToggleStatus)
        self.btnGrantManager = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnGrantManager.setMinimumSize(QtCore.QSize(0, 38))
        self.btnGrantManager.setObjectName("btnGrantManager")
        self.formLayout.addWidget(self.btnGrantManager)
        self.contentLayout.addWidget(self.formPanel)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.listPanel = QtWidgets.QFrame(parent=HumanPage)
        self.listPanel.setObjectName("listPanel")
        self.listLayout = QtWidgets.QVBoxLayout(self.listPanel)
        self.listLayout.setContentsMargins(12, 10, 12, 10)
        self.listLayout.setSpacing(8)
        self.listLayout.setObjectName("listLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.lblListTitle = QtWidgets.QLabel(parent=self.listPanel)
        self.lblListTitle.setObjectName("lblListTitle")
        self.filterLayout.addWidget(self.lblListTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.txtSearch = QtWidgets.QLineEdit(parent=self.listPanel)
        self.txtSearch.setMinimumSize(QtCore.QSize(210, 36))
        self.txtSearch.setObjectName("txtSearch")
        self.filterLayout.addWidget(self.txtSearch)
        self.cboFilterRole = QtWidgets.QComboBox(parent=self.listPanel)
        self.cboFilterRole.setMinimumSize(QtCore.QSize(120, 36))
        self.cboFilterRole.setObjectName("cboFilterRole")
        self.cboFilterRole.addItem("")
        self.cboFilterRole.addItem("")
        self.cboFilterRole.addItem("")
        self.cboFilterRole.addItem("")
        self.cboFilterRole.addItem("")
        self.cboFilterRole.addItem("")
        self.filterLayout.addWidget(self.cboFilterRole)
        self.cboFilterStatus = QtWidgets.QComboBox(parent=self.listPanel)
        self.cboFilterStatus.setMinimumSize(QtCore.QSize(115, 36))
        self.cboFilterStatus.setObjectName("cboFilterStatus")
        self.cboFilterStatus.addItem("")
        self.cboFilterStatus.addItem("")
        self.cboFilterStatus.addItem("")
        self.cboFilterStatus.addItem("")
        self.filterLayout.addWidget(self.cboFilterStatus)
        self.btnSearch = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnSearch.setMinimumSize(QtCore.QSize(82, 36))
        self.btnSearch.setObjectName("btnSearch")
        self.filterLayout.addWidget(self.btnSearch)
        self.btnClearFilter = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnClearFilter.setMinimumSize(QtCore.QSize(88, 36))
        self.btnClearFilter.setObjectName("btnClearFilter")
        self.filterLayout.addWidget(self.btnClearFilter)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnRefresh.setMinimumSize(QtCore.QSize(82, 36))
        self.btnRefresh.setObjectName("btnRefresh")
        self.filterLayout.addWidget(self.btnRefresh)
        self.listLayout.addLayout(self.filterLayout)
        self.tableUsers = QtWidgets.QTableWidget(parent=self.listPanel)
        self.tableUsers.setMinimumSize(QtCore.QSize(0, 250))
        self.tableUsers.setColumnCount(10)
        self.tableUsers.setObjectName("tableUsers")
        self.tableUsers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(9, item)
        self.listLayout.addWidget(self.tableUsers)
        self.listActionLayout = QtWidgets.QHBoxLayout()
        self.listActionLayout.setSpacing(8)
        self.listActionLayout.setObjectName("listActionLayout")
        self.btnViewPerformance = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnViewPerformance.setMinimumSize(QtCore.QSize(150, 38))
        self.btnViewPerformance.setObjectName("btnViewPerformance")
        self.listActionLayout.addWidget(self.btnViewPerformance)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.listActionLayout.addItem(spacerItem1)
        self.btnExportHuman = QtWidgets.QPushButton(parent=self.listPanel)
        self.btnExportHuman.setMinimumSize(QtCore.QSize(130, 38))
        self.btnExportHuman.setObjectName("btnExportHuman")
        self.listActionLayout.addWidget(self.btnExportHuman)
        self.listLayout.addLayout(self.listActionLayout)
        self.rightLayout.addWidget(self.listPanel)
        self.performancePanel = QtWidgets.QFrame(parent=HumanPage)
        self.performancePanel.setObjectName("performancePanel")
        self.performanceLayout = QtWidgets.QVBoxLayout(self.performancePanel)
        self.performanceLayout.setContentsMargins(12, 10, 12, 10)
        self.performanceLayout.setSpacing(8)
        self.performanceLayout.setObjectName("performanceLayout")
        self.lblPerformanceTitle = QtWidgets.QLabel(parent=self.performancePanel)
        self.lblPerformanceTitle.setObjectName("lblPerformanceTitle")
        self.performanceLayout.addWidget(self.lblPerformanceTitle)
        self.tablePerformance = QtWidgets.QTableWidget(parent=self.performancePanel)
        self.tablePerformance.setMinimumSize(QtCore.QSize(0, 125))
        self.tablePerformance.setColumnCount(5)
        self.tablePerformance.setObjectName("tablePerformance")
        self.tablePerformance.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePerformance.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePerformance.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePerformance.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePerformance.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePerformance.setHorizontalHeaderItem(4, item)
        self.performanceLayout.addWidget(self.tablePerformance)
        self.rightLayout.addWidget(self.performancePanel)
        self.contentLayout.addLayout(self.rightLayout)
        self.mainLayout.addLayout(self.contentLayout)

        self.retranslateUi(HumanPage)
        QtCore.QMetaObject.connectSlotsByName(HumanPage)

    def retranslateUi(self, HumanPage):
        _translate = QtCore.QCoreApplication.translate
        HumanPage.setStyleSheet(_translate("HumanPage", "\n"
"QWidget#HumanPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#formPanel,\n"
"QFrame#listPanel,\n"
"QFrame#performancePanel,\n"
"QFrame#summaryCard1,\n"
"QFrame#summaryCard2,\n"
"QFrame#summaryCard3,\n"
"QFrame#summaryCard4,\n"
"QFrame#passwordBox {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame#passwordBox {\n"
"    background-color: #f8fbff;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statNumber {\n"
"    color: #2563eb;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QComboBox,\n"
"QDateEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus,\n"
"QDateEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down,\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox::down-arrow,\n"
"QDateEdit::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px 10px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnAddUser,\n"
"QPushButton#btnSearch,\n"
"QPushButton#btnViewPerformance {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnUpdateUser,\n"
"QPushButton#btnResetPassword,\n"
"QPushButton#btnToggleStatus {\n"
"    background-color: #16a34a;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnDeleteUser {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnClearForm,\n"
"QPushButton#btnRefresh,\n"
"QPushButton#btnClearFilter,\n"
"QPushButton#btnExportHuman {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnGrantManager {\n"
"    background-color: #7c3aed;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblTotalUsers.setText(_translate("HumanPage", "0"))
        self.lblTotalUsers.setProperty("class", _translate("HumanPage", "statNumber"))
        self.lblTotalUsersText.setText(_translate("HumanPage", "Tổng nhân sự"))
        self.lblTotalUsersText.setProperty("class", _translate("HumanPage", "statText"))
        self.lblActiveUsers.setText(_translate("HumanPage", "0"))
        self.lblActiveUsers.setProperty("class", _translate("HumanPage", "statNumber"))
        self.lblActiveUsersText.setText(_translate("HumanPage", "Tài khoản hoạt động"))
        self.lblActiveUsersText.setProperty("class", _translate("HumanPage", "statText"))
        self.lblSaleUsers.setText(_translate("HumanPage", "0"))
        self.lblSaleUsers.setProperty("class", _translate("HumanPage", "statNumber"))
        self.lblSaleUsersText.setText(_translate("HumanPage", "Nhân viên bán hàng"))
        self.lblSaleUsersText.setProperty("class", _translate("HumanPage", "statText"))
        self.lblSelectedRevenue.setText(_translate("HumanPage", "0 đ"))
        self.lblSelectedRevenue.setProperty("class", _translate("HumanPage", "statNumber"))
        self.lblSelectedRevenueText.setText(_translate("HumanPage", "Doanh số NV đang chọn"))
        self.lblSelectedRevenueText.setProperty("class", _translate("HumanPage", "statText"))
        self.lblFormTitle.setText(_translate("HumanPage", "👨‍💼 Hồ sơ nhân sự"))
        self.lblFormTitle.setProperty("class", _translate("HumanPage", "sectionTitle"))
        self.lblFullName.setText(_translate("HumanPage", "Họ tên"))
        self.lblFullName.setProperty("class", _translate("HumanPage", "formLabel"))
        self.txtFullName.setPlaceholderText(_translate("HumanPage", "Nhập họ tên nhân viên"))
        self.lblUsername.setText(_translate("HumanPage", "Tên đăng nhập"))
        self.lblUsername.setProperty("class", _translate("HumanPage", "formLabel"))
        self.lblPhone.setText(_translate("HumanPage", "SĐT"))
        self.lblPhone.setProperty("class", _translate("HumanPage", "formLabel"))
        self.txtUsername.setPlaceholderText(_translate("HumanPage", "username"))
        self.txtPhone.setPlaceholderText(_translate("HumanPage", "098..."))
        self.lblEmail.setText(_translate("HumanPage", "Email"))
        self.lblEmail.setProperty("class", _translate("HumanPage", "formLabel"))
        self.txtEmail.setPlaceholderText(_translate("HumanPage", "email@gmail.com"))
        self.lblRole.setText(_translate("HumanPage", "Vai trò"))
        self.lblRole.setProperty("class", _translate("HumanPage", "formLabel"))
        self.lblStatus.setText(_translate("HumanPage", "Trạng thái"))
        self.lblStatus.setProperty("class", _translate("HumanPage", "formLabel"))
        self.cboRole.setItemText(0, _translate("HumanPage", "admin"))
        self.cboRole.setItemText(1, _translate("HumanPage", "quản lý"))
        self.cboRole.setItemText(2, _translate("HumanPage", "sale"))
        self.cboRole.setItemText(3, _translate("HumanPage", "nhân viên"))
        self.cboRole.setItemText(4, _translate("HumanPage", "kỹ thuật"))
        self.cboStatus.setItemText(0, _translate("HumanPage", "active"))
        self.cboStatus.setItemText(1, _translate("HumanPage", "inactive"))
        self.cboStatus.setItemText(2, _translate("HumanPage", "locked"))
        self.lblPasswordTitle.setText(_translate("HumanPage", "🔐 Mật khẩu"))
        self.lblPasswordTitle.setProperty("class", _translate("HumanPage", "sectionTitle"))
        self.txtPassword.setPlaceholderText(_translate("HumanPage", "Mật khẩu khi thêm mới / đổi mật khẩu"))
        self.txtConfirmPassword.setPlaceholderText(_translate("HumanPage", "Nhập lại mật khẩu"))
        self.btnResetPassword.setText(_translate("HumanPage", "🔑 Đổi mật khẩu"))
        self.btnAddUser.setText(_translate("HumanPage", "➕ Thêm"))
        self.btnUpdateUser.setText(_translate("HumanPage", "💾 Sửa"))
        self.btnDeleteUser.setText(_translate("HumanPage", "🗑 Xóa"))
        self.btnClearForm.setText(_translate("HumanPage", "🧹 Xóa form"))
        self.btnToggleStatus.setText(_translate("HumanPage", "🔁 Bật / tắt tài khoản"))
        self.btnGrantManager.setText(_translate("HumanPage", "⭐ Gán quyền quản lý"))
        self.lblListTitle.setText(_translate("HumanPage", "📋 Danh sách nhân sự"))
        self.lblListTitle.setProperty("class", _translate("HumanPage", "sectionTitle"))
        self.txtSearch.setPlaceholderText(_translate("HumanPage", "🔍 Tìm tên, username, SĐT..."))
        self.cboFilterRole.setItemText(0, _translate("HumanPage", "Tất cả vai trò"))
        self.cboFilterRole.setItemText(1, _translate("HumanPage", "admin"))
        self.cboFilterRole.setItemText(2, _translate("HumanPage", "quản lý"))
        self.cboFilterRole.setItemText(3, _translate("HumanPage", "sale"))
        self.cboFilterRole.setItemText(4, _translate("HumanPage", "nhân viên"))
        self.cboFilterRole.setItemText(5, _translate("HumanPage", "kỹ thuật"))
        self.cboFilterStatus.setItemText(0, _translate("HumanPage", "Tất cả trạng thái"))
        self.cboFilterStatus.setItemText(1, _translate("HumanPage", "active"))
        self.cboFilterStatus.setItemText(2, _translate("HumanPage", "inactive"))
        self.cboFilterStatus.setItemText(3, _translate("HumanPage", "locked"))
        self.btnSearch.setText(_translate("HumanPage", "🔍 Tìm"))
        self.btnClearFilter.setText(_translate("HumanPage", "🧹 Xóa lọc"))
        self.btnRefresh.setText(_translate("HumanPage", "🔄 Mới"))
        item = self.tableUsers.horizontalHeaderItem(0)
        item.setText(_translate("HumanPage", "ID"))
        item = self.tableUsers.horizontalHeaderItem(1)
        item.setText(_translate("HumanPage", "Họ tên"))
        item = self.tableUsers.horizontalHeaderItem(2)
        item.setText(_translate("HumanPage", "Username"))
        item = self.tableUsers.horizontalHeaderItem(3)
        item.setText(_translate("HumanPage", "SĐT"))
        item = self.tableUsers.horizontalHeaderItem(4)
        item.setText(_translate("HumanPage", "Email"))
        item = self.tableUsers.horizontalHeaderItem(5)
        item.setText(_translate("HumanPage", "Vai trò"))
        item = self.tableUsers.horizontalHeaderItem(6)
        item.setText(_translate("HumanPage", "Trạng thái"))
        item = self.tableUsers.horizontalHeaderItem(7)
        item.setText(_translate("HumanPage", "Số đơn"))
        item = self.tableUsers.horizontalHeaderItem(8)
        item.setText(_translate("HumanPage", "Doanh số"))
        item = self.tableUsers.horizontalHeaderItem(9)
        item.setText(_translate("HumanPage", "Ngày tạo"))
        self.btnViewPerformance.setText(_translate("HumanPage", "📊 Xem doanh số NV"))
        self.btnExportHuman.setText(_translate("HumanPage", "📤 Xuất danh sách"))
        self.lblPerformanceTitle.setText(_translate("HumanPage", "🏆 Doanh số theo nhân viên"))
        self.lblPerformanceTitle.setProperty("class", _translate("HumanPage", "sectionTitle"))
        item = self.tablePerformance.horizontalHeaderItem(0)
        item.setText(_translate("HumanPage", "Top"))
        item = self.tablePerformance.horizontalHeaderItem(1)
        item.setText(_translate("HumanPage", "Nhân viên"))
        item = self.tablePerformance.horizontalHeaderItem(2)
        item.setText(_translate("HumanPage", "Số đơn"))
        item = self.tablePerformance.horizontalHeaderItem(3)
        item.setText(_translate("HumanPage", "Doanh số"))
        item = self.tablePerformance.horizontalHeaderItem(4)
        item.setText(_translate("HumanPage", "Trung bình/đơn"))
