# Form implementation generated from reading ui file 'app/view/ui/invoice_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InvoicePage(object):
    def setupUi(self, InvoicePage):
        InvoicePage.setObjectName("InvoicePage")
        InvoicePage.resize(1050, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(InvoicePage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.summaryCard1 = QtWidgets.QFrame(parent=InvoicePage)
        self.summaryCard1.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard1.setObjectName("summaryCard1")
        self.summaryCard1Layout = QtWidgets.QVBoxLayout(self.summaryCard1)
        self.summaryCard1Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard1Layout.setObjectName("summaryCard1Layout")
        self.lblTotalInvoices = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalInvoices.setObjectName("lblTotalInvoices")
        self.summaryCard1Layout.addWidget(self.lblTotalInvoices)
        self.lblTotalInvoicesText = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalInvoicesText.setObjectName("lblTotalInvoicesText")
        self.summaryCard1Layout.addWidget(self.lblTotalInvoicesText)
        self.summaryLayout.addWidget(self.summaryCard1)
        self.summaryCard2 = QtWidgets.QFrame(parent=InvoicePage)
        self.summaryCard2.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard2.setObjectName("summaryCard2")
        self.summaryCard2Layout = QtWidgets.QVBoxLayout(self.summaryCard2)
        self.summaryCard2Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard2Layout.setObjectName("summaryCard2Layout")
        self.lblTodayRevenue = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblTodayRevenue.setObjectName("lblTodayRevenue")
        self.summaryCard2Layout.addWidget(self.lblTodayRevenue)
        self.lblTodayRevenueText = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblTodayRevenueText.setObjectName("lblTodayRevenueText")
        self.summaryCard2Layout.addWidget(self.lblTodayRevenueText)
        self.summaryLayout.addWidget(self.summaryCard2)
        self.summaryCard3 = QtWidgets.QFrame(parent=InvoicePage)
        self.summaryCard3.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard3.setObjectName("summaryCard3")
        self.summaryCard3Layout = QtWidgets.QVBoxLayout(self.summaryCard3)
        self.summaryCard3Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard3Layout.setObjectName("summaryCard3Layout")
        self.lblMonthRevenue = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblMonthRevenue.setObjectName("lblMonthRevenue")
        self.summaryCard3Layout.addWidget(self.lblMonthRevenue)
        self.lblMonthRevenueText = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblMonthRevenueText.setObjectName("lblMonthRevenueText")
        self.summaryCard3Layout.addWidget(self.lblMonthRevenueText)
        self.summaryLayout.addWidget(self.summaryCard3)
        self.summaryCard4 = QtWidgets.QFrame(parent=InvoicePage)
        self.summaryCard4.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard4.setObjectName("summaryCard4")
        self.summaryCard4Layout = QtWidgets.QVBoxLayout(self.summaryCard4)
        self.summaryCard4Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard4Layout.setObjectName("summaryCard4Layout")
        self.lblCancelledInvoices = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblCancelledInvoices.setObjectName("lblCancelledInvoices")
        self.summaryCard4Layout.addWidget(self.lblCancelledInvoices)
        self.lblCancelledInvoicesText = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblCancelledInvoicesText.setObjectName("lblCancelledInvoicesText")
        self.summaryCard4Layout.addWidget(self.lblCancelledInvoicesText)
        self.summaryLayout.addWidget(self.summaryCard4)
        self.mainLayout.addLayout(self.summaryLayout)
        self.filterPanel = QtWidgets.QFrame(parent=InvoicePage)
        self.filterPanel.setMaximumSize(QtCore.QSize(16777215, 104))
        self.filterPanel.setObjectName("filterPanel")
        self.filterPanelLayout = QtWidgets.QVBoxLayout(self.filterPanel)
        self.filterPanelLayout.setContentsMargins(12, 10, 12, 10)
        self.filterPanelLayout.setSpacing(8)
        self.filterPanelLayout.setObjectName("filterPanelLayout")
        self.lblFilterTitle = QtWidgets.QLabel(parent=self.filterPanel)
        self.lblFilterTitle.setObjectName("lblFilterTitle")
        self.filterPanelLayout.addWidget(self.lblFilterTitle)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.txtSearchInvoice = QtWidgets.QLineEdit(parent=self.filterPanel)
        self.txtSearchInvoice.setMinimumSize(QtCore.QSize(260, 38))
        self.txtSearchInvoice.setObjectName("txtSearchInvoice")
        self.filterLayout.addWidget(self.txtSearchInvoice)
        self.cboPaymentFilter = QtWidgets.QComboBox(parent=self.filterPanel)
        self.cboPaymentFilter.setMinimumSize(QtCore.QSize(175, 38))
        self.cboPaymentFilter.setObjectName("cboPaymentFilter")
        self.cboPaymentFilter.addItem("")
        self.cboPaymentFilter.addItem("")
        self.cboPaymentFilter.addItem("")
        self.filterLayout.addWidget(self.cboPaymentFilter)
        self.cboStatusFilter = QtWidgets.QComboBox(parent=self.filterPanel)
        self.cboStatusFilter.setMinimumSize(QtCore.QSize(165, 38))
        self.cboStatusFilter.setObjectName("cboStatusFilter")
        self.cboStatusFilter.addItem("")
        self.cboStatusFilter.addItem("")
        self.cboStatusFilter.addItem("")
        self.cboStatusFilter.addItem("")
        self.filterLayout.addWidget(self.cboStatusFilter)
        self.dateFrom = QtWidgets.QDateEdit(parent=self.filterPanel)
        self.dateFrom.setMinimumSize(QtCore.QSize(135, 38))
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.filterLayout.addWidget(self.dateFrom)
        self.dateTo = QtWidgets.QDateEdit(parent=self.filterPanel)
        self.dateTo.setMinimumSize(QtCore.QSize(135, 38))
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.filterLayout.addWidget(self.dateTo)
        self.btnSearch = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnSearch.setMinimumSize(QtCore.QSize(82, 38))
        self.btnSearch.setObjectName("btnSearch")
        self.filterLayout.addWidget(self.btnSearch)
        self.btnClearFilter = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnClearFilter.setMinimumSize(QtCore.QSize(92, 38))
        self.btnClearFilter.setObjectName("btnClearFilter")
        self.filterLayout.addWidget(self.btnClearFilter)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnRefresh.setMinimumSize(QtCore.QSize(82, 38))
        self.btnRefresh.setObjectName("btnRefresh")
        self.filterLayout.addWidget(self.btnRefresh)
        self.filterPanelLayout.addLayout(self.filterLayout)
        self.mainLayout.addWidget(self.filterPanel)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.contentLayout.setObjectName("contentLayout")
        self.invoicePanel = QtWidgets.QFrame(parent=InvoicePage)
        self.invoicePanel.setObjectName("invoicePanel")
        self.invoicePanelLayout = QtWidgets.QVBoxLayout(self.invoicePanel)
        self.invoicePanelLayout.setContentsMargins(12, 10, 12, 10)
        self.invoicePanelLayout.setSpacing(8)
        self.invoicePanelLayout.setObjectName("invoicePanelLayout")
        self.invoiceTitleLayout = QtWidgets.QHBoxLayout()
        self.invoiceTitleLayout.setObjectName("invoiceTitleLayout")
        self.lblInvoiceListTitle = QtWidgets.QLabel(parent=self.invoicePanel)
        self.lblInvoiceListTitle.setObjectName("lblInvoiceListTitle")
        self.invoiceTitleLayout.addWidget(self.lblInvoiceListTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.invoiceTitleLayout.addItem(spacerItem)
        self.btnViewDetail = QtWidgets.QPushButton(parent=self.invoicePanel)
        self.btnViewDetail.setMinimumSize(QtCore.QSize(110, 36))
        self.btnViewDetail.setObjectName("btnViewDetail")
        self.invoiceTitleLayout.addWidget(self.btnViewDetail)
        self.btnReprintInvoice = QtWidgets.QPushButton(parent=self.invoicePanel)
        self.btnReprintInvoice.setMinimumSize(QtCore.QSize(120, 36))
        self.btnReprintInvoice.setObjectName("btnReprintInvoice")
        self.invoiceTitleLayout.addWidget(self.btnReprintInvoice)
        self.invoicePanelLayout.addLayout(self.invoiceTitleLayout)
        self.tableInvoices = QtWidgets.QTableWidget(parent=self.invoicePanel)
        self.tableInvoices.setMinimumSize(QtCore.QSize(0, 310))
        self.tableInvoices.setColumnCount(10)
        self.tableInvoices.setObjectName("tableInvoices")
        self.tableInvoices.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoices.setHorizontalHeaderItem(9, item)
        self.invoicePanelLayout.addWidget(self.tableInvoices)
        self.contentLayout.addWidget(self.invoicePanel)
        self.detailPanel = QtWidgets.QFrame(parent=InvoicePage)
        self.detailPanel.setMinimumSize(QtCore.QSize(420, 0))
        self.detailPanel.setMaximumSize(QtCore.QSize(470, 16777215))
        self.detailPanel.setObjectName("detailPanel")
        self.detailPanelLayout = QtWidgets.QVBoxLayout(self.detailPanel)
        self.detailPanelLayout.setContentsMargins(12, 10, 12, 10)
        self.detailPanelLayout.setSpacing(8)
        self.detailPanelLayout.setObjectName("detailPanelLayout")
        self.lblDetailTitle = QtWidgets.QLabel(parent=self.detailPanel)
        self.lblDetailTitle.setObjectName("lblDetailTitle")
        self.detailPanelLayout.addWidget(self.lblDetailTitle)
        self.detailInfoBox = QtWidgets.QFrame(parent=self.detailPanel)
        self.detailInfoBox.setObjectName("detailInfoBox")
        self.detailInfoLayout = QtWidgets.QGridLayout(self.detailInfoBox)
        self.detailInfoLayout.setContentsMargins(12, 10, 12, 10)
        self.detailInfoLayout.setHorizontalSpacing(10)
        self.detailInfoLayout.setVerticalSpacing(7)
        self.detailInfoLayout.setObjectName("detailInfoLayout")
        self.lblInvoiceIdText = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblInvoiceIdText.setMinimumSize(QtCore.QSize(82, 0))
        self.lblInvoiceIdText.setObjectName("lblInvoiceIdText")
        self.detailInfoLayout.addWidget(self.lblInvoiceIdText, 0, 0, 1, 1)
        self.lblInvoiceIdValue = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblInvoiceIdValue.setObjectName("lblInvoiceIdValue")
        self.detailInfoLayout.addWidget(self.lblInvoiceIdValue, 0, 1, 1, 1)
        self.lblCreatedAtText = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblCreatedAtText.setObjectName("lblCreatedAtText")
        self.detailInfoLayout.addWidget(self.lblCreatedAtText, 1, 0, 1, 1)
        self.lblCreatedAtValue = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblCreatedAtValue.setObjectName("lblCreatedAtValue")
        self.detailInfoLayout.addWidget(self.lblCreatedAtValue, 1, 1, 1, 1)
        self.lblCustomerText = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblCustomerText.setObjectName("lblCustomerText")
        self.detailInfoLayout.addWidget(self.lblCustomerText, 2, 0, 1, 1)
        self.lblCustomerValue = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblCustomerValue.setObjectName("lblCustomerValue")
        self.detailInfoLayout.addWidget(self.lblCustomerValue, 2, 1, 1, 1)
        self.lblPhoneText = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblPhoneText.setObjectName("lblPhoneText")
        self.detailInfoLayout.addWidget(self.lblPhoneText, 3, 0, 1, 1)
        self.lblPhoneValue = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblPhoneValue.setObjectName("lblPhoneValue")
        self.detailInfoLayout.addWidget(self.lblPhoneValue, 3, 1, 1, 1)
        self.lblStaffText = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblStaffText.setObjectName("lblStaffText")
        self.detailInfoLayout.addWidget(self.lblStaffText, 4, 0, 1, 1)
        self.lblStaffValue = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblStaffValue.setObjectName("lblStaffValue")
        self.detailInfoLayout.addWidget(self.lblStaffValue, 4, 1, 1, 1)
        self.lblPaymentText = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblPaymentText.setObjectName("lblPaymentText")
        self.detailInfoLayout.addWidget(self.lblPaymentText, 5, 0, 1, 1)
        self.lblPaymentValue = QtWidgets.QLabel(parent=self.detailInfoBox)
        self.lblPaymentValue.setObjectName("lblPaymentValue")
        self.detailInfoLayout.addWidget(self.lblPaymentValue, 5, 1, 1, 1)
        self.detailPanelLayout.addWidget(self.detailInfoBox)
        self.tableInvoiceItems = QtWidgets.QTableWidget(parent=self.detailPanel)
        self.tableInvoiceItems.setMinimumSize(QtCore.QSize(0, 160))
        self.tableInvoiceItems.setColumnCount(5)
        self.tableInvoiceItems.setObjectName("tableInvoiceItems")
        self.tableInvoiceItems.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoiceItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoiceItems.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoiceItems.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoiceItems.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInvoiceItems.setHorizontalHeaderItem(4, item)
        self.detailPanelLayout.addWidget(self.tableInvoiceItems)
        self.moneyBox = QtWidgets.QFrame(parent=self.detailPanel)
        self.moneyBox.setObjectName("moneyBox")
        self.moneyDetailLayout = QtWidgets.QGridLayout(self.moneyBox)
        self.moneyDetailLayout.setContentsMargins(12, 8, 12, 8)
        self.moneyDetailLayout.setHorizontalSpacing(10)
        self.moneyDetailLayout.setVerticalSpacing(7)
        self.moneyDetailLayout.setObjectName("moneyDetailLayout")
        self.lblSubtotalText = QtWidgets.QLabel(parent=self.moneyBox)
        self.lblSubtotalText.setObjectName("lblSubtotalText")
        self.moneyDetailLayout.addWidget(self.lblSubtotalText, 0, 0, 1, 1)
        self.lblSubtotalValue = QtWidgets.QLabel(parent=self.moneyBox)
        self.lblSubtotalValue.setObjectName("lblSubtotalValue")
        self.moneyDetailLayout.addWidget(self.lblSubtotalValue, 0, 1, 1, 1)
        self.lblDiscountText = QtWidgets.QLabel(parent=self.moneyBox)
        self.lblDiscountText.setObjectName("lblDiscountText")
        self.moneyDetailLayout.addWidget(self.lblDiscountText, 1, 0, 1, 1)
        self.lblDiscountValue = QtWidgets.QLabel(parent=self.moneyBox)
        self.lblDiscountValue.setObjectName("lblDiscountValue")
        self.moneyDetailLayout.addWidget(self.lblDiscountValue, 1, 1, 1, 1)
        self.lblTotalText = QtWidgets.QLabel(parent=self.moneyBox)
        self.lblTotalText.setObjectName("lblTotalText")
        self.moneyDetailLayout.addWidget(self.lblTotalText, 2, 0, 1, 1)
        self.lblTotalValue = QtWidgets.QLabel(parent=self.moneyBox)
        self.lblTotalValue.setObjectName("lblTotalValue")
        self.moneyDetailLayout.addWidget(self.lblTotalValue, 2, 1, 1, 1)
        self.detailPanelLayout.addWidget(self.moneyBox)
        self.detailButtonLayout1 = QtWidgets.QHBoxLayout()
        self.detailButtonLayout1.setSpacing(8)
        self.detailButtonLayout1.setObjectName("detailButtonLayout1")
        self.btnExportPdf = QtWidgets.QPushButton(parent=self.detailPanel)
        self.btnExportPdf.setMinimumSize(QtCore.QSize(0, 40))
        self.btnExportPdf.setObjectName("btnExportPdf")
        self.detailButtonLayout1.addWidget(self.btnExportPdf)
        self.btnCancelInvoice = QtWidgets.QPushButton(parent=self.detailPanel)
        self.btnCancelInvoice.setMinimumSize(QtCore.QSize(0, 40))
        self.btnCancelInvoice.setObjectName("btnCancelInvoice")
        self.detailButtonLayout1.addWidget(self.btnCancelInvoice)
        self.detailPanelLayout.addLayout(self.detailButtonLayout1)
        self.btnReturnItem = QtWidgets.QPushButton(parent=self.detailPanel)
        self.btnReturnItem.setMinimumSize(QtCore.QSize(0, 40))
        self.btnReturnItem.setObjectName("btnReturnItem")
        self.detailPanelLayout.addWidget(self.btnReturnItem)
        self.contentLayout.addWidget(self.detailPanel)
        self.mainLayout.addLayout(self.contentLayout)

        self.retranslateUi(InvoicePage)
        QtCore.QMetaObject.connectSlotsByName(InvoicePage)

    def retranslateUi(self, InvoicePage):
        _translate = QtCore.QCoreApplication.translate
        InvoicePage.setStyleSheet(_translate("InvoicePage", "\n"
"QWidget#InvoicePage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#filterPanel,\n"
"QFrame#invoicePanel,\n"
"QFrame#detailPanel,\n"
"QFrame#summaryCard1,\n"
"QFrame#summaryCard2,\n"
"QFrame#summaryCard3,\n"
"QFrame#summaryCard4,\n"
"QFrame#detailInfoBox,\n"
"QFrame#moneyBox {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame#detailInfoBox,\n"
"QFrame#moneyBox {\n"
"    background-color: #f8fbff;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.valueLabel {\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statNumber {\n"
"    color: #2563eb;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QDateEdit,\n"
"QComboBox {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QDateEdit:focus,\n"
"QComboBox:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down,\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px 10px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnSearch,\n"
"QPushButton#btnViewDetail,\n"
"QPushButton#btnExportPdf,\n"
"QPushButton#btnReprintInvoice {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnRefresh,\n"
"QPushButton#btnClearFilter {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnCancelInvoice {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnReturnItem {\n"
"    background-color: #f59e0b;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblTotalInvoices.setText(_translate("InvoicePage", "0"))
        self.lblTotalInvoices.setProperty("class", _translate("InvoicePage", "statNumber"))
        self.lblTotalInvoicesText.setText(_translate("InvoicePage", "Tổng hóa đơn"))
        self.lblTotalInvoicesText.setProperty("class", _translate("InvoicePage", "statText"))
        self.lblTodayRevenue.setText(_translate("InvoicePage", "0 đ"))
        self.lblTodayRevenue.setProperty("class", _translate("InvoicePage", "statNumber"))
        self.lblTodayRevenueText.setText(_translate("InvoicePage", "Doanh thu hôm nay"))
        self.lblTodayRevenueText.setProperty("class", _translate("InvoicePage", "statText"))
        self.lblMonthRevenue.setText(_translate("InvoicePage", "0 đ"))
        self.lblMonthRevenue.setProperty("class", _translate("InvoicePage", "statNumber"))
        self.lblMonthRevenueText.setText(_translate("InvoicePage", "Doanh thu tháng"))
        self.lblMonthRevenueText.setProperty("class", _translate("InvoicePage", "statText"))
        self.lblCancelledInvoices.setText(_translate("InvoicePage", "0"))
        self.lblCancelledInvoices.setProperty("class", _translate("InvoicePage", "statNumber"))
        self.lblCancelledInvoicesText.setText(_translate("InvoicePage", "Đơn hủy / hoàn"))
        self.lblCancelledInvoicesText.setProperty("class", _translate("InvoicePage", "statText"))
        self.lblFilterTitle.setText(_translate("InvoicePage", "🔍 Bộ lọc hóa đơn"))
        self.lblFilterTitle.setProperty("class", _translate("InvoicePage", "sectionTitle"))
        self.txtSearchInvoice.setPlaceholderText(_translate("InvoicePage", "Tìm mã đơn, SĐT, khách hàng, IMEI..."))
        self.cboPaymentFilter.setItemText(0, _translate("InvoicePage", "Tất cả thanh toán"))
        self.cboPaymentFilter.setItemText(1, _translate("InvoicePage", "Tiền mặt"))
        self.cboPaymentFilter.setItemText(2, _translate("InvoicePage", "QR chuyển khoản"))
        self.cboStatusFilter.setItemText(0, _translate("InvoicePage", "Tất cả trạng thái"))
        self.cboStatusFilter.setItemText(1, _translate("InvoicePage", "paid"))
        self.cboStatusFilter.setItemText(2, _translate("InvoicePage", "cancelled"))
        self.cboStatusFilter.setItemText(3, _translate("InvoicePage", "returned"))
        self.dateFrom.setDisplayFormat(_translate("InvoicePage", "dd/MM/yyyy"))
        self.dateTo.setDisplayFormat(_translate("InvoicePage", "dd/MM/yyyy"))
        self.btnSearch.setText(_translate("InvoicePage", "🔍 Tìm"))
        self.btnClearFilter.setText(_translate("InvoicePage", "🧹 Xóa lọc"))
        self.btnRefresh.setText(_translate("InvoicePage", "🔄 Mới"))
        self.lblInvoiceListTitle.setText(_translate("InvoicePage", "🧾 Danh sách hóa đơn"))
        self.lblInvoiceListTitle.setProperty("class", _translate("InvoicePage", "sectionTitle"))
        self.btnViewDetail.setText(_translate("InvoicePage", "👁 Chi tiết"))
        self.btnReprintInvoice.setText(_translate("InvoicePage", "🖨 In lại"))
        item = self.tableInvoices.horizontalHeaderItem(0)
        item.setText(_translate("InvoicePage", "Mã đơn"))
        item = self.tableInvoices.horizontalHeaderItem(1)
        item.setText(_translate("InvoicePage", "Ngày bán"))
        item = self.tableInvoices.horizontalHeaderItem(2)
        item.setText(_translate("InvoicePage", "Khách hàng"))
        item = self.tableInvoices.horizontalHeaderItem(3)
        item.setText(_translate("InvoicePage", "SĐT"))
        item = self.tableInvoices.horizontalHeaderItem(4)
        item.setText(_translate("InvoicePage", "Số máy"))
        item = self.tableInvoices.horizontalHeaderItem(5)
        item.setText(_translate("InvoicePage", "Tạm tính"))
        item = self.tableInvoices.horizontalHeaderItem(6)
        item.setText(_translate("InvoicePage", "Giảm"))
        item = self.tableInvoices.horizontalHeaderItem(7)
        item.setText(_translate("InvoicePage", "Tổng tiền"))
        item = self.tableInvoices.horizontalHeaderItem(8)
        item.setText(_translate("InvoicePage", "Thanh toán"))
        item = self.tableInvoices.horizontalHeaderItem(9)
        item.setText(_translate("InvoicePage", "Trạng thái"))
        self.lblDetailTitle.setText(_translate("InvoicePage", "📄 Chi tiết hóa đơn"))
        self.lblDetailTitle.setProperty("class", _translate("InvoicePage", "sectionTitle"))
        self.lblInvoiceIdText.setText(_translate("InvoicePage", "Mã đơn:"))
        self.lblInvoiceIdText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblInvoiceIdValue.setText(_translate("InvoicePage", "#---"))
        self.lblInvoiceIdValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblCreatedAtText.setText(_translate("InvoicePage", "Ngày bán:"))
        self.lblCreatedAtText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblCreatedAtValue.setText(_translate("InvoicePage", "---"))
        self.lblCreatedAtValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblCustomerText.setText(_translate("InvoicePage", "Khách:"))
        self.lblCustomerText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblCustomerValue.setText(_translate("InvoicePage", "---"))
        self.lblCustomerValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblPhoneText.setText(_translate("InvoicePage", "SĐT:"))
        self.lblPhoneText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblPhoneValue.setText(_translate("InvoicePage", "---"))
        self.lblPhoneValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblStaffText.setText(_translate("InvoicePage", "Nhân viên:"))
        self.lblStaffText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblStaffValue.setText(_translate("InvoicePage", "---"))
        self.lblStaffValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblPaymentText.setText(_translate("InvoicePage", "Thanh toán:"))
        self.lblPaymentText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblPaymentValue.setText(_translate("InvoicePage", "---"))
        self.lblPaymentValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        item = self.tableInvoiceItems.horizontalHeaderItem(0)
        item.setText(_translate("InvoicePage", "IMEI"))
        item = self.tableInvoiceItems.horizontalHeaderItem(1)
        item.setText(_translate("InvoicePage", "Sản phẩm"))
        item = self.tableInvoiceItems.horizontalHeaderItem(2)
        item.setText(_translate("InvoicePage", "DL"))
        item = self.tableInvoiceItems.horizontalHeaderItem(3)
        item.setText(_translate("InvoicePage", "Màu"))
        item = self.tableInvoiceItems.horizontalHeaderItem(4)
        item.setText(_translate("InvoicePage", "Giá"))
        self.lblSubtotalText.setText(_translate("InvoicePage", "Tạm tính:"))
        self.lblSubtotalText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblSubtotalValue.setText(_translate("InvoicePage", "0 đ"))
        self.lblSubtotalValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblDiscountText.setText(_translate("InvoicePage", "Giảm giá:"))
        self.lblDiscountText.setProperty("class", _translate("InvoicePage", "formLabel"))
        self.lblDiscountValue.setText(_translate("InvoicePage", "0 đ"))
        self.lblDiscountValue.setProperty("class", _translate("InvoicePage", "valueLabel"))
        self.lblTotalText.setText(_translate("InvoicePage", "Tổng tiền:"))
        self.lblTotalText.setStyleSheet(_translate("InvoicePage", "color: #1e3a8a; font-size: 15px; font-weight: bold;"))
        self.lblTotalValue.setText(_translate("InvoicePage", "0 đ"))
        self.lblTotalValue.setStyleSheet(_translate("InvoicePage", "color: #dc2626; font-size: 20px; font-weight: bold;"))
        self.btnExportPdf.setText(_translate("InvoicePage", "📄 Xuất PDF"))
        self.btnCancelInvoice.setText(_translate("InvoicePage", "❌ Hủy đơn"))
        self.btnReturnItem.setText(_translate("InvoicePage", "↩ Hoàn hàng / trả lại IMEI vào kho"))
