# Form implementation generated from reading ui file 'app/view/ui/product_stock.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductStockPage(object):
    def setupUi(self, ProductStockPage):
        ProductStockPage.setObjectName("ProductStockPage")
        ProductStockPage.resize(1050, 560)
        self.contentLayout = QtWidgets.QHBoxLayout(ProductStockPage)
        self.contentLayout.setContentsMargins(14, 10, 14, 10)
        self.contentLayout.setSpacing(12)
        self.contentLayout.setObjectName("contentLayout")
        self.formPanel = QtWidgets.QFrame(parent=ProductStockPage)
        self.formPanel.setMinimumSize(QtCore.QSize(350, 0))
        self.formPanel.setMaximumSize(QtCore.QSize(380, 16777215))
        self.formPanel.setObjectName("formPanel")
        self.formLayout = QtWidgets.QVBoxLayout(self.formPanel)
        self.formLayout.setContentsMargins(12, 10, 12, 10)
        self.formLayout.setSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.lblFormTitle = QtWidgets.QLabel(parent=self.formPanel)
        self.lblFormTitle.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formLayout.addWidget(self.lblFormTitle)
        self.lblName = QtWidgets.QLabel(parent=self.formPanel)
        self.lblName.setObjectName("lblName")
        self.formLayout.addWidget(self.lblName)
        self.cboProductName = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboProductName.setEditable(True)
        self.cboProductName.setMinimumSize(QtCore.QSize(0, 36))
        self.cboProductName.setObjectName("cboProductName")
        self.formLayout.addWidget(self.cboProductName)
        self.lblBrand = QtWidgets.QLabel(parent=self.formPanel)
        self.lblBrand.setObjectName("lblBrand")
        self.formLayout.addWidget(self.lblBrand)
        self.txtBrand = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtBrand.setMinimumSize(QtCore.QSize(0, 36))
        self.txtBrand.setObjectName("txtBrand")
        self.formLayout.addWidget(self.txtBrand)
        self.variantTitleLayout = QtWidgets.QHBoxLayout()
        self.variantTitleLayout.setSpacing(8)
        self.variantTitleLayout.setObjectName("variantTitleLayout")
        self.lblStorage = QtWidgets.QLabel(parent=self.formPanel)
        self.lblStorage.setObjectName("lblStorage")
        self.variantTitleLayout.addWidget(self.lblStorage)
        self.lblColor = QtWidgets.QLabel(parent=self.formPanel)
        self.lblColor.setObjectName("lblColor")
        self.variantTitleLayout.addWidget(self.lblColor)
        self.formLayout.addLayout(self.variantTitleLayout)
        self.variantLayout = QtWidgets.QHBoxLayout()
        self.variantLayout.setSpacing(8)
        self.variantLayout.setObjectName("variantLayout")
        self.cboStorage = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboStorage.setEditable(True)
        self.cboStorage.setMinimumSize(QtCore.QSize(0, 36))
        self.cboStorage.setObjectName("cboStorage")
        self.cboStorage.addItem("")
        self.cboStorage.addItem("")
        self.cboStorage.addItem("")
        self.cboStorage.addItem("")
        self.cboStorage.addItem("")
        self.variantLayout.addWidget(self.cboStorage)
        self.cboColor = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboColor.setEditable(True)
        self.cboColor.setMinimumSize(QtCore.QSize(0, 36))
        self.cboColor.setObjectName("cboColor")
        self.cboColor.addItem("")
        self.cboColor.addItem("")
        self.cboColor.addItem("")
        self.cboColor.addItem("")
        self.cboColor.addItem("")
        self.cboColor.addItem("")
        self.variantLayout.addWidget(self.cboColor)
        self.formLayout.addLayout(self.variantLayout)
        self.priceTitleLayout = QtWidgets.QHBoxLayout()
        self.priceTitleLayout.setSpacing(8)
        self.priceTitleLayout.setObjectName("priceTitleLayout")
        self.lblPrice = QtWidgets.QLabel(parent=self.formPanel)
        self.lblPrice.setObjectName("lblPrice")
        self.priceTitleLayout.addWidget(self.lblPrice)
        self.lblImportPrice = QtWidgets.QLabel(parent=self.formPanel)
        self.lblImportPrice.setObjectName("lblImportPrice")
        self.priceTitleLayout.addWidget(self.lblImportPrice)
        self.formLayout.addLayout(self.priceTitleLayout)
        self.priceLayout = QtWidgets.QHBoxLayout()
        self.priceLayout.setSpacing(8)
        self.priceLayout.setObjectName("priceLayout")
        self.spinPrice = QtWidgets.QDoubleSpinBox(parent=self.formPanel)
        self.spinPrice.setMinimumSize(QtCore.QSize(0, 36))
        self.spinPrice.setMaximum(999999999.0)
        self.spinPrice.setSingleStep(100000.0)
        self.spinPrice.setProperty("value", 10000000.0)
        self.spinPrice.setObjectName("spinPrice")
        self.priceLayout.addWidget(self.spinPrice)
        self.spinImportPrice = QtWidgets.QDoubleSpinBox(parent=self.formPanel)
        self.spinImportPrice.setMinimumSize(QtCore.QSize(0, 36))
        self.spinImportPrice.setMaximum(999999999.0)
        self.spinImportPrice.setSingleStep(100000.0)
        self.spinImportPrice.setObjectName("spinImportPrice")
        self.priceLayout.addWidget(self.spinImportPrice)
        self.formLayout.addLayout(self.priceLayout)
        self.lblDescription = QtWidgets.QLabel(parent=self.formPanel)
        self.lblDescription.setObjectName("lblDescription")
        self.formLayout.addWidget(self.lblDescription)
        self.txtDescription = QtWidgets.QLineEdit(parent=self.formPanel)
        self.txtDescription.setMinimumSize(QtCore.QSize(0, 36))
        self.txtDescription.setObjectName("txtDescription")
        self.formLayout.addWidget(self.txtDescription)
        self.lblBulkImei = QtWidgets.QLabel(parent=self.formPanel)
        self.lblBulkImei.setObjectName("lblBulkImei")
        self.formLayout.addWidget(self.lblBulkImei)
        self.txtBulkImei = QtWidgets.QTextEdit(parent=self.formPanel)
        self.txtBulkImei.setMinimumSize(QtCore.QSize(0, 96))
        self.txtBulkImei.setMaximumSize(QtCore.QSize(16777215, 120))
        self.txtBulkImei.setObjectName("txtBulkImei")
        self.formLayout.addWidget(self.txtBulkImei)
        self.btnAdd = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnAdd.setObjectName("btnAdd")
        self.formLayout.addWidget(self.btnAdd)
        self.btnUpdate = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnUpdate.setObjectName("btnUpdate")
        self.formLayout.addWidget(self.btnUpdate)
        self.btnDelete = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnDelete.setObjectName("btnDelete")
        self.formLayout.addWidget(self.btnDelete)
        self.bottomButtonLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonLayout.setSpacing(8)
        self.bottomButtonLayout.setObjectName("bottomButtonLayout")
        self.btnClear = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnClear.setObjectName("btnClear")
        self.bottomButtonLayout.addWidget(self.btnClear)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnRefresh.setObjectName("btnRefresh")
        self.bottomButtonLayout.addWidget(self.btnRefresh)
        self.formLayout.addLayout(self.bottomButtonLayout)
        self.contentLayout.addWidget(self.formPanel)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.tablePanel = QtWidgets.QFrame(parent=ProductStockPage)
        self.tablePanel.setObjectName("tablePanel")
        self.tableLayout = QtWidgets.QVBoxLayout(self.tablePanel)
        self.tableLayout.setContentsMargins(12, 10, 12, 10)
        self.tableLayout.setSpacing(8)
        self.tableLayout.setObjectName("tableLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.searchBox = QtWidgets.QLineEdit(parent=self.tablePanel)
        self.searchBox.setMinimumSize(QtCore.QSize(0, 36))
        self.searchBox.setObjectName("searchBox")
        self.filterLayout.addWidget(self.searchBox)
        self.cboFilterStock = QtWidgets.QComboBox(parent=self.tablePanel)
        self.cboFilterStock.setMinimumSize(QtCore.QSize(145, 36))
        self.cboFilterStock.setObjectName("cboFilterStock")
        self.cboFilterStock.addItem("")
        self.cboFilterStock.addItem("")
        self.cboFilterStock.addItem("")
        self.cboFilterStock.addItem("")
        self.filterLayout.addWidget(self.cboFilterStock)
        self.tableLayout.addLayout(self.filterLayout)
        self.tableProducts = QtWidgets.QTableWidget(parent=self.tablePanel)
        self.tableProducts.setColumnCount(8)
        self.tableProducts.setObjectName("tableProducts")
        self.tableProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(7, item)
        self.tableLayout.addWidget(self.tableProducts)
        self.btnShowVariants = QtWidgets.QPushButton(parent=self.tablePanel)
        self.btnShowVariants.setMaximumSize(QtCore.QSize(16777215, 34))
        self.btnShowVariants.setObjectName("btnShowVariants")
        self.tableLayout.addWidget(self.btnShowVariants)
        self.rightLayout.addWidget(self.tablePanel)
        self.imeiPanel = QtWidgets.QFrame(parent=ProductStockPage)
        self.imeiPanel.setMaximumSize(QtCore.QSize(16777215, 150))
        self.imeiPanel.setObjectName("imeiPanel")
        self.imeiLayout = QtWidgets.QVBoxLayout(self.imeiPanel)
        self.imeiLayout.setContentsMargins(12, 8, 12, 8)
        self.imeiLayout.setSpacing(6)
        self.imeiLayout.setObjectName("imeiLayout")
        self.imeiActionLayout = QtWidgets.QHBoxLayout()
        self.imeiActionLayout.setSpacing(8)
        self.imeiActionLayout.setObjectName("imeiActionLayout")
        self.lblImeiTitle = QtWidgets.QLabel(parent=self.imeiPanel)
        self.lblImeiTitle.setObjectName("lblImeiTitle")
        self.imeiActionLayout.addWidget(self.lblImeiTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.imeiActionLayout.addItem(spacerItem)
        self.btnMarkImeiSold = QtWidgets.QPushButton(parent=self.imeiPanel)
        self.btnMarkImeiSold.setMaximumSize(QtCore.QSize(100, 32))
        self.btnMarkImeiSold.setObjectName("btnMarkImeiSold")
        self.imeiActionLayout.addWidget(self.btnMarkImeiSold)
        self.btnDeleteImei = QtWidgets.QPushButton(parent=self.imeiPanel)
        self.btnDeleteImei.setMaximumSize(QtCore.QSize(85, 32))
        self.btnDeleteImei.setObjectName("btnDeleteImei")
        self.imeiActionLayout.addWidget(self.btnDeleteImei)
        self.imeiLayout.addLayout(self.imeiActionLayout)
        self.tableImeis = QtWidgets.QTableWidget(parent=self.imeiPanel)
        self.tableImeis.setMinimumSize(QtCore.QSize(0, 92))
        self.tableImeis.setMaximumSize(QtCore.QSize(16777215, 92))
        self.tableImeis.setColumnCount(5)
        self.tableImeis.setObjectName("tableImeis")
        self.tableImeis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableImeis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImeis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImeis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImeis.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImeis.setHorizontalHeaderItem(4, item)
        self.imeiLayout.addWidget(self.tableImeis)
        self.rightLayout.addWidget(self.imeiPanel)
        self.warningPanel = QtWidgets.QFrame(parent=ProductStockPage)
        self.warningPanel.setMaximumSize(QtCore.QSize(16777215, 75))
        self.warningPanel.setObjectName("warningPanel")
        self.warningLayout = QtWidgets.QVBoxLayout(self.warningPanel)
        self.warningLayout.setContentsMargins(12, 6, 12, 6)
        self.warningLayout.setSpacing(4)
        self.warningLayout.setObjectName("warningLayout")
        self.lblLowStockTitle = QtWidgets.QLabel(parent=self.warningPanel)
        self.lblLowStockTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblLowStockTitle.setObjectName("lblLowStockTitle")
        self.warningLayout.addWidget(self.lblLowStockTitle)
        self.listLowStock = QtWidgets.QListWidget(parent=self.warningPanel)
        self.listLowStock.setObjectName("listLowStock")
        self.warningLayout.addWidget(self.listLowStock)
        self.rightLayout.addWidget(self.warningPanel)
        self.contentLayout.addLayout(self.rightLayout)

        self.retranslateUi(ProductStockPage)
        QtCore.QMetaObject.connectSlotsByName(ProductStockPage)

    def retranslateUi(self, ProductStockPage):
        _translate = QtCore.QCoreApplication.translate
        ProductStockPage.setStyleSheet(_translate("ProductStockPage", "\n"
"QWidget#ProductStockPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#formPanel,\n"
"QFrame#tablePanel,\n"
"QFrame#imeiPanel,\n"
"QFrame#warningPanel {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QComboBox,\n"
"QDoubleSpinBox,\n"
"QTextEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QTextEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 12px;\n"
"    min-height: 34px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 28px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnAdd {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnUpdate {\n"
"    background-color: #16a34a;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnDelete,\n"
"QPushButton#btnDeleteImei {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnShowVariants {\n"
"    background-color: #dbeafe;\n"
"    color: #1e3a8a;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QPushButton#btnMarkImeiSold {\n"
"    background-color: #f59e0b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnRefresh {\n"
"    background-color: #0f172a;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnClear {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QListWidget {\n"
"    background-color: #fff7ed;\n"
"    border: 1px solid #fed7aa;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: #dc2626;\n"
"    font-size: 12px;\n"
"}\n"
"   "))
        self.lblFormTitle.setText(_translate("ProductStockPage", "📦 Thêm biến thể kèm IMEI"))
        self.lblFormTitle.setStyleSheet(_translate("ProductStockPage", "color: #1e3a8a; font-size: 16px; font-weight: bold;"))
        self.lblName.setText(_translate("ProductStockPage", "Tên sản phẩm"))
        self.lblName.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.lblBrand.setText(_translate("ProductStockPage", "Hãng"))
        self.lblBrand.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.txtBrand.setPlaceholderText(_translate("ProductStockPage", "Apple, Samsung, Xiaomi..."))
        self.lblStorage.setText(_translate("ProductStockPage", "Dung lượng"))
        self.lblStorage.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.lblColor.setText(_translate("ProductStockPage", "Màu sắc"))
        self.lblColor.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.cboStorage.setItemText(0, _translate("ProductStockPage", "64GB"))
        self.cboStorage.setItemText(1, _translate("ProductStockPage", "128GB"))
        self.cboStorage.setItemText(2, _translate("ProductStockPage", "256GB"))
        self.cboStorage.setItemText(3, _translate("ProductStockPage", "512GB"))
        self.cboStorage.setItemText(4, _translate("ProductStockPage", "1TB"))
        self.cboColor.setItemText(0, _translate("ProductStockPage", "Đen"))
        self.cboColor.setItemText(1, _translate("ProductStockPage", "Trắng"))
        self.cboColor.setItemText(2, _translate("ProductStockPage", "Xanh"))
        self.cboColor.setItemText(3, _translate("ProductStockPage", "Vàng"))
        self.cboColor.setItemText(4, _translate("ProductStockPage", "Hồng"))
        self.cboColor.setItemText(5, _translate("ProductStockPage", "Titan"))
        self.lblPrice.setText(_translate("ProductStockPage", "Giá bán"))
        self.lblPrice.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.lblImportPrice.setText(_translate("ProductStockPage", "Giá nhập"))
        self.lblImportPrice.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.spinPrice.setSuffix(_translate("ProductStockPage", " đ"))
        self.spinImportPrice.setSuffix(_translate("ProductStockPage", " đ"))
        self.lblDescription.setText(_translate("ProductStockPage", "Mô tả"))
        self.lblDescription.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.txtDescription.setPlaceholderText(_translate("ProductStockPage", "Mô tả ngắn"))
        self.lblBulkImei.setText(_translate("ProductStockPage", "IMEI nhập kho"))
        self.lblBulkImei.setProperty("class", _translate("ProductStockPage", "formLabel"))
        self.txtBulkImei.setPlaceholderText(_translate("ProductStockPage", "Dán IMEI vào đây, mỗi dòng 1 IMEI. Stock sẽ tự tính theo số IMEI."))
        self.btnAdd.setText(_translate("ProductStockPage", "➕ Thêm biến thể + IMEI"))
        self.btnUpdate.setText(_translate("ProductStockPage", "💾 Cập nhật thông tin biến thể"))
        self.btnDelete.setText(_translate("ProductStockPage", "🗑 Xóa biến thể"))
        self.btnClear.setText(_translate("ProductStockPage", "🧹 Xóa form"))
        self.btnRefresh.setText(_translate("ProductStockPage", "🔄 Làm mới"))
        self.searchBox.setPlaceholderText(_translate("ProductStockPage", "🔍 Tìm sản phẩm, hãng, màu, dung lượng, IMEI..."))
        self.cboFilterStock.setItemText(0, _translate("ProductStockPage", "Tất cả tồn kho"))
        self.cboFilterStock.setItemText(1, _translate("ProductStockPage", "Sắp hết hàng"))
        self.cboFilterStock.setItemText(2, _translate("ProductStockPage", "Còn hàng"))
        self.cboFilterStock.setItemText(3, _translate("ProductStockPage", "Hết hàng"))
        item = self.tableProducts.horizontalHeaderItem(0)
        item.setText(_translate("ProductStockPage", "ID"))
        item = self.tableProducts.horizontalHeaderItem(1)
        item.setText(_translate("ProductStockPage", "Tên sản phẩm"))
        item = self.tableProducts.horizontalHeaderItem(2)
        item.setText(_translate("ProductStockPage", "Hãng"))
        item = self.tableProducts.horizontalHeaderItem(3)
        item.setText(_translate("ProductStockPage", "Dung lượng"))
        item = self.tableProducts.horizontalHeaderItem(4)
        item.setText(_translate("ProductStockPage", "Màu"))
        item = self.tableProducts.horizontalHeaderItem(5)
        item.setText(_translate("ProductStockPage", "Giá bán"))
        item = self.tableProducts.horizontalHeaderItem(6)
        item.setText(_translate("ProductStockPage", "Tồn IMEI"))
        item = self.tableProducts.horizontalHeaderItem(7)
        item.setText(_translate("ProductStockPage", "Mô tả"))
        self.btnShowVariants.setText(_translate("ProductStockPage", "👁 Hiển thị / làm mới danh sách biến thể"))
        self.lblImeiTitle.setText(_translate("ProductStockPage", "📱 IMEI của biến thể đang chọn"))
        self.lblImeiTitle.setStyleSheet(_translate("ProductStockPage", "color: #1e3a8a; font-size: 15px; font-weight: bold;"))
        self.btnMarkImeiSold.setText(_translate("ProductStockPage", "🏷 Đã bán"))
        self.btnDeleteImei.setText(_translate("ProductStockPage", "🗑 Xóa"))
        item = self.tableImeis.horizontalHeaderItem(0)
        item.setText(_translate("ProductStockPage", "ID"))
        item = self.tableImeis.horizontalHeaderItem(1)
        item.setText(_translate("ProductStockPage", "IMEI"))
        item = self.tableImeis.horizontalHeaderItem(2)
        item.setText(_translate("ProductStockPage", "Trạng thái"))
        item = self.tableImeis.horizontalHeaderItem(3)
        item.setText(_translate("ProductStockPage", "Giá nhập"))
        item = self.tableImeis.horizontalHeaderItem(4)
        item.setText(_translate("ProductStockPage", "Ngày nhập"))
        self.lblLowStockTitle.setText(_translate("ProductStockPage", "⚠️ Sản phẩm sắp hết hàng"))
        self.lblLowStockTitle.setStyleSheet(_translate("ProductStockPage", "color: #dc2626; font-size: 15px; font-weight: bold;"))
