# Form implementation generated from reading ui file 'app/view/ui/profile_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfilePage(object):
    def setupUi(self, ProfilePage):
        ProfilePage.setObjectName("ProfilePage")
        ProfilePage.resize(1050, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(ProfilePage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.summaryCard1 = QtWidgets.QFrame(parent=ProfilePage)
        self.summaryCard1.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard1.setObjectName("summaryCard1")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.summaryCard1)
        self.vboxlayout.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblMyInvoices = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblMyInvoices.setObjectName("lblMyInvoices")
        self.vboxlayout.addWidget(self.lblMyInvoices)
        self.lblMyInvoicesText = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblMyInvoicesText.setObjectName("lblMyInvoicesText")
        self.vboxlayout.addWidget(self.lblMyInvoicesText)
        self.summaryLayout.addWidget(self.summaryCard1)
        self.summaryCard2 = QtWidgets.QFrame(parent=ProfilePage)
        self.summaryCard2.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard2.setObjectName("summaryCard2")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.summaryCard2)
        self.vboxlayout1.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.lblMyRevenue = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblMyRevenue.setObjectName("lblMyRevenue")
        self.vboxlayout1.addWidget(self.lblMyRevenue)
        self.lblMyRevenueText = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblMyRevenueText.setObjectName("lblMyRevenueText")
        self.vboxlayout1.addWidget(self.lblMyRevenueText)
        self.summaryLayout.addWidget(self.summaryCard2)
        self.summaryCard3 = QtWidgets.QFrame(parent=ProfilePage)
        self.summaryCard3.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard3.setObjectName("summaryCard3")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.summaryCard3)
        self.vboxlayout2.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.lblMyAov = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblMyAov.setObjectName("lblMyAov")
        self.vboxlayout2.addWidget(self.lblMyAov)
        self.lblMyAovText = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblMyAovText.setObjectName("lblMyAovText")
        self.vboxlayout2.addWidget(self.lblMyAovText)
        self.summaryLayout.addWidget(self.summaryCard3)
        self.summaryCard4 = QtWidgets.QFrame(parent=ProfilePage)
        self.summaryCard4.setMaximumSize(QtCore.QSize(16777215, 74))
        self.summaryCard4.setObjectName("summaryCard4")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.summaryCard4)
        self.vboxlayout3.setContentsMargins(12, 8, 12, 8)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.lblAccountStatus = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblAccountStatus.setObjectName("lblAccountStatus")
        self.vboxlayout3.addWidget(self.lblAccountStatus)
        self.lblAccountStatusText = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblAccountStatusText.setObjectName("lblAccountStatusText")
        self.vboxlayout3.addWidget(self.lblAccountStatusText)
        self.summaryLayout.addWidget(self.summaryCard4)
        self.mainLayout.addLayout(self.summaryLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.contentLayout.setObjectName("contentLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSpacing(10)
        self.leftLayout.setObjectName("leftLayout")
        self.infoPanel = QtWidgets.QFrame(parent=ProfilePage)
        self.infoPanel.setMinimumSize(QtCore.QSize(360, 0))
        self.infoPanel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.infoPanel.setObjectName("infoPanel")
        self.infoLayout = QtWidgets.QVBoxLayout(self.infoPanel)
        self.infoLayout.setContentsMargins(14, 12, 14, 12)
        self.infoLayout.setSpacing(9)
        self.infoLayout.setObjectName("infoLayout")
        self.lblInfoTitle = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblInfoTitle.setObjectName("lblInfoTitle")
        self.infoLayout.addWidget(self.lblInfoTitle)
        self.avatarBox = QtWidgets.QFrame(parent=self.infoPanel)
        self.avatarBox.setMinimumSize(QtCore.QSize(0, 130))
        self.avatarBox.setObjectName("avatarBox")
        self.avatarLayout = QtWidgets.QVBoxLayout(self.avatarBox)
        self.avatarLayout.setContentsMargins(12, 10, 12, 10)
        self.avatarLayout.setObjectName("avatarLayout")
        self.lblAvatar = QtWidgets.QLabel(parent=self.avatarBox)
        self.lblAvatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAvatar.setObjectName("lblAvatar")
        self.avatarLayout.addWidget(self.lblAvatar)
        self.lblProfileName = QtWidgets.QLabel(parent=self.avatarBox)
        self.lblProfileName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblProfileName.setObjectName("lblProfileName")
        self.avatarLayout.addWidget(self.lblProfileName)
        self.lblProfileRole = QtWidgets.QLabel(parent=self.avatarBox)
        self.lblProfileRole.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblProfileRole.setObjectName("lblProfileRole")
        self.avatarLayout.addWidget(self.lblProfileRole)
        self.infoLayout.addWidget(self.avatarBox)
        self.lblFullName = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblFullName.setObjectName("lblFullName")
        self.infoLayout.addWidget(self.lblFullName)
        self.txtFullName = QtWidgets.QLineEdit(parent=self.infoPanel)
        self.txtFullName.setMinimumSize(QtCore.QSize(0, 38))
        self.txtFullName.setObjectName("txtFullName")
        self.infoLayout.addWidget(self.txtFullName)
        self.lblUsername = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblUsername.setObjectName("lblUsername")
        self.infoLayout.addWidget(self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.infoPanel)
        self.txtUsername.setMinimumSize(QtCore.QSize(0, 38))
        self.txtUsername.setReadOnly(True)
        self.txtUsername.setObjectName("txtUsername")
        self.infoLayout.addWidget(self.txtUsername)
        self.contactTitleLayout = QtWidgets.QHBoxLayout()
        self.contactTitleLayout.setSpacing(8)
        self.contactTitleLayout.setObjectName("contactTitleLayout")
        self.lblPhone = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblPhone.setObjectName("lblPhone")
        self.contactTitleLayout.addWidget(self.lblPhone)
        self.lblRole = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblRole.setObjectName("lblRole")
        self.contactTitleLayout.addWidget(self.lblRole)
        self.infoLayout.addLayout(self.contactTitleLayout)
        self.contactLayout = QtWidgets.QHBoxLayout()
        self.contactLayout.setSpacing(8)
        self.contactLayout.setObjectName("contactLayout")
        self.txtPhone = QtWidgets.QLineEdit(parent=self.infoPanel)
        self.txtPhone.setMinimumSize(QtCore.QSize(0, 38))
        self.txtPhone.setObjectName("txtPhone")
        self.contactLayout.addWidget(self.txtPhone)
        self.txtRole = QtWidgets.QLineEdit(parent=self.infoPanel)
        self.txtRole.setMinimumSize(QtCore.QSize(0, 38))
        self.txtRole.setReadOnly(True)
        self.txtRole.setObjectName("txtRole")
        self.contactLayout.addWidget(self.txtRole)
        self.infoLayout.addLayout(self.contactLayout)
        self.lblEmail = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblEmail.setObjectName("lblEmail")
        self.infoLayout.addWidget(self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.infoPanel)
        self.txtEmail.setMinimumSize(QtCore.QSize(0, 38))
        self.txtEmail.setObjectName("txtEmail")
        self.infoLayout.addWidget(self.txtEmail)
        self.lblAddress = QtWidgets.QLabel(parent=self.infoPanel)
        self.lblAddress.setObjectName("lblAddress")
        self.infoLayout.addWidget(self.lblAddress)
        self.txtAddress = QtWidgets.QLineEdit(parent=self.infoPanel)
        self.txtAddress.setMinimumSize(QtCore.QSize(0, 38))
        self.txtAddress.setObjectName("txtAddress")
        self.infoLayout.addWidget(self.txtAddress)
        self.infoButtonLayout = QtWidgets.QHBoxLayout()
        self.infoButtonLayout.setSpacing(8)
        self.infoButtonLayout.setObjectName("infoButtonLayout")
        self.btnUpdateProfile = QtWidgets.QPushButton(parent=self.infoPanel)
        self.btnUpdateProfile.setMinimumSize(QtCore.QSize(0, 38))
        self.btnUpdateProfile.setObjectName("btnUpdateProfile")
        self.infoButtonLayout.addWidget(self.btnUpdateProfile)
        self.btnRefreshProfile = QtWidgets.QPushButton(parent=self.infoPanel)
        self.btnRefreshProfile.setMinimumSize(QtCore.QSize(0, 38))
        self.btnRefreshProfile.setObjectName("btnRefreshProfile")
        self.infoButtonLayout.addWidget(self.btnRefreshProfile)
        self.infoLayout.addLayout(self.infoButtonLayout)
        self.btnLogoutProfile = QtWidgets.QPushButton(parent=self.infoPanel)
        self.btnLogoutProfile.setMinimumSize(QtCore.QSize(0, 38))
        self.btnLogoutProfile.setObjectName("btnLogoutProfile")
        self.infoLayout.addWidget(self.btnLogoutProfile)
        self.leftLayout.addWidget(self.infoPanel)
        self.contentLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.passwordPanel = QtWidgets.QFrame(parent=ProfilePage)
        self.passwordPanel.setMaximumSize(QtCore.QSize(16777215, 160))
        self.passwordPanel.setObjectName("passwordPanel")
        self.passwordLayout = QtWidgets.QVBoxLayout(self.passwordPanel)
        self.passwordLayout.setContentsMargins(14, 12, 14, 12)
        self.passwordLayout.setSpacing(8)
        self.passwordLayout.setObjectName("passwordLayout")
        self.lblPasswordTitle = QtWidgets.QLabel(parent=self.passwordPanel)
        self.lblPasswordTitle.setObjectName("lblPasswordTitle")
        self.passwordLayout.addWidget(self.lblPasswordTitle)
        self.passwordInputLayout = QtWidgets.QHBoxLayout()
        self.passwordInputLayout.setSpacing(8)
        self.passwordInputLayout.setObjectName("passwordInputLayout")
        self.txtOldPassword = QtWidgets.QLineEdit(parent=self.passwordPanel)
        self.txtOldPassword.setMinimumSize(QtCore.QSize(0, 38))
        self.txtOldPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtOldPassword.setObjectName("txtOldPassword")
        self.passwordInputLayout.addWidget(self.txtOldPassword)
        self.txtNewPassword = QtWidgets.QLineEdit(parent=self.passwordPanel)
        self.txtNewPassword.setMinimumSize(QtCore.QSize(0, 38))
        self.txtNewPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtNewPassword.setObjectName("txtNewPassword")
        self.passwordInputLayout.addWidget(self.txtNewPassword)
        self.txtConfirmPassword = QtWidgets.QLineEdit(parent=self.passwordPanel)
        self.txtConfirmPassword.setMinimumSize(QtCore.QSize(0, 38))
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.passwordInputLayout.addWidget(self.txtConfirmPassword)
        self.passwordLayout.addLayout(self.passwordInputLayout)
        self.passwordButtonLayout = QtWidgets.QHBoxLayout()
        self.passwordButtonLayout.setSpacing(8)
        self.passwordButtonLayout.setObjectName("passwordButtonLayout")
        self.btnChangePassword = QtWidgets.QPushButton(parent=self.passwordPanel)
        self.btnChangePassword.setMinimumSize(QtCore.QSize(160, 38))
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.passwordButtonLayout.addWidget(self.btnChangePassword)
        self.btnClearPassword = QtWidgets.QPushButton(parent=self.passwordPanel)
        self.btnClearPassword.setMinimumSize(QtCore.QSize(130, 38))
        self.btnClearPassword.setObjectName("btnClearPassword")
        self.passwordButtonLayout.addWidget(self.btnClearPassword)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.passwordButtonLayout.addItem(spacerItem)
        self.passwordLayout.addLayout(self.passwordButtonLayout)
        self.rightLayout.addWidget(self.passwordPanel)
        self.salesPanel = QtWidgets.QFrame(parent=ProfilePage)
        self.salesPanel.setMaximumSize(QtCore.QSize(16777215, 140))
        self.salesPanel.setObjectName("salesPanel")
        self.salesLayout = QtWidgets.QVBoxLayout(self.salesPanel)
        self.salesLayout.setContentsMargins(14, 12, 14, 12)
        self.salesLayout.setSpacing(8)
        self.salesLayout.setObjectName("salesLayout")
        self.lblSalesTitle = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblSalesTitle.setObjectName("lblSalesTitle")
        self.salesLayout.addWidget(self.lblSalesTitle)
        self.salesGrid = QtWidgets.QGridLayout()
        self.salesGrid.setHorizontalSpacing(12)
        self.salesGrid.setVerticalSpacing(8)
        self.salesGrid.setObjectName("salesGrid")
        self.lblTodayRevenueText = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblTodayRevenueText.setObjectName("lblTodayRevenueText")
        self.salesGrid.addWidget(self.lblTodayRevenueText, 0, 0, 1, 1)
        self.lblTodayRevenueValue = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblTodayRevenueValue.setObjectName("lblTodayRevenueValue")
        self.salesGrid.addWidget(self.lblTodayRevenueValue, 0, 1, 1, 1)
        self.lblMonthRevenueText = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblMonthRevenueText.setObjectName("lblMonthRevenueText")
        self.salesGrid.addWidget(self.lblMonthRevenueText, 0, 2, 1, 1)
        self.lblMonthRevenueValue = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblMonthRevenueValue.setObjectName("lblMonthRevenueValue")
        self.salesGrid.addWidget(self.lblMonthRevenueValue, 0, 3, 1, 1)
        self.lblTodayOrderText = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblTodayOrderText.setObjectName("lblTodayOrderText")
        self.salesGrid.addWidget(self.lblTodayOrderText, 1, 0, 1, 1)
        self.lblTodayOrderValue = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblTodayOrderValue.setObjectName("lblTodayOrderValue")
        self.salesGrid.addWidget(self.lblTodayOrderValue, 1, 1, 1, 1)
        self.lblMonthOrderText = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblMonthOrderText.setObjectName("lblMonthOrderText")
        self.salesGrid.addWidget(self.lblMonthOrderText, 1, 2, 1, 1)
        self.lblMonthOrderValue = QtWidgets.QLabel(parent=self.salesPanel)
        self.lblMonthOrderValue.setObjectName("lblMonthOrderValue")
        self.salesGrid.addWidget(self.lblMonthOrderValue, 1, 3, 1, 1)
        self.salesLayout.addLayout(self.salesGrid)
        self.rightLayout.addWidget(self.salesPanel)
        self.invoicePanel = QtWidgets.QFrame(parent=ProfilePage)
        self.invoicePanel.setObjectName("invoicePanel")
        self.invoiceLayout = QtWidgets.QVBoxLayout(self.invoicePanel)
        self.invoiceLayout.setContentsMargins(14, 12, 14, 12)
        self.invoiceLayout.setSpacing(8)
        self.invoiceLayout.setObjectName("invoiceLayout")
        self.invoiceTitleLayout = QtWidgets.QHBoxLayout()
        self.invoiceTitleLayout.setObjectName("invoiceTitleLayout")
        self.lblInvoiceTitle = QtWidgets.QLabel(parent=self.invoicePanel)
        self.lblInvoiceTitle.setObjectName("lblInvoiceTitle")
        self.invoiceTitleLayout.addWidget(self.lblInvoiceTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.invoiceTitleLayout.addItem(spacerItem1)
        self.btnExportMyInvoices = QtWidgets.QPushButton(parent=self.invoicePanel)
        self.btnExportMyInvoices.setMinimumSize(QtCore.QSize(130, 36))
        self.btnExportMyInvoices.setObjectName("btnExportMyInvoices")
        self.invoiceTitleLayout.addWidget(self.btnExportMyInvoices)
        self.invoiceLayout.addLayout(self.invoiceTitleLayout)
        self.tableMyInvoices = QtWidgets.QTableWidget(parent=self.invoicePanel)
        self.tableMyInvoices.setMinimumSize(QtCore.QSize(0, 210))
        self.tableMyInvoices.setColumnCount(6)
        self.tableMyInvoices.setObjectName("tableMyInvoices")
        self.tableMyInvoices.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMyInvoices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMyInvoices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMyInvoices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMyInvoices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMyInvoices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMyInvoices.setHorizontalHeaderItem(5, item)
        self.invoiceLayout.addWidget(self.tableMyInvoices)
        self.rightLayout.addWidget(self.invoicePanel)
        self.contentLayout.addLayout(self.rightLayout)
        self.mainLayout.addLayout(self.contentLayout)

        self.retranslateUi(ProfilePage)
        QtCore.QMetaObject.connectSlotsByName(ProfilePage)

    def retranslateUi(self, ProfilePage):
        _translate = QtCore.QCoreApplication.translate
        ProfilePage.setStyleSheet(_translate("ProfilePage", "\n"
"QWidget#ProfilePage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#infoPanel,\n"
"QFrame#passwordPanel,\n"
"QFrame#salesPanel,\n"
"QFrame#invoicePanel,\n"
"QFrame#summaryCard1,\n"
"QFrame#summaryCard2,\n"
"QFrame#summaryCard3,\n"
"QFrame#summaryCard4 {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame#avatarBox {\n"
"    background-color: #eff6ff;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.valueLabel {\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statNumber {\n"
"    color: #2563eb;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel#lblAvatar {\n"
"    color: #2563eb;\n"
"    font-size: 54px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#lblProfileName {\n"
"    color: #1e3a8a;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#lblProfileRole {\n"
"    color: #64748b;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QComboBox {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px 10px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnUpdateProfile,\n"
"QPushButton#btnChangePassword,\n"
"QPushButton#btnRefreshProfile {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnClearPassword,\n"
"QPushButton#btnExportMyInvoices {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnLogoutProfile {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblMyInvoices.setText(_translate("ProfilePage", "0"))
        self.lblMyInvoices.setProperty("class", _translate("ProfilePage", "statNumber"))
        self.lblMyInvoicesText.setText(_translate("ProfilePage", "Hóa đơn đã bán"))
        self.lblMyInvoicesText.setProperty("class", _translate("ProfilePage", "statText"))
        self.lblMyRevenue.setText(_translate("ProfilePage", "0 đ"))
        self.lblMyRevenue.setProperty("class", _translate("ProfilePage", "statNumber"))
        self.lblMyRevenueText.setText(_translate("ProfilePage", "Doanh số cá nhân"))
        self.lblMyRevenueText.setProperty("class", _translate("ProfilePage", "statText"))
        self.lblMyAov.setText(_translate("ProfilePage", "0 đ"))
        self.lblMyAov.setProperty("class", _translate("ProfilePage", "statNumber"))
        self.lblMyAovText.setText(_translate("ProfilePage", "Trung bình / đơn"))
        self.lblMyAovText.setProperty("class", _translate("ProfilePage", "statText"))
        self.lblAccountStatus.setText(_translate("ProfilePage", "active"))
        self.lblAccountStatus.setProperty("class", _translate("ProfilePage", "statNumber"))
        self.lblAccountStatusText.setText(_translate("ProfilePage", "Trạng thái tài khoản"))
        self.lblAccountStatusText.setProperty("class", _translate("ProfilePage", "statText"))
        self.lblInfoTitle.setText(_translate("ProfilePage", "👤 Thông tin tài khoản"))
        self.lblInfoTitle.setProperty("class", _translate("ProfilePage", "sectionTitle"))
        self.lblAvatar.setText(_translate("ProfilePage", "👤"))
        self.lblProfileName.setText(_translate("ProfilePage", "---"))
        self.lblProfileRole.setText(_translate("ProfilePage", "---"))
        self.lblFullName.setText(_translate("ProfilePage", "Họ tên"))
        self.lblFullName.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblUsername.setText(_translate("ProfilePage", "Tên đăng nhập"))
        self.lblUsername.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblPhone.setText(_translate("ProfilePage", "SĐT"))
        self.lblPhone.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblRole.setText(_translate("ProfilePage", "Vai trò"))
        self.lblRole.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.txtPhone.setPlaceholderText(_translate("ProfilePage", "Số điện thoại"))
        self.lblEmail.setText(_translate("ProfilePage", "Email"))
        self.lblEmail.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.txtEmail.setPlaceholderText(_translate("ProfilePage", "Email cá nhân"))
        self.lblAddress.setText(_translate("ProfilePage", "Địa chỉ"))
        self.lblAddress.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.txtAddress.setPlaceholderText(_translate("ProfilePage", "Địa chỉ nhận hàng / bảo hành"))
        self.btnUpdateProfile.setText(_translate("ProfilePage", "💾 Cập nhật"))
        self.btnRefreshProfile.setText(_translate("ProfilePage", "🔄 Làm mới"))
        self.btnLogoutProfile.setText(_translate("ProfilePage", "🚪 Đăng xuất"))
        self.lblPasswordTitle.setText(_translate("ProfilePage", "🔐 Đổi mật khẩu"))
        self.lblPasswordTitle.setProperty("class", _translate("ProfilePage", "sectionTitle"))
        self.txtOldPassword.setPlaceholderText(_translate("ProfilePage", "Mật khẩu hiện tại"))
        self.txtNewPassword.setPlaceholderText(_translate("ProfilePage", "Mật khẩu mới"))
        self.txtConfirmPassword.setPlaceholderText(_translate("ProfilePage", "Nhập lại mật khẩu mới"))
        self.btnChangePassword.setText(_translate("ProfilePage", "🔑 Đổi mật khẩu"))
        self.btnClearPassword.setText(_translate("ProfilePage", "🧹 Xóa ô"))
        self.lblSalesTitle.setText(_translate("ProfilePage", "📊 Hiệu suất cá nhân"))
        self.lblSalesTitle.setProperty("class", _translate("ProfilePage", "sectionTitle"))
        self.lblTodayRevenueText.setText(_translate("ProfilePage", "Doanh số hôm nay:"))
        self.lblTodayRevenueText.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblTodayRevenueValue.setText(_translate("ProfilePage", "0 đ"))
        self.lblTodayRevenueValue.setProperty("class", _translate("ProfilePage", "valueLabel"))
        self.lblMonthRevenueText.setText(_translate("ProfilePage", "Doanh số tháng:"))
        self.lblMonthRevenueText.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblMonthRevenueValue.setText(_translate("ProfilePage", "0 đ"))
        self.lblMonthRevenueValue.setProperty("class", _translate("ProfilePage", "valueLabel"))
        self.lblTodayOrderText.setText(_translate("ProfilePage", "Đơn hôm nay:"))
        self.lblTodayOrderText.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblTodayOrderValue.setText(_translate("ProfilePage", "0"))
        self.lblTodayOrderValue.setProperty("class", _translate("ProfilePage", "valueLabel"))
        self.lblMonthOrderText.setText(_translate("ProfilePage", "Đơn tháng:"))
        self.lblMonthOrderText.setProperty("class", _translate("ProfilePage", "formLabel"))
        self.lblMonthOrderValue.setText(_translate("ProfilePage", "0"))
        self.lblMonthOrderValue.setProperty("class", _translate("ProfilePage", "valueLabel"))
        self.lblInvoiceTitle.setText(_translate("ProfilePage", "🧾 Hóa đơn gần đây của tôi"))
        self.lblInvoiceTitle.setProperty("class", _translate("ProfilePage", "sectionTitle"))
        self.btnExportMyInvoices.setText(_translate("ProfilePage", "📤 Xuất danh sách"))
        item = self.tableMyInvoices.horizontalHeaderItem(0)
        item.setText(_translate("ProfilePage", "Mã đơn"))
        item = self.tableMyInvoices.horizontalHeaderItem(1)
        item.setText(_translate("ProfilePage", "Ngày bán"))
        item = self.tableMyInvoices.horizontalHeaderItem(2)
        item.setText(_translate("ProfilePage", "Khách hàng"))
        item = self.tableMyInvoices.horizontalHeaderItem(3)
        item.setText(_translate("ProfilePage", "Số máy"))
        item = self.tableMyInvoices.horizontalHeaderItem(4)
        item.setText(_translate("ProfilePage", "Tổng tiền"))
        item = self.tableMyInvoices.horizontalHeaderItem(5)
        item.setText(_translate("ProfilePage", "Thanh toán"))
