# Form implementation generated from reading ui file 'app/view/ui/report_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReportPage(object):
    def setupUi(self, ReportPage):
        ReportPage.setObjectName("ReportPage")
        ReportPage.resize(1050, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(ReportPage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.filterPanel = QtWidgets.QFrame(parent=ReportPage)
        self.filterPanel.setMaximumSize(QtCore.QSize(16777215, 88))
        self.filterPanel.setObjectName("filterPanel")
        self.filterPanelLayout = QtWidgets.QVBoxLayout(self.filterPanel)
        self.filterPanelLayout.setContentsMargins(12, 10, 12, 10)
        self.filterPanelLayout.setSpacing(8)
        self.filterPanelLayout.setObjectName("filterPanelLayout")
        self.lblFilterTitle = QtWidgets.QLabel(parent=self.filterPanel)
        self.lblFilterTitle.setObjectName("lblFilterTitle")
        self.filterPanelLayout.addWidget(self.lblFilterTitle)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setSpacing(8)
        self.filterLayout.setObjectName("filterLayout")
        self.cboReportType = QtWidgets.QComboBox(parent=self.filterPanel)
        self.cboReportType.setMinimumSize(QtCore.QSize(150, 36))
        self.cboReportType.setObjectName("cboReportType")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.filterLayout.addWidget(self.cboReportType)
        self.dateFrom = QtWidgets.QDateEdit(parent=self.filterPanel)
        self.dateFrom.setMinimumSize(QtCore.QSize(125, 36))
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.filterLayout.addWidget(self.dateFrom)
        self.dateTo = QtWidgets.QDateEdit(parent=self.filterPanel)
        self.dateTo.setMinimumSize(QtCore.QSize(125, 36))
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.filterLayout.addWidget(self.dateTo)
        self.btnViewDay = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnViewDay.setMinimumSize(QtCore.QSize(82, 36))
        self.btnViewDay.setObjectName("btnViewDay")
        self.filterLayout.addWidget(self.btnViewDay)
        self.btnViewMonth = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnViewMonth.setMinimumSize(QtCore.QSize(88, 36))
        self.btnViewMonth.setObjectName("btnViewMonth")
        self.filterLayout.addWidget(self.btnViewMonth)
        self.btnViewYear = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnViewYear.setMinimumSize(QtCore.QSize(82, 36))
        self.btnViewYear.setObjectName("btnViewYear")
        self.filterLayout.addWidget(self.btnViewYear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.btnRefreshReport = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnRefreshReport.setMinimumSize(QtCore.QSize(82, 36))
        self.btnRefreshReport.setObjectName("btnRefreshReport")
        self.filterLayout.addWidget(self.btnRefreshReport)
        self.btnExportCsv = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnExportCsv.setMinimumSize(QtCore.QSize(78, 36))
        self.btnExportCsv.setObjectName("btnExportCsv")
        self.filterLayout.addWidget(self.btnExportCsv)
        self.btnExportExcel = QtWidgets.QPushButton(parent=self.filterPanel)
        self.btnExportExcel.setMinimumSize(QtCore.QSize(78, 36))
        self.btnExportExcel.setObjectName("btnExportExcel")
        self.filterLayout.addWidget(self.btnExportExcel)
        self.filterPanelLayout.addLayout(self.filterLayout)
        self.mainLayout.addWidget(self.filterPanel)
        self.kpiLayout = QtWidgets.QHBoxLayout()
        self.kpiLayout.setSpacing(10)
        self.kpiLayout.setObjectName("kpiLayout")
        self.kpiCardRevenue = QtWidgets.QFrame(parent=ReportPage)
        self.kpiCardRevenue.setMaximumSize(QtCore.QSize(16777215, 76))
        self.kpiCardRevenue.setObjectName("kpiCardRevenue")
        self.kpiRevenueLayout = QtWidgets.QVBoxLayout(self.kpiCardRevenue)
        self.kpiRevenueLayout.setContentsMargins(12, 8, 12, 8)
        self.kpiRevenueLayout.setObjectName("kpiRevenueLayout")
        self.lblRevenueValue = QtWidgets.QLabel(parent=self.kpiCardRevenue)
        self.lblRevenueValue.setObjectName("lblRevenueValue")
        self.kpiRevenueLayout.addWidget(self.lblRevenueValue)
        self.lblRevenueText = QtWidgets.QLabel(parent=self.kpiCardRevenue)
        self.lblRevenueText.setObjectName("lblRevenueText")
        self.kpiRevenueLayout.addWidget(self.lblRevenueText)
        self.kpiLayout.addWidget(self.kpiCardRevenue)
        self.kpiCardProfit = QtWidgets.QFrame(parent=ReportPage)
        self.kpiCardProfit.setMaximumSize(QtCore.QSize(16777215, 76))
        self.kpiCardProfit.setObjectName("kpiCardProfit")
        self.kpiProfitLayout = QtWidgets.QVBoxLayout(self.kpiCardProfit)
        self.kpiProfitLayout.setContentsMargins(12, 8, 12, 8)
        self.kpiProfitLayout.setObjectName("kpiProfitLayout")
        self.lblProfitValue = QtWidgets.QLabel(parent=self.kpiCardProfit)
        self.lblProfitValue.setObjectName("lblProfitValue")
        self.kpiProfitLayout.addWidget(self.lblProfitValue)
        self.lblProfitText = QtWidgets.QLabel(parent=self.kpiCardProfit)
        self.lblProfitText.setObjectName("lblProfitText")
        self.kpiProfitLayout.addWidget(self.lblProfitText)
        self.kpiLayout.addWidget(self.kpiCardProfit)
        self.kpiCardOrders = QtWidgets.QFrame(parent=ReportPage)
        self.kpiCardOrders.setMaximumSize(QtCore.QSize(16777215, 76))
        self.kpiCardOrders.setObjectName("kpiCardOrders")
        self.kpiOrdersLayout = QtWidgets.QVBoxLayout(self.kpiCardOrders)
        self.kpiOrdersLayout.setContentsMargins(12, 8, 12, 8)
        self.kpiOrdersLayout.setObjectName("kpiOrdersLayout")
        self.lblOrderValue = QtWidgets.QLabel(parent=self.kpiCardOrders)
        self.lblOrderValue.setObjectName("lblOrderValue")
        self.kpiOrdersLayout.addWidget(self.lblOrderValue)
        self.lblOrderText = QtWidgets.QLabel(parent=self.kpiCardOrders)
        self.lblOrderText.setObjectName("lblOrderText")
        self.kpiOrdersLayout.addWidget(self.lblOrderText)
        self.kpiLayout.addWidget(self.kpiCardOrders)
        self.kpiCardAov = QtWidgets.QFrame(parent=ReportPage)
        self.kpiCardAov.setMaximumSize(QtCore.QSize(16777215, 76))
        self.kpiCardAov.setObjectName("kpiCardAov")
        self.kpiAovLayout = QtWidgets.QVBoxLayout(self.kpiCardAov)
        self.kpiAovLayout.setContentsMargins(12, 8, 12, 8)
        self.kpiAovLayout.setObjectName("kpiAovLayout")
        self.lblAovValue = QtWidgets.QLabel(parent=self.kpiCardAov)
        self.lblAovValue.setObjectName("lblAovValue")
        self.kpiAovLayout.addWidget(self.lblAovValue)
        self.lblAovText = QtWidgets.QLabel(parent=self.kpiCardAov)
        self.lblAovText.setObjectName("lblAovText")
        self.kpiAovLayout.addWidget(self.lblAovText)
        self.kpiLayout.addWidget(self.kpiCardAov)
        self.mainLayout.addLayout(self.kpiLayout)
        self.chartLayout = QtWidgets.QHBoxLayout()
        self.chartLayout.setSpacing(10)
        self.chartLayout.setObjectName("chartLayout")
        self.chartRevenuePanel = QtWidgets.QFrame(parent=ReportPage)
        self.chartRevenuePanel.setObjectName("chartRevenuePanel")
        self.chartRevenueLayout = QtWidgets.QVBoxLayout(self.chartRevenuePanel)
        self.chartRevenueLayout.setContentsMargins(12, 10, 12, 10)
        self.chartRevenueLayout.setSpacing(8)
        self.chartRevenueLayout.setObjectName("chartRevenueLayout")
        self.lblRevenueChartTitle = QtWidgets.QLabel(parent=self.chartRevenuePanel)
        self.lblRevenueChartTitle.setObjectName("lblRevenueChartTitle")
        self.chartRevenueLayout.addWidget(self.lblRevenueChartTitle)
        self.chartRevenueFrame = QtWidgets.QFrame(parent=self.chartRevenuePanel)
        self.chartRevenueFrame.setMinimumSize(QtCore.QSize(0, 170))
        self.chartRevenueFrame.setObjectName("chartRevenueFrame")
        self.chartRevenueFrameLayout = QtWidgets.QVBoxLayout(self.chartRevenueFrame)
        self.chartRevenueFrameLayout.setObjectName("chartRevenueFrameLayout")
        self.lblRevenueChartPlaceholder = QtWidgets.QLabel(parent=self.chartRevenueFrame)
        self.lblRevenueChartPlaceholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblRevenueChartPlaceholder.setObjectName("lblRevenueChartPlaceholder")
        self.chartRevenueFrameLayout.addWidget(self.lblRevenueChartPlaceholder)
        self.chartRevenueLayout.addWidget(self.chartRevenueFrame)
        self.chartLayout.addWidget(self.chartRevenuePanel)
        self.chartBrandPanel = QtWidgets.QFrame(parent=ReportPage)
        self.chartBrandPanel.setMinimumSize(QtCore.QSize(300, 0))
        self.chartBrandPanel.setMaximumSize(QtCore.QSize(360, 16777215))
        self.chartBrandPanel.setObjectName("chartBrandPanel")
        self.chartBrandLayout = QtWidgets.QVBoxLayout(self.chartBrandPanel)
        self.chartBrandLayout.setContentsMargins(12, 10, 12, 10)
        self.chartBrandLayout.setSpacing(8)
        self.chartBrandLayout.setObjectName("chartBrandLayout")
        self.lblBrandChartTitle = QtWidgets.QLabel(parent=self.chartBrandPanel)
        self.lblBrandChartTitle.setObjectName("lblBrandChartTitle")
        self.chartBrandLayout.addWidget(self.lblBrandChartTitle)
        self.chartBrandFrame = QtWidgets.QFrame(parent=self.chartBrandPanel)
        self.chartBrandFrame.setMinimumSize(QtCore.QSize(0, 170))
        self.chartBrandFrame.setObjectName("chartBrandFrame")
        self.chartBrandFrameLayout = QtWidgets.QVBoxLayout(self.chartBrandFrame)
        self.chartBrandFrameLayout.setObjectName("chartBrandFrameLayout")
        self.lblBrandChartPlaceholder = QtWidgets.QLabel(parent=self.chartBrandFrame)
        self.lblBrandChartPlaceholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblBrandChartPlaceholder.setObjectName("lblBrandChartPlaceholder")
        self.chartBrandFrameLayout.addWidget(self.lblBrandChartPlaceholder)
        self.chartBrandLayout.addWidget(self.chartBrandFrame)
        self.chartLayout.addWidget(self.chartBrandPanel)
        self.mainLayout.addLayout(self.chartLayout)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setSpacing(10)
        self.bottomLayout.setObjectName("bottomLayout")
        self.topProductPanel = QtWidgets.QFrame(parent=ReportPage)
        self.topProductPanel.setObjectName("topProductPanel")
        self.topProductLayout = QtWidgets.QVBoxLayout(self.topProductPanel)
        self.topProductLayout.setContentsMargins(12, 10, 12, 10)
        self.topProductLayout.setSpacing(8)
        self.topProductLayout.setObjectName("topProductLayout")
        self.lblTopProductTitle = QtWidgets.QLabel(parent=self.topProductPanel)
        self.lblTopProductTitle.setObjectName("lblTopProductTitle")
        self.topProductLayout.addWidget(self.lblTopProductTitle)
        self.tableTopProducts = QtWidgets.QTableWidget(parent=self.topProductPanel)
        self.tableTopProducts.setMinimumSize(QtCore.QSize(0, 120))
        self.tableTopProducts.setColumnCount(4)
        self.tableTopProducts.setObjectName("tableTopProducts")
        self.tableTopProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopProducts.setHorizontalHeaderItem(3, item)
        self.topProductLayout.addWidget(self.tableTopProducts)
        self.bottomLayout.addWidget(self.topProductPanel)
        self.topCustomerPanel = QtWidgets.QFrame(parent=ReportPage)
        self.topCustomerPanel.setObjectName("topCustomerPanel")
        self.topCustomerLayout = QtWidgets.QVBoxLayout(self.topCustomerPanel)
        self.topCustomerLayout.setContentsMargins(12, 10, 12, 10)
        self.topCustomerLayout.setSpacing(8)
        self.topCustomerLayout.setObjectName("topCustomerLayout")
        self.lblTopCustomerTitle = QtWidgets.QLabel(parent=self.topCustomerPanel)
        self.lblTopCustomerTitle.setObjectName("lblTopCustomerTitle")
        self.topCustomerLayout.addWidget(self.lblTopCustomerTitle)
        self.tableTopCustomers = QtWidgets.QTableWidget(parent=self.topCustomerPanel)
        self.tableTopCustomers.setMinimumSize(QtCore.QSize(0, 120))
        self.tableTopCustomers.setColumnCount(4)
        self.tableTopCustomers.setObjectName("tableTopCustomers")
        self.tableTopCustomers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopCustomers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopCustomers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopCustomers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopCustomers.setHorizontalHeaderItem(3, item)
        self.topCustomerLayout.addWidget(self.tableTopCustomers)
        self.bottomLayout.addWidget(self.topCustomerPanel)
        self.topDiscountPanel = QtWidgets.QFrame(parent=ReportPage)
        self.topDiscountPanel.setObjectName("topDiscountPanel")
        self.topDiscountLayout = QtWidgets.QVBoxLayout(self.topDiscountPanel)
        self.topDiscountLayout.setContentsMargins(12, 10, 12, 10)
        self.topDiscountLayout.setSpacing(8)
        self.topDiscountLayout.setObjectName("topDiscountLayout")
        self.lblTopDiscountTitle = QtWidgets.QLabel(parent=self.topDiscountPanel)
        self.lblTopDiscountTitle.setObjectName("lblTopDiscountTitle")
        self.topDiscountLayout.addWidget(self.lblTopDiscountTitle)
        self.tableTopDiscounts = QtWidgets.QTableWidget(parent=self.topDiscountPanel)
        self.tableTopDiscounts.setMinimumSize(QtCore.QSize(0, 120))
        self.tableTopDiscounts.setColumnCount(4)
        self.tableTopDiscounts.setObjectName("tableTopDiscounts")
        self.tableTopDiscounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopDiscounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopDiscounts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopDiscounts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopDiscounts.setHorizontalHeaderItem(3, item)
        self.topDiscountLayout.addWidget(self.tableTopDiscounts)
        self.bottomLayout.addWidget(self.topDiscountPanel)
        self.mainLayout.addLayout(self.bottomLayout)

        self.retranslateUi(ReportPage)
        QtCore.QMetaObject.connectSlotsByName(ReportPage)

    def retranslateUi(self, ReportPage):
        _translate = QtCore.QCoreApplication.translate
        ReportPage.setStyleSheet(_translate("ReportPage", "\n"
"QWidget#ReportPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#filterPanel,\n"
"QFrame#kpiCardRevenue,\n"
"QFrame#kpiCardProfit,\n"
"QFrame#kpiCardOrders,\n"
"QFrame#kpiCardAov,\n"
"QFrame#chartRevenuePanel,\n"
"QFrame#chartBrandPanel,\n"
"QFrame#topProductPanel,\n"
"QFrame#topCustomerPanel,\n"
"QFrame#topDiscountPanel {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame.chartBox {\n"
"    background-color: #f8fbff;\n"
"    border: 1px dashed #93c5fd;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.kpiValue {\n"
"    color: #2563eb;\n"
"    font-size: 23px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.kpiText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel.chartPlaceholder {\n"
"    color: #64748b;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QComboBox,\n"
"QDateEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QComboBox:focus,\n"
"QDateEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down,\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox::down-arrow,\n"
"QDateEdit::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px 10px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnViewDay,\n"
"QPushButton#btnViewMonth,\n"
"QPushButton#btnViewYear {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnRefreshReport,\n"
"QPushButton#btnExportCsv {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnExportExcel {\n"
"    background-color: #16a34a;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblFilterTitle.setText(_translate("ReportPage", "📈 Báo cáo kinh doanh"))
        self.lblFilterTitle.setProperty("class", _translate("ReportPage", "sectionTitle"))
        self.cboReportType.setItemText(0, _translate("ReportPage", "Tổng quan"))
        self.cboReportType.setItemText(1, _translate("ReportPage", "Doanh thu"))
        self.cboReportType.setItemText(2, _translate("ReportPage", "Sản phẩm"))
        self.cboReportType.setItemText(3, _translate("ReportPage", "Khách hàng"))
        self.cboReportType.setItemText(4, _translate("ReportPage", "Mã giảm giá"))
        self.cboReportType.setItemText(5, _translate("ReportPage", "Tồn kho"))
        self.dateFrom.setDisplayFormat(_translate("ReportPage", "dd/MM/yyyy"))
        self.dateTo.setDisplayFormat(_translate("ReportPage", "dd/MM/yyyy"))
        self.btnViewDay.setText(_translate("ReportPage", "📅 Ngày"))
        self.btnViewMonth.setText(_translate("ReportPage", "🗓 Tháng"))
        self.btnViewYear.setText(_translate("ReportPage", "📆 Năm"))
        self.btnRefreshReport.setText(_translate("ReportPage", "🔄 Mới"))
        self.btnExportCsv.setText(_translate("ReportPage", "CSV"))
        self.btnExportExcel.setText(_translate("ReportPage", "Excel"))
        self.lblRevenueValue.setText(_translate("ReportPage", "0 đ"))
        self.lblRevenueValue.setProperty("class", _translate("ReportPage", "kpiValue"))
        self.lblRevenueText.setText(_translate("ReportPage", "Doanh thu"))
        self.lblRevenueText.setProperty("class", _translate("ReportPage", "kpiText"))
        self.lblProfitValue.setText(_translate("ReportPage", "0 đ"))
        self.lblProfitValue.setProperty("class", _translate("ReportPage", "kpiValue"))
        self.lblProfitText.setText(_translate("ReportPage", "Lợi nhuận ước tính"))
        self.lblProfitText.setProperty("class", _translate("ReportPage", "kpiText"))
        self.lblOrderValue.setText(_translate("ReportPage", "0"))
        self.lblOrderValue.setProperty("class", _translate("ReportPage", "kpiValue"))
        self.lblOrderText.setText(_translate("ReportPage", "Số hóa đơn"))
        self.lblOrderText.setProperty("class", _translate("ReportPage", "kpiText"))
        self.lblAovValue.setText(_translate("ReportPage", "0 đ"))
        self.lblAovValue.setProperty("class", _translate("ReportPage", "kpiValue"))
        self.lblAovText.setText(_translate("ReportPage", "Trung bình / đơn"))
        self.lblAovText.setProperty("class", _translate("ReportPage", "kpiText"))
        self.lblRevenueChartTitle.setText(_translate("ReportPage", "📊 Doanh thu theo ngày"))
        self.lblRevenueChartTitle.setProperty("class", _translate("ReportPage", "sectionTitle"))
        self.chartRevenueFrame.setProperty("class", _translate("ReportPage", "chartBox"))
        self.lblRevenueChartPlaceholder.setText(_translate("ReportPage", "Biểu đồ doanh thu sẽ tự hiển thị tại đây"))
        self.lblRevenueChartPlaceholder.setProperty("class", _translate("ReportPage", "chartPlaceholder"))
        self.lblBrandChartTitle.setText(_translate("ReportPage", "🏷 Top hãng bán chạy"))
        self.lblBrandChartTitle.setProperty("class", _translate("ReportPage", "sectionTitle"))
        self.chartBrandFrame.setProperty("class", _translate("ReportPage", "chartBox"))
        self.lblBrandChartPlaceholder.setText(_translate("ReportPage", "Biểu đồ top hãng bán chạy sẽ tự hiển thị tại đây"))
        self.lblBrandChartPlaceholder.setProperty("class", _translate("ReportPage", "chartPlaceholder"))
        self.lblTopProductTitle.setText(_translate("ReportPage", "🏆 Top sản phẩm bán chạy"))
        self.lblTopProductTitle.setProperty("class", _translate("ReportPage", "sectionTitle"))
        item = self.tableTopProducts.horizontalHeaderItem(0)
        item.setText(_translate("ReportPage", "Top"))
        item = self.tableTopProducts.horizontalHeaderItem(1)
        item.setText(_translate("ReportPage", "Sản phẩm"))
        item = self.tableTopProducts.horizontalHeaderItem(2)
        item.setText(_translate("ReportPage", "Số lượng"))
        item = self.tableTopProducts.horizontalHeaderItem(3)
        item.setText(_translate("ReportPage", "Doanh thu"))
        self.lblTopCustomerTitle.setText(_translate("ReportPage", "👑 Top khách hàng"))
        self.lblTopCustomerTitle.setProperty("class", _translate("ReportPage", "sectionTitle"))
        item = self.tableTopCustomers.horizontalHeaderItem(0)
        item.setText(_translate("ReportPage", "Top"))
        item = self.tableTopCustomers.horizontalHeaderItem(1)
        item.setText(_translate("ReportPage", "Khách hàng"))
        item = self.tableTopCustomers.horizontalHeaderItem(2)
        item.setText(_translate("ReportPage", "Số đơn"))
        item = self.tableTopCustomers.horizontalHeaderItem(3)
        item.setText(_translate("ReportPage", "Tổng chi"))
        self.lblTopDiscountTitle.setText(_translate("ReportPage", "🎁 Mã giảm giá dùng nhiều"))
        self.lblTopDiscountTitle.setProperty("class", _translate("ReportPage", "sectionTitle"))
        item = self.tableTopDiscounts.horizontalHeaderItem(0)
        item.setText(_translate("ReportPage", "Top"))
        item = self.tableTopDiscounts.horizontalHeaderItem(1)
        item.setText(_translate("ReportPage", "Mã"))
        item = self.tableTopDiscounts.horizontalHeaderItem(2)
        item.setText(_translate("ReportPage", "Lượt dùng"))
        item = self.tableTopDiscounts.horizontalHeaderItem(3)
        item.setText(_translate("ReportPage", "Tổng giảm"))
