# Form implementation generated from reading ui file 'app/view/ui/sales_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SalesPage(object):
    def setupUi(self, SalesPage):
        SalesPage.setObjectName("SalesPage")
        SalesPage.resize(1050, 560)
        self.mainLayout = QtWidgets.QHBoxLayout(SalesPage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSpacing(10)
        self.leftLayout.setObjectName("leftLayout")
        self.customerPanel = QtWidgets.QFrame(parent=SalesPage)
        self.customerPanel.setMinimumSize(QtCore.QSize(390, 255))
        self.customerPanel.setMaximumSize(QtCore.QSize(460, 285))
        self.customerPanel.setObjectName("customerPanel")
        self.customerLayout = QtWidgets.QVBoxLayout(self.customerPanel)
        self.customerLayout.setContentsMargins(14, 12, 14, 12)
        self.customerLayout.setSpacing(8)
        self.customerLayout.setObjectName("customerLayout")
        self.lblCustomerTitle = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerTitle.setObjectName("lblCustomerTitle")
        self.customerLayout.addWidget(self.lblCustomerTitle)
        self.lblCustomerPhone = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerPhone.setObjectName("lblCustomerPhone")
        self.customerLayout.addWidget(self.lblCustomerPhone)
        self.phoneLayout = QtWidgets.QHBoxLayout()
        self.phoneLayout.setSpacing(10)
        self.phoneLayout.setObjectName("phoneLayout")
        self.txtCustomerPhone = QtWidgets.QLineEdit(parent=self.customerPanel)
        self.txtCustomerPhone.setMinimumSize(QtCore.QSize(0, 38))
        self.txtCustomerPhone.setObjectName("txtCustomerPhone")
        self.phoneLayout.addWidget(self.txtCustomerPhone)
        self.btnFindCustomer = QtWidgets.QPushButton(parent=self.customerPanel)
        self.btnFindCustomer.setMinimumSize(QtCore.QSize(92, 38))
        self.btnFindCustomer.setObjectName("btnFindCustomer")
        self.phoneLayout.addWidget(self.btnFindCustomer)
        self.customerLayout.addLayout(self.phoneLayout)
        self.lblCustomerName = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.customerLayout.addWidget(self.lblCustomerName)
        self.txtCustomerName = QtWidgets.QLineEdit(parent=self.customerPanel)
        self.txtCustomerName.setMinimumSize(QtCore.QSize(0, 38))
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.customerLayout.addWidget(self.txtCustomerName)
        self.customerExtraTitleLayout = QtWidgets.QHBoxLayout()
        self.customerExtraTitleLayout.setSpacing(10)
        self.customerExtraTitleLayout.setObjectName("customerExtraTitleLayout")
        self.lblCustomerEmail = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerEmail.setObjectName("lblCustomerEmail")
        self.customerExtraTitleLayout.addWidget(self.lblCustomerEmail)
        self.lblCustomerAddress = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerAddress.setObjectName("lblCustomerAddress")
        self.customerExtraTitleLayout.addWidget(self.lblCustomerAddress)
        self.customerLayout.addLayout(self.customerExtraTitleLayout)
        self.customerExtraLayout = QtWidgets.QHBoxLayout()
        self.customerExtraLayout.setSpacing(10)
        self.customerExtraLayout.setObjectName("customerExtraLayout")
        self.txtCustomerEmail = QtWidgets.QLineEdit(parent=self.customerPanel)
        self.txtCustomerEmail.setMinimumSize(QtCore.QSize(0, 38))
        self.txtCustomerEmail.setObjectName("txtCustomerEmail")
        self.customerExtraLayout.addWidget(self.txtCustomerEmail)
        self.txtCustomerAddress = QtWidgets.QLineEdit(parent=self.customerPanel)
        self.txtCustomerAddress.setMinimumSize(QtCore.QSize(0, 38))
        self.txtCustomerAddress.setObjectName("txtCustomerAddress")
        self.customerExtraLayout.addWidget(self.txtCustomerAddress)
        self.customerLayout.addLayout(self.customerExtraLayout)
        self.customerButtonLayout = QtWidgets.QHBoxLayout()
        self.customerButtonLayout.setSpacing(10)
        self.customerButtonLayout.setObjectName("customerButtonLayout")
        self.btnImportCustomer = QtWidgets.QPushButton(parent=self.customerPanel)
        self.btnImportCustomer.setMinimumSize(QtCore.QSize(0, 38))
        self.btnImportCustomer.setObjectName("btnImportCustomer")
        self.customerButtonLayout.addWidget(self.btnImportCustomer)
        self.btnNewCustomer = QtWidgets.QPushButton(parent=self.customerPanel)
        self.btnNewCustomer.setMinimumSize(QtCore.QSize(0, 38))
        self.btnNewCustomer.setObjectName("btnNewCustomer")
        self.customerButtonLayout.addWidget(self.btnNewCustomer)
        self.customerLayout.addLayout(self.customerButtonLayout)
        self.leftLayout.addWidget(self.customerPanel)
        self.productPanel = QtWidgets.QFrame(parent=SalesPage)
        self.productPanel.setMinimumSize(QtCore.QSize(390, 0))
        self.productPanel.setMaximumSize(QtCore.QSize(460, 16777215))
        self.productPanel.setObjectName("productPanel")
        self.productLayout = QtWidgets.QVBoxLayout(self.productPanel)
        self.productLayout.setContentsMargins(14, 12, 14, 12)
        self.productLayout.setSpacing(8)
        self.productLayout.setObjectName("productLayout")
        self.lblProductTitle = QtWidgets.QLabel(parent=self.productPanel)
        self.lblProductTitle.setObjectName("lblProductTitle")
        self.productLayout.addWidget(self.lblProductTitle)
        self.lblSearchImei = QtWidgets.QLabel(parent=self.productPanel)
        self.lblSearchImei.setObjectName("lblSearchImei")
        self.productLayout.addWidget(self.lblSearchImei)
        self.imeiLayout = QtWidgets.QHBoxLayout()
        self.imeiLayout.setSpacing(10)
        self.imeiLayout.setObjectName("imeiLayout")
        self.txtImeiSearch = QtWidgets.QLineEdit(parent=self.productPanel)
        self.txtImeiSearch.setMinimumSize(QtCore.QSize(0, 38))
        self.txtImeiSearch.setObjectName("txtImeiSearch")
        self.imeiLayout.addWidget(self.txtImeiSearch)
        self.btnFindImei = QtWidgets.QPushButton(parent=self.productPanel)
        self.btnFindImei.setMinimumSize(QtCore.QSize(92, 38))
        self.btnFindImei.setObjectName("btnFindImei")
        self.imeiLayout.addWidget(self.btnFindImei)
        self.btnScanImei = QtWidgets.QPushButton(parent=self.productPanel)
        self.btnScanImei.setMinimumSize(QtCore.QSize(115, 38))
        self.btnScanImei.setObjectName("btnScanImei")
        self.imeiLayout.addWidget(self.btnScanImei)
        self.productLayout.addLayout(self.imeiLayout)
        self.aiTitleLabel = QtWidgets.QLabel(parent=self.productPanel)
        self.aiTitleLabel.setObjectName("aiTitleLabel")
        self.productLayout.addWidget(self.aiTitleLabel)
        self.aiSuggestLayout = QtWidgets.QHBoxLayout()
        self.aiSuggestLayout.setSpacing(10)
        self.aiSuggestLayout.setObjectName("aiSuggestLayout")
        self.txtAiRequest = QtWidgets.QLineEdit(parent=self.productPanel)
        self.txtAiRequest.setMinimumSize(QtCore.QSize(0, 38))
        self.txtAiRequest.setObjectName("txtAiRequest")
        self.aiSuggestLayout.addWidget(self.txtAiRequest)
        self.btnAiSuggest = QtWidgets.QPushButton(parent=self.productPanel)
        self.btnAiSuggest.setMinimumSize(QtCore.QSize(105, 38))
        self.btnAiSuggest.setObjectName("btnAiSuggest")
        self.aiSuggestLayout.addWidget(self.btnAiSuggest)
        self.productLayout.addLayout(self.aiSuggestLayout)
        self.productNameTitleLayout = QtWidgets.QHBoxLayout()
        self.productNameTitleLayout.setSpacing(10)
        self.productNameTitleLayout.setObjectName("productNameTitleLayout")
        self.lblProductName = QtWidgets.QLabel(parent=self.productPanel)
        self.lblProductName.setObjectName("lblProductName")
        self.productNameTitleLayout.addWidget(self.lblProductName)
        self.lblSelectedImei = QtWidgets.QLabel(parent=self.productPanel)
        self.lblSelectedImei.setObjectName("lblSelectedImei")
        self.productNameTitleLayout.addWidget(self.lblSelectedImei)
        self.productLayout.addLayout(self.productNameTitleLayout)
        self.productNameLayout = QtWidgets.QHBoxLayout()
        self.productNameLayout.setSpacing(10)
        self.productNameLayout.setObjectName("productNameLayout")
        self.txtProductName = QtWidgets.QLineEdit(parent=self.productPanel)
        self.txtProductName.setReadOnly(True)
        self.txtProductName.setMinimumSize(QtCore.QSize(0, 38))
        self.txtProductName.setObjectName("txtProductName")
        self.productNameLayout.addWidget(self.txtProductName)
        self.txtSelectedImei = QtWidgets.QLineEdit(parent=self.productPanel)
        self.txtSelectedImei.setReadOnly(True)
        self.txtSelectedImei.setMinimumSize(QtCore.QSize(0, 38))
        self.txtSelectedImei.setObjectName("txtSelectedImei")
        self.productNameLayout.addWidget(self.txtSelectedImei)
        self.productLayout.addLayout(self.productNameLayout)
        self.variantTitleLayout = QtWidgets.QHBoxLayout()
        self.variantTitleLayout.setSpacing(10)
        self.variantTitleLayout.setObjectName("variantTitleLayout")
        self.lblBrand = QtWidgets.QLabel(parent=self.productPanel)
        self.lblBrand.setObjectName("lblBrand")
        self.variantTitleLayout.addWidget(self.lblBrand)
        self.lblVariant = QtWidgets.QLabel(parent=self.productPanel)
        self.lblVariant.setObjectName("lblVariant")
        self.variantTitleLayout.addWidget(self.lblVariant)
        self.productLayout.addLayout(self.variantTitleLayout)
        self.variantLayout = QtWidgets.QHBoxLayout()
        self.variantLayout.setSpacing(10)
        self.variantLayout.setObjectName("variantLayout")
        self.txtBrand = QtWidgets.QLineEdit(parent=self.productPanel)
        self.txtBrand.setReadOnly(True)
        self.txtBrand.setMinimumSize(QtCore.QSize(0, 38))
        self.txtBrand.setObjectName("txtBrand")
        self.variantLayout.addWidget(self.txtBrand)
        self.txtVariantInfo = QtWidgets.QLineEdit(parent=self.productPanel)
        self.txtVariantInfo.setReadOnly(True)
        self.txtVariantInfo.setMinimumSize(QtCore.QSize(0, 38))
        self.txtVariantInfo.setObjectName("txtVariantInfo")
        self.variantLayout.addWidget(self.txtVariantInfo)
        self.productLayout.addLayout(self.variantLayout)
        self.priceTitleLayout = QtWidgets.QHBoxLayout()
        self.priceTitleLayout.setSpacing(10)
        self.priceTitleLayout.setObjectName("priceTitleLayout")
        self.lblSalePrice = QtWidgets.QLabel(parent=self.productPanel)
        self.lblSalePrice.setObjectName("lblSalePrice")
        self.priceTitleLayout.addWidget(self.lblSalePrice)
        self.lblWarrantyMonth = QtWidgets.QLabel(parent=self.productPanel)
        self.lblWarrantyMonth.setObjectName("lblWarrantyMonth")
        self.priceTitleLayout.addWidget(self.lblWarrantyMonth)
        self.productLayout.addLayout(self.priceTitleLayout)
        self.priceLayout = QtWidgets.QHBoxLayout()
        self.priceLayout.setSpacing(10)
        self.priceLayout.setObjectName("priceLayout")
        self.spinSalePrice = QtWidgets.QDoubleSpinBox(parent=self.productPanel)
        self.spinSalePrice.setMinimumSize(QtCore.QSize(0, 38))
        self.spinSalePrice.setMaximum(999999999.0)
        self.spinSalePrice.setSingleStep(100000.0)
        self.spinSalePrice.setObjectName("spinSalePrice")
        self.priceLayout.addWidget(self.spinSalePrice)
        self.spinWarrantyMonth = QtWidgets.QSpinBox(parent=self.productPanel)
        self.spinWarrantyMonth.setMinimumSize(QtCore.QSize(0, 38))
        self.spinWarrantyMonth.setMinimum(0)
        self.spinWarrantyMonth.setMaximum(36)
        self.spinWarrantyMonth.setProperty("value", 12)
        self.spinWarrantyMonth.setObjectName("spinWarrantyMonth")
        self.priceLayout.addWidget(self.spinWarrantyMonth)
        self.productLayout.addLayout(self.priceLayout)
        self.btnAddToCart = QtWidgets.QPushButton(parent=self.productPanel)
        self.btnAddToCart.setMinimumSize(QtCore.QSize(0, 42))
        self.btnAddToCart.setObjectName("btnAddToCart")
        self.productLayout.addWidget(self.btnAddToCart)
        self.leftLayout.addWidget(self.productPanel)
        self.mainLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.cartPanel = QtWidgets.QFrame(parent=SalesPage)
        self.cartPanel.setMaximumSize(QtCore.QSize(16777215, 230))
        self.cartPanel.setObjectName("cartPanel")
        self.cartLayout = QtWidgets.QVBoxLayout(self.cartPanel)
        self.cartLayout.setContentsMargins(12, 10, 12, 10)
        self.cartLayout.setSpacing(8)
        self.cartLayout.setObjectName("cartLayout")
        self.cartTitleLayout = QtWidgets.QHBoxLayout()
        self.cartTitleLayout.setObjectName("cartTitleLayout")
        self.lblCartTitle = QtWidgets.QLabel(parent=self.cartPanel)
        self.lblCartTitle.setObjectName("lblCartTitle")
        self.cartTitleLayout.addWidget(self.lblCartTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.cartTitleLayout.addItem(spacerItem)
        self.btnRemoveCartItem = QtWidgets.QPushButton(parent=self.cartPanel)
        self.btnRemoveCartItem.setMaximumSize(QtCore.QSize(105, 34))
        self.btnRemoveCartItem.setObjectName("btnRemoveCartItem")
        self.cartTitleLayout.addWidget(self.btnRemoveCartItem)
        self.btnClearCart = QtWidgets.QPushButton(parent=self.cartPanel)
        self.btnClearCart.setMaximumSize(QtCore.QSize(95, 34))
        self.btnClearCart.setObjectName("btnClearCart")
        self.cartTitleLayout.addWidget(self.btnClearCart)
        self.cartLayout.addLayout(self.cartTitleLayout)
        self.tableCart = QtWidgets.QTableWidget(parent=self.cartPanel)
        self.tableCart.setMinimumSize(QtCore.QSize(0, 140))
        self.tableCart.setMaximumSize(QtCore.QSize(16777215, 145))
        self.tableCart.setColumnCount(8)
        self.tableCart.setObjectName("tableCart")
        self.tableCart.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCart.setHorizontalHeaderItem(7, item)
        self.cartLayout.addWidget(self.tableCart)
        self.rightLayout.addWidget(self.cartPanel)
        self.paymentPanel = QtWidgets.QFrame(parent=SalesPage)
        self.paymentPanel.setMinimumSize(QtCore.QSize(0, 335))
        self.paymentPanel.setObjectName("paymentPanel")
        self.paymentMainLayout = QtWidgets.QVBoxLayout(self.paymentPanel)
        self.paymentMainLayout.setContentsMargins(14, 12, 14, 12)
        self.paymentMainLayout.setSpacing(12)
        self.paymentMainLayout.setObjectName("paymentMainLayout")
        self.lblPaymentTitle = QtWidgets.QLabel(parent=self.paymentPanel)
        self.lblPaymentTitle.setObjectName("lblPaymentTitle")
        self.paymentMainLayout.addWidget(self.lblPaymentTitle)
        self.paymentTopLayout = QtWidgets.QHBoxLayout()
        self.paymentTopLayout.setSpacing(12)
        self.paymentTopLayout.setObjectName("paymentTopLayout")
        self.summaryBox = QtWidgets.QFrame(parent=self.paymentPanel)
        self.summaryBox.setObjectName("summaryBox")
        self.summaryLayout = QtWidgets.QVBoxLayout(self.summaryBox)
        self.summaryLayout.setContentsMargins(12, 10, 12, 10)
        self.summaryLayout.setSpacing(8)
        self.summaryLayout.setObjectName("summaryLayout")
        self.discountLayout = QtWidgets.QHBoxLayout()
        self.discountLayout.setSpacing(8)
        self.discountLayout.setObjectName("discountLayout")
        self.txtDiscountCode = QtWidgets.QLineEdit(parent=self.summaryBox)
        self.txtDiscountCode.setMinimumSize(QtCore.QSize(0, 38))
        self.txtDiscountCode.setObjectName("txtDiscountCode")
        self.discountLayout.addWidget(self.txtDiscountCode)
        self.btnApplyDiscount = QtWidgets.QPushButton(parent=self.summaryBox)
        self.btnApplyDiscount.setMinimumSize(QtCore.QSize(92, 38))
        self.btnApplyDiscount.setObjectName("btnApplyDiscount")
        self.discountLayout.addWidget(self.btnApplyDiscount)
        self.summaryLayout.addLayout(self.discountLayout)
        self.moneyGridLayout = QtWidgets.QGridLayout()
        self.moneyGridLayout.setHorizontalSpacing(14)
        self.moneyGridLayout.setVerticalSpacing(7)
        self.moneyGridLayout.setObjectName("moneyGridLayout")
        self.lblSubtotal = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblSubtotal.setObjectName("lblSubtotal")
        self.moneyGridLayout.addWidget(self.lblSubtotal, 0, 0, 1, 1)
        self.lblSubtotalValue = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblSubtotalValue.setObjectName("lblSubtotalValue")
        self.moneyGridLayout.addWidget(self.lblSubtotalValue, 0, 1, 1, 1)
        self.lblDiscount = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblDiscount.setObjectName("lblDiscount")
        self.moneyGridLayout.addWidget(self.lblDiscount, 1, 0, 1, 1)
        self.lblDiscountValue = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblDiscountValue.setObjectName("lblDiscountValue")
        self.moneyGridLayout.addWidget(self.lblDiscountValue, 1, 1, 1, 1)
        self.lblPaymentMethod = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblPaymentMethod.setObjectName("lblPaymentMethod")
        self.moneyGridLayout.addWidget(self.lblPaymentMethod, 2, 0, 1, 1)
        self.paymentMethodLayout = QtWidgets.QHBoxLayout()
        self.paymentMethodLayout.setSpacing(12)
        self.paymentMethodLayout.setObjectName("paymentMethodLayout")
        self.radioCash = QtWidgets.QRadioButton(parent=self.summaryBox)
        self.radioCash.setChecked(True)
        self.radioCash.setObjectName("radioCash")
        self.paymentMethodLayout.addWidget(self.radioCash)
        self.radioQR = QtWidgets.QRadioButton(parent=self.summaryBox)
        self.radioQR.setObjectName("radioQR")
        self.paymentMethodLayout.addWidget(self.radioQR)
        self.moneyGridLayout.addLayout(self.paymentMethodLayout, 2, 1, 1, 1)
        self.lblPaid = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblPaid.setObjectName("lblPaid")
        self.moneyGridLayout.addWidget(self.lblPaid, 3, 0, 1, 1)
        self.spinCustomerPaid = QtWidgets.QDoubleSpinBox(parent=self.summaryBox)
        self.spinCustomerPaid.setMinimumSize(QtCore.QSize(0, 38))
        self.spinCustomerPaid.setMaximum(999999999.0)
        self.spinCustomerPaid.setSingleStep(100000.0)
        self.spinCustomerPaid.setObjectName("spinCustomerPaid")
        self.moneyGridLayout.addWidget(self.spinCustomerPaid, 3, 1, 1, 1)
        self.lblChange = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblChange.setObjectName("lblChange")
        self.moneyGridLayout.addWidget(self.lblChange, 4, 0, 1, 1)
        self.lblChangeValue = QtWidgets.QLabel(parent=self.summaryBox)
        self.lblChangeValue.setObjectName("lblChangeValue")
        self.moneyGridLayout.addWidget(self.lblChangeValue, 4, 1, 1, 1)
        self.summaryLayout.addLayout(self.moneyGridLayout)
        self.paymentTopLayout.addWidget(self.summaryBox)
        self.totalBox = QtWidgets.QFrame(parent=self.paymentPanel)
        self.totalBox.setMinimumSize(QtCore.QSize(230, 0))
        self.totalBox.setMaximumSize(QtCore.QSize(280, 16777215))
        self.totalBox.setObjectName("totalBox")
        self.totalBoxLayout = QtWidgets.QVBoxLayout(self.totalBox)
        self.totalBoxLayout.setContentsMargins(14, 14, 14, 14)
        self.totalBoxLayout.setSpacing(10)
        self.totalBoxLayout.setObjectName("totalBoxLayout")
        self.lblTotalText = QtWidgets.QLabel(parent=self.totalBox)
        self.lblTotalText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTotalText.setObjectName("lblTotalText")
        self.totalBoxLayout.addWidget(self.lblTotalText)
        self.lblTotalValue = QtWidgets.QLabel(parent=self.totalBox)
        self.lblTotalValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTotalValue.setObjectName("lblTotalValue")
        self.totalBoxLayout.addWidget(self.lblTotalValue)
        self.btnShowQr = QtWidgets.QPushButton(parent=self.totalBox)
        self.btnShowQr.setMinimumSize(QtCore.QSize(0, 40))
        self.btnShowQr.setObjectName("btnShowQr")
        self.totalBoxLayout.addWidget(self.btnShowQr)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.totalBoxLayout.addItem(spacerItem1)
        self.paymentTopLayout.addWidget(self.totalBox)
        self.paymentMainLayout.addLayout(self.paymentTopLayout)
        self.finalButtonLayout = QtWidgets.QHBoxLayout()
        self.finalButtonLayout.setSpacing(10)
        self.finalButtonLayout.setObjectName("finalButtonLayout")
        self.btnConfirmPayment = QtWidgets.QPushButton(parent=self.paymentPanel)
        self.btnConfirmPayment.setMinimumSize(QtCore.QSize(0, 48))
        self.btnConfirmPayment.setObjectName("btnConfirmPayment")
        self.finalButtonLayout.addWidget(self.btnConfirmPayment)
        self.btnExportInvoice = QtWidgets.QPushButton(parent=self.paymentPanel)
        self.btnExportInvoice.setMinimumSize(QtCore.QSize(150, 48))
        self.btnExportInvoice.setObjectName("btnExportInvoice")
        self.finalButtonLayout.addWidget(self.btnExportInvoice)
        self.paymentMainLayout.addLayout(self.finalButtonLayout)
        self.lblQrImage = QtWidgets.QLabel(parent=self.paymentPanel)
        self.lblQrImage.setVisible(False)
        self.lblQrImage.setMaximumSize(QtCore.QSize(1, 1))
        self.lblQrImage.setText("")
        self.lblQrImage.setObjectName("lblQrImage")
        self.paymentMainLayout.addWidget(self.lblQrImage)
        self.rightLayout.addWidget(self.paymentPanel)
        self.mainLayout.addLayout(self.rightLayout)

        self.retranslateUi(SalesPage)
        QtCore.QMetaObject.connectSlotsByName(SalesPage)

    def retranslateUi(self, SalesPage):
        _translate = QtCore.QCoreApplication.translate
        SalesPage.setStyleSheet(_translate("SalesPage", "\n"
"QWidget#SalesPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"QFrame#customerPanel,\n"
"QFrame#productPanel,\n"
"QFrame#cartPanel,\n"
"QFrame#paymentPanel,\n"
"QFrame#summaryBox {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame#totalBox {\n"
"    background-color: #eff6ff;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QComboBox,\n"
"QDoubleSpinBox,\n"
"QSpinBox,\n"
"QTextEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QComboBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QSpinBox:focus,\n"
"QTextEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnFindCustomer,\n"
"QPushButton#btnImportCustomer,\n"
"QPushButton#btnFindImei,\n"
"QPushButton#btnScanImei,\n"
"QPushButton#btnAiSuggest,\n"
"QPushButton#btnAddToCart,\n"
"QPushButton#btnExportInvoice {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnNewCustomer,\n"
"QPushButton#btnClearCart {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QPushButton#btnRemoveCartItem {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnConfirmPayment {\n"
"    background-color: #16a34a;\n"
"    color: white;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton#btnApplyDiscount,\n"
"QPushButton#btnShowQr {\n"
"    background-color: #7c3aed;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #334155;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#lblTotalValue {\n"
"    color: #dc2626;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#lblSubtotalValue,\n"
"QLabel#lblDiscountValue,\n"
"QLabel#lblChangeValue {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#lblSubtotalValue {\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QLabel#lblDiscountValue {\n"
"    color: #7c3aed;\n"
"}\n"
"\n"
"QLabel#lblChangeValue {\n"
"    color: #16a34a;\n"
"}\n"
"\n"
"QLabel#lblQrImage {\n"
"    background-color: transparent;\n"
"}\n"
"   "))
        self.lblCustomerTitle.setText(_translate("SalesPage", "👤 Thông tin khách hàng"))
        self.lblCustomerTitle.setProperty("class", _translate("SalesPage", "sectionTitle"))
        self.lblCustomerPhone.setText(_translate("SalesPage", "Số điện thoại"))
        self.lblCustomerPhone.setProperty("class", _translate("SalesPage", "formLabel"))
        self.txtCustomerPhone.setPlaceholderText(_translate("SalesPage", "Nhập SĐT để tìm khách cũ"))
        self.btnFindCustomer.setText(_translate("SalesPage", "🔍 Tìm"))
        self.lblCustomerName.setText(_translate("SalesPage", "Họ tên"))
        self.lblCustomerName.setProperty("class", _translate("SalesPage", "formLabel"))
        self.txtCustomerName.setPlaceholderText(_translate("SalesPage", "Nguyễn Văn A"))
        self.lblCustomerEmail.setText(_translate("SalesPage", "Email"))
        self.lblCustomerEmail.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblCustomerAddress.setText(_translate("SalesPage", "Địa chỉ"))
        self.lblCustomerAddress.setProperty("class", _translate("SalesPage", "formLabel"))
        self.txtCustomerEmail.setPlaceholderText(_translate("SalesPage", "email@gmail.com"))
        self.txtCustomerAddress.setPlaceholderText(_translate("SalesPage", "Địa chỉ"))
        self.btnImportCustomer.setText(_translate("SalesPage", "💾 Lưu / Import khách"))
        self.btnNewCustomer.setText(_translate("SalesPage", "🧹 Khách mới"))
        self.lblProductTitle.setText(_translate("SalesPage", "📱 Bán hàng theo IMEI"))
        self.lblProductTitle.setProperty("class", _translate("SalesPage", "sectionTitle"))
        self.lblSearchImei.setText(_translate("SalesPage", "Quét / nhập IMEI"))
        self.lblSearchImei.setProperty("class", _translate("SalesPage", "formLabel"))
        self.txtImeiSearch.setPlaceholderText(_translate("SalesPage", "Nhập IMEI để tìm máy còn hàng"))
        self.btnFindImei.setText(_translate("SalesPage", "🔍 Tìm"))
        self.btnScanImei.setText(_translate("SalesPage", "📷 Quét IMEI"))
        self.aiTitleLabel.setText(_translate("SalesPage", "🤖 AI tư vấn máy"))
        self.aiTitleLabel.setProperty("class", _translate("SalesPage", "formLabel"))
        self.txtAiRequest.setPlaceholderText(_translate("SalesPage", "VD: khách cần iPhone dưới 10 triệu, pin tốt, 128GB"))
        self.btnAiSuggest.setText(_translate("SalesPage", "🤖 Gợi ý"))
        self.lblProductName.setText(_translate("SalesPage", "Sản phẩm"))
        self.lblProductName.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblSelectedImei.setText(_translate("SalesPage", "IMEI"))
        self.lblSelectedImei.setProperty("class", _translate("SalesPage", "formLabel"))
        self.txtProductName.setPlaceholderText(_translate("SalesPage", "Tự hiện sau khi tìm IMEI"))
        self.lblBrand.setText(_translate("SalesPage", "Hãng"))
        self.lblBrand.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblVariant.setText(_translate("SalesPage", "Dung lượng / Màu"))
        self.lblVariant.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblSalePrice.setText(_translate("SalesPage", "Giá bán"))
        self.lblSalePrice.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblWarrantyMonth.setText(_translate("SalesPage", "Bảo hành"))
        self.lblWarrantyMonth.setProperty("class", _translate("SalesPage", "formLabel"))
        self.spinSalePrice.setSuffix(_translate("SalesPage", " đ"))
        self.spinWarrantyMonth.setSuffix(_translate("SalesPage", " tháng"))
        self.btnAddToCart.setText(_translate("SalesPage", "➕ Thêm IMEI vào giỏ hàng"))
        self.lblCartTitle.setText(_translate("SalesPage", "🛒 Giỏ hàng / Hóa đơn tạm"))
        self.lblCartTitle.setProperty("class", _translate("SalesPage", "sectionTitle"))
        self.btnRemoveCartItem.setText(_translate("SalesPage", "🗑 Xóa dòng"))
        self.btnClearCart.setText(_translate("SalesPage", "🧹 Xóa giỏ"))
        item = self.tableCart.horizontalHeaderItem(0)
        item.setText(_translate("SalesPage", "ID IMEI"))
        item = self.tableCart.horizontalHeaderItem(1)
        item.setText(_translate("SalesPage", "IMEI"))
        item = self.tableCart.horizontalHeaderItem(2)
        item.setText(_translate("SalesPage", "Sản phẩm"))
        item = self.tableCart.horizontalHeaderItem(3)
        item.setText(_translate("SalesPage", "Dung lượng"))
        item = self.tableCart.horizontalHeaderItem(4)
        item.setText(_translate("SalesPage", "Màu"))
        item = self.tableCart.horizontalHeaderItem(5)
        item.setText(_translate("SalesPage", "Giá bán"))
        item = self.tableCart.horizontalHeaderItem(6)
        item.setText(_translate("SalesPage", "Bảo hành"))
        item = self.tableCart.horizontalHeaderItem(7)
        item.setText(_translate("SalesPage", "Thành tiền"))
        self.lblPaymentTitle.setText(_translate("SalesPage", "💳 Thanh toán"))
        self.lblPaymentTitle.setProperty("class", _translate("SalesPage", "sectionTitle"))
        self.txtDiscountCode.setPlaceholderText(_translate("SalesPage", "Mã giảm giá"))
        self.btnApplyDiscount.setText(_translate("SalesPage", "🎁 Áp mã"))
        self.lblSubtotal.setText(_translate("SalesPage", "Tạm tính"))
        self.lblSubtotal.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblSubtotalValue.setText(_translate("SalesPage", "0 đ"))
        self.lblDiscount.setText(_translate("SalesPage", "Giảm giá"))
        self.lblDiscount.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblDiscountValue.setText(_translate("SalesPage", "0 đ"))
        self.lblPaymentMethod.setText(_translate("SalesPage", "Phương thức"))
        self.lblPaymentMethod.setProperty("class", _translate("SalesPage", "formLabel"))
        self.radioCash.setText(_translate("SalesPage", "💵 Tiền mặt"))
        self.radioQR.setText(_translate("SalesPage", "🏦 QR chuyển khoản"))
        self.lblPaid.setText(_translate("SalesPage", "Khách đưa"))
        self.lblPaid.setProperty("class", _translate("SalesPage", "formLabel"))
        self.spinCustomerPaid.setSuffix(_translate("SalesPage", " đ"))
        self.lblChange.setText(_translate("SalesPage", "Tiền trả lại"))
        self.lblChange.setProperty("class", _translate("SalesPage", "formLabel"))
        self.lblChangeValue.setText(_translate("SalesPage", "0 đ"))
        self.lblTotalText.setText(_translate("SalesPage", "Tổng thanh toán"))
        self.lblTotalText.setStyleSheet(_translate("SalesPage", "color: #1e3a8a; font-size: 16px; font-weight: bold;"))
        self.lblTotalValue.setText(_translate("SalesPage", "0 đ"))
        self.btnShowQr.setText(_translate("SalesPage", "🏦 Hiện QR thanh toán"))
        self.btnConfirmPayment.setText(_translate("SalesPage", "✅ Xác nhận đã nhận tiền / thanh toán"))
        self.btnExportInvoice.setText(_translate("SalesPage", "🧾 Xuất hóa đơn"))
