# Form implementation generated from reading ui file 'app/view/ui/warranty_page.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WarrantyPage(object):
    def setupUi(self, WarrantyPage):
        WarrantyPage.setObjectName("WarrantyPage")
        WarrantyPage.resize(1050, 560)
        self.mainLayout = QtWidgets.QVBoxLayout(WarrantyPage)
        self.mainLayout.setContentsMargins(14, 10, 14, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setSpacing(10)
        self.summaryLayout.setObjectName("summaryLayout")
        self.summaryCard1 = QtWidgets.QFrame(parent=WarrantyPage)
        self.summaryCard1.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard1.setObjectName("summaryCard1")
        self.summaryCard1Layout = QtWidgets.QVBoxLayout(self.summaryCard1)
        self.summaryCard1Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard1Layout.setObjectName("summaryCard1Layout")
        self.lblTotalWarranty = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalWarranty.setObjectName("lblTotalWarranty")
        self.summaryCard1Layout.addWidget(self.lblTotalWarranty)
        self.lblTotalWarrantyText = QtWidgets.QLabel(parent=self.summaryCard1)
        self.lblTotalWarrantyText.setObjectName("lblTotalWarrantyText")
        self.summaryCard1Layout.addWidget(self.lblTotalWarrantyText)
        self.summaryLayout.addWidget(self.summaryCard1)
        self.summaryCard2 = QtWidgets.QFrame(parent=WarrantyPage)
        self.summaryCard2.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard2.setObjectName("summaryCard2")
        self.summaryCard2Layout = QtWidgets.QVBoxLayout(self.summaryCard2)
        self.summaryCard2Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard2Layout.setObjectName("summaryCard2Layout")
        self.lblPendingWarranty = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblPendingWarranty.setObjectName("lblPendingWarranty")
        self.summaryCard2Layout.addWidget(self.lblPendingWarranty)
        self.lblPendingWarrantyText = QtWidgets.QLabel(parent=self.summaryCard2)
        self.lblPendingWarrantyText.setObjectName("lblPendingWarrantyText")
        self.summaryCard2Layout.addWidget(self.lblPendingWarrantyText)
        self.summaryLayout.addWidget(self.summaryCard2)
        self.summaryCard3 = QtWidgets.QFrame(parent=WarrantyPage)
        self.summaryCard3.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard3.setObjectName("summaryCard3")
        self.summaryCard3Layout = QtWidgets.QVBoxLayout(self.summaryCard3)
        self.summaryCard3Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard3Layout.setObjectName("summaryCard3Layout")
        self.lblDoneWarranty = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblDoneWarranty.setObjectName("lblDoneWarranty")
        self.summaryCard3Layout.addWidget(self.lblDoneWarranty)
        self.lblDoneWarrantyText = QtWidgets.QLabel(parent=self.summaryCard3)
        self.lblDoneWarrantyText.setObjectName("lblDoneWarrantyText")
        self.summaryCard3Layout.addWidget(self.lblDoneWarrantyText)
        self.summaryLayout.addWidget(self.summaryCard3)
        self.summaryCard4 = QtWidgets.QFrame(parent=WarrantyPage)
        self.summaryCard4.setMaximumSize(QtCore.QSize(16777215, 76))
        self.summaryCard4.setObjectName("summaryCard4")
        self.summaryCard4Layout = QtWidgets.QVBoxLayout(self.summaryCard4)
        self.summaryCard4Layout.setContentsMargins(12, 8, 12, 8)
        self.summaryCard4Layout.setObjectName("summaryCard4Layout")
        self.lblExpiredWarranty = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblExpiredWarranty.setObjectName("lblExpiredWarranty")
        self.summaryCard4Layout.addWidget(self.lblExpiredWarranty)
        self.lblExpiredWarrantyText = QtWidgets.QLabel(parent=self.summaryCard4)
        self.lblExpiredWarrantyText.setObjectName("lblExpiredWarrantyText")
        self.summaryCard4Layout.addWidget(self.lblExpiredWarrantyText)
        self.summaryLayout.addWidget(self.summaryCard4)
        self.mainLayout.addLayout(self.summaryLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.contentLayout.setObjectName("contentLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSpacing(10)
        self.leftLayout.setObjectName("leftLayout")
        self.searchPanel = QtWidgets.QFrame(parent=WarrantyPage)
        self.searchPanel.setMaximumSize(QtCore.QSize(430, 130))
        self.searchPanel.setMinimumSize(QtCore.QSize(380, 125))
        self.searchPanel.setObjectName("searchPanel")
        self.searchLayout = QtWidgets.QVBoxLayout(self.searchPanel)
        self.searchLayout.setContentsMargins(14, 12, 14, 12)
        self.searchLayout.setSpacing(8)
        self.searchLayout.setObjectName("searchLayout")
        self.lblSearchTitle = QtWidgets.QLabel(parent=self.searchPanel)
        self.lblSearchTitle.setObjectName("lblSearchTitle")
        self.searchLayout.addWidget(self.lblSearchTitle)
        self.imeiSearchLayout = QtWidgets.QHBoxLayout()
        self.imeiSearchLayout.setSpacing(8)
        self.imeiSearchLayout.setObjectName("imeiSearchLayout")
        self.txtSearchImei = QtWidgets.QLineEdit(parent=self.searchPanel)
        self.txtSearchImei.setMinimumSize(QtCore.QSize(0, 40))
        self.txtSearchImei.setObjectName("txtSearchImei")
        self.imeiSearchLayout.addWidget(self.txtSearchImei)
        self.btnSearchImei = QtWidgets.QPushButton(parent=self.searchPanel)
        self.btnSearchImei.setMinimumSize(QtCore.QSize(92, 40))
        self.btnSearchImei.setObjectName("btnSearchImei")
        self.imeiSearchLayout.addWidget(self.btnSearchImei)
        self.searchLayout.addLayout(self.imeiSearchLayout)
        self.leftLayout.addWidget(self.searchPanel)
        self.devicePanel = QtWidgets.QFrame(parent=WarrantyPage)
        self.devicePanel.setMaximumSize(QtCore.QSize(430, 210))
        self.devicePanel.setMinimumSize(QtCore.QSize(380, 200))
        self.devicePanel.setObjectName("devicePanel")
        self.deviceLayout = QtWidgets.QVBoxLayout(self.devicePanel)
        self.deviceLayout.setContentsMargins(14, 12, 14, 12)
        self.deviceLayout.setSpacing(8)
        self.deviceLayout.setObjectName("deviceLayout")
        self.lblDeviceTitle = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblDeviceTitle.setObjectName("lblDeviceTitle")
        self.deviceLayout.addWidget(self.lblDeviceTitle)
        self.deviceInfoLayout = QtWidgets.QGridLayout()
        self.deviceInfoLayout.setHorizontalSpacing(10)
        self.deviceInfoLayout.setVerticalSpacing(7)
        self.deviceInfoLayout.setObjectName("deviceInfoLayout")
        self.lblImeiText = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblImeiText.setObjectName("lblImeiText")
        self.deviceInfoLayout.addWidget(self.lblImeiText, 0, 0, 1, 1)
        self.lblImeiValue = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblImeiValue.setObjectName("lblImeiValue")
        self.deviceInfoLayout.addWidget(self.lblImeiValue, 0, 1, 1, 1)
        self.lblProductText = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblProductText.setObjectName("lblProductText")
        self.deviceInfoLayout.addWidget(self.lblProductText, 1, 0, 1, 1)
        self.lblProductValue = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblProductValue.setObjectName("lblProductValue")
        self.deviceInfoLayout.addWidget(self.lblProductValue, 1, 1, 1, 1)
        self.lblVariantText = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblVariantText.setObjectName("lblVariantText")
        self.deviceInfoLayout.addWidget(self.lblVariantText, 2, 0, 1, 1)
        self.lblVariantValue = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblVariantValue.setObjectName("lblVariantValue")
        self.deviceInfoLayout.addWidget(self.lblVariantValue, 2, 1, 1, 1)
        self.lblSoldDateText = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblSoldDateText.setObjectName("lblSoldDateText")
        self.deviceInfoLayout.addWidget(self.lblSoldDateText, 3, 0, 1, 1)
        self.lblSoldDateValue = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblSoldDateValue.setObjectName("lblSoldDateValue")
        self.deviceInfoLayout.addWidget(self.lblSoldDateValue, 3, 1, 1, 1)
        self.lblWarrantyEndText = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblWarrantyEndText.setObjectName("lblWarrantyEndText")
        self.deviceInfoLayout.addWidget(self.lblWarrantyEndText, 4, 0, 1, 1)
        self.lblWarrantyEndValue = QtWidgets.QLabel(parent=self.devicePanel)
        self.lblWarrantyEndValue.setObjectName("lblWarrantyEndValue")
        self.deviceInfoLayout.addWidget(self.lblWarrantyEndValue, 4, 1, 1, 1)
        self.deviceLayout.addLayout(self.deviceInfoLayout)
        self.leftLayout.addWidget(self.devicePanel)
        self.customerPanel = QtWidgets.QFrame(parent=WarrantyPage)
        self.customerPanel.setMaximumSize(QtCore.QSize(430, 170))
        self.customerPanel.setMinimumSize(QtCore.QSize(380, 160))
        self.customerPanel.setObjectName("customerPanel")
        self.customerLayout = QtWidgets.QVBoxLayout(self.customerPanel)
        self.customerLayout.setContentsMargins(14, 12, 14, 12)
        self.customerLayout.setSpacing(8)
        self.customerLayout.setObjectName("customerLayout")
        self.lblCustomerTitle = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerTitle.setObjectName("lblCustomerTitle")
        self.customerLayout.addWidget(self.lblCustomerTitle)
        self.customerInfoLayout = QtWidgets.QGridLayout()
        self.customerInfoLayout.setHorizontalSpacing(10)
        self.customerInfoLayout.setVerticalSpacing(7)
        self.customerInfoLayout.setObjectName("customerInfoLayout")
        self.lblCustomerNameText = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerNameText.setObjectName("lblCustomerNameText")
        self.customerInfoLayout.addWidget(self.lblCustomerNameText, 0, 0, 1, 1)
        self.lblCustomerNameValue = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblCustomerNameValue.setObjectName("lblCustomerNameValue")
        self.customerInfoLayout.addWidget(self.lblCustomerNameValue, 0, 1, 1, 1)
        self.lblPhoneText = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblPhoneText.setObjectName("lblPhoneText")
        self.customerInfoLayout.addWidget(self.lblPhoneText, 1, 0, 1, 1)
        self.lblPhoneValue = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblPhoneValue.setObjectName("lblPhoneValue")
        self.customerInfoLayout.addWidget(self.lblPhoneValue, 1, 1, 1, 1)
        self.lblInvoiceText = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblInvoiceText.setObjectName("lblInvoiceText")
        self.customerInfoLayout.addWidget(self.lblInvoiceText, 2, 0, 1, 1)
        self.lblInvoiceValue = QtWidgets.QLabel(parent=self.customerPanel)
        self.lblInvoiceValue.setObjectName("lblInvoiceValue")
        self.customerInfoLayout.addWidget(self.lblInvoiceValue, 2, 1, 1, 1)
        self.customerLayout.addLayout(self.customerInfoLayout)
        self.leftLayout.addWidget(self.customerPanel)
        self.contentLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setSpacing(10)
        self.rightLayout.setObjectName("rightLayout")
        self.topRightLayout = QtWidgets.QHBoxLayout()
        self.topRightLayout.setSpacing(10)
        self.topRightLayout.setObjectName("topRightLayout")
        self.statusBox = QtWidgets.QFrame(parent=WarrantyPage)
        self.statusBox.setMaximumSize(QtCore.QSize(260, 135))
        self.statusBox.setObjectName("statusBox")
        self.statusLayout = QtWidgets.QVBoxLayout(self.statusBox)
        self.statusLayout.setContentsMargins(14, 12, 14, 12)
        self.statusLayout.setSpacing(8)
        self.statusLayout.setObjectName("statusLayout")
        self.lblWarrantyStatusText = QtWidgets.QLabel(parent=self.statusBox)
        self.lblWarrantyStatusText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblWarrantyStatusText.setObjectName("lblWarrantyStatusText")
        self.statusLayout.addWidget(self.lblWarrantyStatusText)
        self.lblWarrantyStatusValue = QtWidgets.QLabel(parent=self.statusBox)
        self.lblWarrantyStatusValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblWarrantyStatusValue.setObjectName("lblWarrantyStatusValue")
        self.statusLayout.addWidget(self.lblWarrantyStatusValue)
        self.lblWarrantyRemainValue = QtWidgets.QLabel(parent=self.statusBox)
        self.lblWarrantyRemainValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblWarrantyRemainValue.setObjectName("lblWarrantyRemainValue")
        self.statusLayout.addWidget(self.lblWarrantyRemainValue)
        self.topRightLayout.addWidget(self.statusBox)
        self.formPanel = QtWidgets.QFrame(parent=WarrantyPage)
        self.formPanel.setMinimumSize(QtCore.QSize(0, 135))
        self.formPanel.setObjectName("formPanel")
        self.quickFormLayout = QtWidgets.QVBoxLayout(self.formPanel)
        self.quickFormLayout.setContentsMargins(14, 12, 14, 12)
        self.quickFormLayout.setSpacing(8)
        self.quickFormLayout.setObjectName("quickFormLayout")
        self.lblQuickFormTitle = QtWidgets.QLabel(parent=self.formPanel)
        self.lblQuickFormTitle.setObjectName("lblQuickFormTitle")
        self.quickFormLayout.addWidget(self.lblQuickFormTitle)
        self.statusFormLayout = QtWidgets.QHBoxLayout()
        self.statusFormLayout.setSpacing(8)
        self.statusFormLayout.setObjectName("statusFormLayout")
        self.cboWarrantyStatus = QtWidgets.QComboBox(parent=self.formPanel)
        self.cboWarrantyStatus.setMinimumSize(QtCore.QSize(155, 38))
        self.cboWarrantyStatus.setObjectName("cboWarrantyStatus")
        self.cboWarrantyStatus.addItem("")
        self.cboWarrantyStatus.addItem("")
        self.cboWarrantyStatus.addItem("")
        self.cboWarrantyStatus.addItem("")
        self.cboWarrantyStatus.addItem("")
        self.cboWarrantyStatus.addItem("")
        self.statusFormLayout.addWidget(self.cboWarrantyStatus)
        self.dateReceive = QtWidgets.QDateEdit(parent=self.formPanel)
        self.dateReceive.setMinimumSize(QtCore.QSize(135, 38))
        self.dateReceive.setCalendarPopup(True)
        self.dateReceive.setObjectName("dateReceive")
        self.statusFormLayout.addWidget(self.dateReceive)
        self.dateReturn = QtWidgets.QDateEdit(parent=self.formPanel)
        self.dateReturn.setMinimumSize(QtCore.QSize(135, 38))
        self.dateReturn.setCalendarPopup(True)
        self.dateReturn.setObjectName("dateReturn")
        self.statusFormLayout.addWidget(self.dateReturn)
        self.quickFormLayout.addLayout(self.statusFormLayout)
        self.quickButtonLayout = QtWidgets.QHBoxLayout()
        self.quickButtonLayout.setSpacing(8)
        self.quickButtonLayout.setObjectName("quickButtonLayout")
        self.btnCreateWarranty = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnCreateWarranty.setMinimumSize(QtCore.QSize(0, 38))
        self.btnCreateWarranty.setObjectName("btnCreateWarranty")
        self.quickButtonLayout.addWidget(self.btnCreateWarranty)
        self.btnUpdateWarranty = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnUpdateWarranty.setMinimumSize(QtCore.QSize(0, 38))
        self.btnUpdateWarranty.setObjectName("btnUpdateWarranty")
        self.quickButtonLayout.addWidget(self.btnUpdateWarranty)
        self.btnReturnDevice = QtWidgets.QPushButton(parent=self.formPanel)
        self.btnReturnDevice.setMinimumSize(QtCore.QSize(0, 38))
        self.btnReturnDevice.setObjectName("btnReturnDevice")
        self.quickButtonLayout.addWidget(self.btnReturnDevice)
        self.quickFormLayout.addLayout(self.quickButtonLayout)
        self.topRightLayout.addWidget(self.formPanel)
        self.rightLayout.addLayout(self.topRightLayout)
        self.formPanel1 = QtWidgets.QFrame(parent=WarrantyPage)
        self.formPanel1.setObjectName("formPanel1")
        self.formLayout = QtWidgets.QVBoxLayout(self.formPanel1)
        self.formLayout.setContentsMargins(14, 12, 14, 12)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.formTitleLayout = QtWidgets.QHBoxLayout()
        self.formTitleLayout.setObjectName("formTitleLayout")
        self.lblFormTitle = QtWidgets.QLabel(parent=self.formPanel1)
        self.lblFormTitle.setObjectName("lblFormTitle")
        self.formTitleLayout.addWidget(self.lblFormTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.formTitleLayout.addItem(spacerItem)
        self.btnClearForm = QtWidgets.QPushButton(parent=self.formPanel1)
        self.btnClearForm.setMinimumSize(QtCore.QSize(98, 34))
        self.btnClearForm.setObjectName("btnClearForm")
        self.formTitleLayout.addWidget(self.btnClearForm)
        self.formLayout.addLayout(self.formTitleLayout)
        self.issueTitleLayout = QtWidgets.QHBoxLayout()
        self.issueTitleLayout.setSpacing(10)
        self.issueTitleLayout.setObjectName("issueTitleLayout")
        self.lblIssueTitle = QtWidgets.QLabel(parent=self.formPanel1)
        self.lblIssueTitle.setObjectName("lblIssueTitle")
        self.issueTitleLayout.addWidget(self.lblIssueTitle)
        self.lblConditionTitle = QtWidgets.QLabel(parent=self.formPanel1)
        self.lblConditionTitle.setObjectName("lblConditionTitle")
        self.issueTitleLayout.addWidget(self.lblConditionTitle)
        self.formLayout.addLayout(self.issueTitleLayout)
        self.issueLayout = QtWidgets.QHBoxLayout()
        self.issueLayout.setSpacing(10)
        self.issueLayout.setObjectName("issueLayout")
        self.txtIssue = QtWidgets.QTextEdit(parent=self.formPanel1)
        self.txtIssue.setMinimumSize(QtCore.QSize(0, 78))
        self.txtIssue.setObjectName("txtIssue")
        self.issueLayout.addWidget(self.txtIssue)
        self.txtDeviceCondition = QtWidgets.QTextEdit(parent=self.formPanel1)
        self.txtDeviceCondition.setMinimumSize(QtCore.QSize(0, 78))
        self.txtDeviceCondition.setObjectName("txtDeviceCondition")
        self.issueLayout.addWidget(self.txtDeviceCondition)
        self.formLayout.addLayout(self.issueLayout)
        self.lblTechNoteTitle = QtWidgets.QLabel(parent=self.formPanel1)
        self.lblTechNoteTitle.setObjectName("lblTechNoteTitle")
        self.formLayout.addWidget(self.lblTechNoteTitle)
        self.txtTechNote = QtWidgets.QTextEdit(parent=self.formPanel1)
        self.txtTechNote.setMinimumSize(QtCore.QSize(0, 72))
        self.txtTechNote.setObjectName("txtTechNote")
        self.formLayout.addWidget(self.txtTechNote)
        self.rightLayout.addWidget(self.formPanel1)
        self.historyPanel = QtWidgets.QFrame(parent=WarrantyPage)
        self.historyPanel.setObjectName("historyPanel")
        self.historyLayout = QtWidgets.QVBoxLayout(self.historyPanel)
        self.historyLayout.setContentsMargins(14, 12, 14, 12)
        self.historyLayout.setSpacing(8)
        self.historyLayout.setObjectName("historyLayout")
        self.historyTitleLayout = QtWidgets.QHBoxLayout()
        self.historyTitleLayout.setObjectName("historyTitleLayout")
        self.lblHistoryTitle = QtWidgets.QLabel(parent=self.historyPanel)
        self.lblHistoryTitle.setObjectName("lblHistoryTitle")
        self.historyTitleLayout.addWidget(self.lblHistoryTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.historyTitleLayout.addItem(spacerItem1)
        self.cboHistoryFilter = QtWidgets.QComboBox(parent=self.historyPanel)
        self.cboHistoryFilter.setMinimumSize(QtCore.QSize(165, 36))
        self.cboHistoryFilter.setObjectName("cboHistoryFilter")
        self.cboHistoryFilter.addItem("")
        self.cboHistoryFilter.addItem("")
        self.cboHistoryFilter.addItem("")
        self.cboHistoryFilter.addItem("")
        self.cboHistoryFilter.addItem("")
        self.cboHistoryFilter.addItem("")
        self.cboHistoryFilter.addItem("")
        self.historyTitleLayout.addWidget(self.cboHistoryFilter)
        self.btnRefresh = QtWidgets.QPushButton(parent=self.historyPanel)
        self.btnRefresh.setMinimumSize(QtCore.QSize(82, 36))
        self.btnRefresh.setObjectName("btnRefresh")
        self.historyTitleLayout.addWidget(self.btnRefresh)
        self.btnPrintWarranty = QtWidgets.QPushButton(parent=self.historyPanel)
        self.btnPrintWarranty.setMinimumSize(QtCore.QSize(108, 36))
        self.btnPrintWarranty.setObjectName("btnPrintWarranty")
        self.historyTitleLayout.addWidget(self.btnPrintWarranty)
        self.btnExportWarranty = QtWidgets.QPushButton(parent=self.historyPanel)
        self.btnExportWarranty.setMinimumSize(QtCore.QSize(92, 36))
        self.btnExportWarranty.setObjectName("btnExportWarranty")
        self.historyTitleLayout.addWidget(self.btnExportWarranty)
        self.historyLayout.addLayout(self.historyTitleLayout)
        self.tableWarrantyHistory = QtWidgets.QTableWidget(parent=self.historyPanel)
        self.tableWarrantyHistory.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWarrantyHistory.setColumnCount(9)
        self.tableWarrantyHistory.setObjectName("tableWarrantyHistory")
        self.tableWarrantyHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarrantyHistory.setHorizontalHeaderItem(8, item)
        self.historyLayout.addWidget(self.tableWarrantyHistory)
        self.bottomActionLayout = QtWidgets.QHBoxLayout()
        self.bottomActionLayout.setSpacing(8)
        self.bottomActionLayout.setObjectName("bottomActionLayout")
        self.btnCancelWarranty = QtWidgets.QPushButton(parent=self.historyPanel)
        self.btnCancelWarranty.setMinimumSize(QtCore.QSize(0, 38))
        self.btnCancelWarranty.setObjectName("btnCancelWarranty")
        self.bottomActionLayout.addWidget(self.btnCancelWarranty)
        self.historyLayout.addLayout(self.bottomActionLayout)
        self.rightLayout.addWidget(self.historyPanel)
        self.contentLayout.addLayout(self.rightLayout)
        self.mainLayout.addLayout(self.contentLayout)

        self.retranslateUi(WarrantyPage)
        QtCore.QMetaObject.connectSlotsByName(WarrantyPage)

    def retranslateUi(self, WarrantyPage):
        _translate = QtCore.QCoreApplication.translate
        WarrantyPage.setStyleSheet(_translate("WarrantyPage", "\n"
"QWidget#WarrantyPage {\n"
"    background-color: #f8fafc;\n"
"}\n"
"\n"
"/* ===== PANEL ===== */\n"
"QFrame#searchPanel,\n"
"QFrame#devicePanel,\n"
"QFrame#customerPanel,\n"
"QFrame#formPanel,\n"
"QFrame#historyPanel,\n"
"QFrame#summaryCard1,\n"
"QFrame#summaryCard2,\n"
"QFrame#summaryCard3,\n"
"QFrame#summaryCard4 {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QFrame#statusBox {\n"
"    background-color: #eff6ff;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"/* ===== TEXT ===== */\n"
"QLabel.sectionTitle {\n"
"    color: #1e3a8a;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.formLabel {\n"
"    color: #334155;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.valueLabel {\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statNumber {\n"
"    color: #2563eb;\n"
"    font-size: 21px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.statText {\n"
"    color: #64748b;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel#lblWarrantyStatusValue {\n"
"    color: #dc2626;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ===== INPUT ===== */\n"
"QLineEdit,\n"
"QDateEdit,\n"
"QComboBox,\n"
"QTextEdit {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QDateEdit:focus,\n"
"QComboBox:focus,\n"
"QTextEdit:focus {\n"
"    border: 2px solid #2563eb;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* ===== COMBOBOX FIX: KHÔNG MỜ CHỮ ===== */\n"
"QComboBox {\n"
"    background-color: #f8fafc;\n"
"    border: 1px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 6px 32px 6px 10px;\n"
"    color: #0f172a;\n"
"    font-size: 13px;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QComboBox::drop-down,\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #cbd5e1;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    background-color: #eff6ff;\n"
"}\n"
"\n"
"QComboBox::down-arrow,\n"
"QDateEdit::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #0f172a;\n"
"    selection-background-color: #dbeafe;\n"
"    selection-color: #0f172a;\n"
"    border: 1px solid #93c5fd;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: 0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* ===== BUTTON ===== */\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 11px;\n"
"    padding: 7px 10px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btnSearchImei,\n"
"QPushButton#btnCreateWarranty,\n"
"QPushButton#btnUpdateWarranty,\n"
"QPushButton#btnPrintWarranty {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnUpdateWarranty {\n"
"    background-color: #16a34a;\n"
"}\n"
"\n"
"QPushButton#btnReturnDevice {\n"
"    background-color: #f59e0b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnCancelWarranty {\n"
"    background-color: #dc2626;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#btnClearForm,\n"
"QPushButton#btnRefresh,\n"
"QPushButton#btnExportWarranty {\n"
"    background-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"/* ===== TABLE ===== */\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #dbeafe;\n"
"    border-radius: 12px;\n"
"    gridline-color: #e2e8f0;\n"
"    color: #0f172a;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #dbeafe;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1e3a8a;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"   "))
        self.lblTotalWarranty.setText(_translate("WarrantyPage", "0"))
        self.lblTotalWarranty.setProperty("class", _translate("WarrantyPage", "statNumber"))
        self.lblTotalWarrantyText.setText(_translate("WarrantyPage", "Tổng phiếu bảo hành"))
        self.lblTotalWarrantyText.setProperty("class", _translate("WarrantyPage", "statText"))
        self.lblPendingWarranty.setText(_translate("WarrantyPage", "0"))
        self.lblPendingWarranty.setProperty("class", _translate("WarrantyPage", "statNumber"))
        self.lblPendingWarrantyText.setText(_translate("WarrantyPage", "Đang xử lý"))
        self.lblPendingWarrantyText.setProperty("class", _translate("WarrantyPage", "statText"))
        self.lblDoneWarranty.setText(_translate("WarrantyPage", "0"))
        self.lblDoneWarranty.setProperty("class", _translate("WarrantyPage", "statNumber"))
        self.lblDoneWarrantyText.setText(_translate("WarrantyPage", "Đã hoàn tất"))
        self.lblDoneWarrantyText.setProperty("class", _translate("WarrantyPage", "statText"))
        self.lblExpiredWarranty.setText(_translate("WarrantyPage", "0"))
        self.lblExpiredWarranty.setProperty("class", _translate("WarrantyPage", "statNumber"))
        self.lblExpiredWarrantyText.setText(_translate("WarrantyPage", "Hết hạn bảo hành"))
        self.lblExpiredWarrantyText.setProperty("class", _translate("WarrantyPage", "statText"))
        self.lblSearchTitle.setText(_translate("WarrantyPage", "🔎 Tra cứu bảo hành theo IMEI"))
        self.lblSearchTitle.setProperty("class", _translate("WarrantyPage", "sectionTitle"))
        self.txtSearchImei.setPlaceholderText(_translate("WarrantyPage", "Nhập hoặc quét IMEI cần tra cứu"))
        self.btnSearchImei.setText(_translate("WarrantyPage", "🔍 Tìm"))
        self.lblDeviceTitle.setText(_translate("WarrantyPage", "📱 Thông tin máy"))
        self.lblDeviceTitle.setProperty("class", _translate("WarrantyPage", "sectionTitle"))
        self.lblImeiText.setText(_translate("WarrantyPage", "IMEI:"))
        self.lblImeiText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblImeiValue.setText(_translate("WarrantyPage", "---"))
        self.lblImeiValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblProductText.setText(_translate("WarrantyPage", "Sản phẩm:"))
        self.lblProductText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblProductValue.setText(_translate("WarrantyPage", "---"))
        self.lblProductValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblVariantText.setText(_translate("WarrantyPage", "Biến thể:"))
        self.lblVariantText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblVariantValue.setText(_translate("WarrantyPage", "---"))
        self.lblVariantValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblSoldDateText.setText(_translate("WarrantyPage", "Ngày bán:"))
        self.lblSoldDateText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblSoldDateValue.setText(_translate("WarrantyPage", "---"))
        self.lblSoldDateValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblWarrantyEndText.setText(_translate("WarrantyPage", "Hạn BH:"))
        self.lblWarrantyEndText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblWarrantyEndValue.setText(_translate("WarrantyPage", "---"))
        self.lblWarrantyEndValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblCustomerTitle.setText(_translate("WarrantyPage", "👤 Thông tin khách mua"))
        self.lblCustomerTitle.setProperty("class", _translate("WarrantyPage", "sectionTitle"))
        self.lblCustomerNameText.setText(_translate("WarrantyPage", "Khách:"))
        self.lblCustomerNameText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblCustomerNameValue.setText(_translate("WarrantyPage", "---"))
        self.lblCustomerNameValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblPhoneText.setText(_translate("WarrantyPage", "SĐT:"))
        self.lblPhoneText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblPhoneValue.setText(_translate("WarrantyPage", "---"))
        self.lblPhoneValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblInvoiceText.setText(_translate("WarrantyPage", "Hóa đơn:"))
        self.lblInvoiceText.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblInvoiceValue.setText(_translate("WarrantyPage", "---"))
        self.lblInvoiceValue.setProperty("class", _translate("WarrantyPage", "valueLabel"))
        self.lblWarrantyStatusText.setText(_translate("WarrantyPage", "Trạng thái bảo hành"))
        self.lblWarrantyStatusText.setStyleSheet(_translate("WarrantyPage", "color: #1e3a8a; font-size: 15px; font-weight: bold;"))
        self.lblWarrantyStatusValue.setText(_translate("WarrantyPage", "Chưa tra cứu"))
        self.lblWarrantyRemainValue.setText(_translate("WarrantyPage", "---"))
        self.lblWarrantyRemainValue.setStyleSheet(_translate("WarrantyPage", "color: #475569; font-weight: bold;"))
        self.lblQuickFormTitle.setText(_translate("WarrantyPage", "🛠 Tạo / cập nhật phiếu bảo hành"))
        self.lblQuickFormTitle.setProperty("class", _translate("WarrantyPage", "sectionTitle"))
        self.cboWarrantyStatus.setItemText(0, _translate("WarrantyPage", "pending"))
        self.cboWarrantyStatus.setItemText(1, _translate("WarrantyPage", "checking"))
        self.cboWarrantyStatus.setItemText(2, _translate("WarrantyPage", "repairing"))
        self.cboWarrantyStatus.setItemText(3, _translate("WarrantyPage", "done"))
        self.cboWarrantyStatus.setItemText(4, _translate("WarrantyPage", "returned"))
        self.cboWarrantyStatus.setItemText(5, _translate("WarrantyPage", "cancelled"))
        self.dateReceive.setDisplayFormat(_translate("WarrantyPage", "dd/MM/yyyy"))
        self.dateReturn.setDisplayFormat(_translate("WarrantyPage", "dd/MM/yyyy"))
        self.btnCreateWarranty.setText(_translate("WarrantyPage", "➕ Tạo phiếu"))
        self.btnUpdateWarranty.setText(_translate("WarrantyPage", "💾 Cập nhật"))
        self.btnReturnDevice.setText(_translate("WarrantyPage", "✅ Trả máy"))
        self.lblFormTitle.setText(_translate("WarrantyPage", "📝 Thông tin lỗi & xử lý kỹ thuật"))
        self.lblFormTitle.setProperty("class", _translate("WarrantyPage", "sectionTitle"))
        self.btnClearForm.setText(_translate("WarrantyPage", "🧹 Xóa form"))
        self.lblIssueTitle.setText(_translate("WarrantyPage", "Lỗi khách báo"))
        self.lblIssueTitle.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.lblConditionTitle.setText(_translate("WarrantyPage", "Tình trạng máy khi nhận"))
        self.lblConditionTitle.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.txtIssue.setPlaceholderText(_translate("WarrantyPage", "VD: Máy sập nguồn, lỗi màn hình, không sạc..."))
        self.txtDeviceCondition.setPlaceholderText(_translate("WarrantyPage", "VD: Máy trầy nhẹ, còn hộp, không móp, pin 80%..."))
        self.lblTechNoteTitle.setText(_translate("WarrantyPage", "Ghi chú kỹ thuật / hướng xử lý"))
        self.lblTechNoteTitle.setProperty("class", _translate("WarrantyPage", "formLabel"))
        self.txtTechNote.setPlaceholderText(_translate("WarrantyPage", "Kỹ thuật ghi chú: đã kiểm tra, thay linh kiện, gửi hãng, chờ khách xác nhận..."))
        self.lblHistoryTitle.setText(_translate("WarrantyPage", "📋 Lịch sử bảo hành"))
        self.lblHistoryTitle.setProperty("class", _translate("WarrantyPage", "sectionTitle"))
        self.cboHistoryFilter.setItemText(0, _translate("WarrantyPage", "Tất cả trạng thái"))
        self.cboHistoryFilter.setItemText(1, _translate("WarrantyPage", "pending"))
        self.cboHistoryFilter.setItemText(2, _translate("WarrantyPage", "checking"))
        self.cboHistoryFilter.setItemText(3, _translate("WarrantyPage", "repairing"))
        self.cboHistoryFilter.setItemText(4, _translate("WarrantyPage", "done"))
        self.cboHistoryFilter.setItemText(5, _translate("WarrantyPage", "returned"))
        self.cboHistoryFilter.setItemText(6, _translate("WarrantyPage", "cancelled"))
        self.btnRefresh.setText(_translate("WarrantyPage", "🔄 Mới"))
        self.btnPrintWarranty.setText(_translate("WarrantyPage", "🖨 In phiếu"))
        self.btnExportWarranty.setText(_translate("WarrantyPage", "📤 Xuất"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(0)
        item.setText(_translate("WarrantyPage", "ID"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(1)
        item.setText(_translate("WarrantyPage", "IMEI"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(2)
        item.setText(_translate("WarrantyPage", "Sản phẩm"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(3)
        item.setText(_translate("WarrantyPage", "Khách hàng"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(4)
        item.setText(_translate("WarrantyPage", "Ngày nhận"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(5)
        item.setText(_translate("WarrantyPage", "Ngày trả"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(6)
        item.setText(_translate("WarrantyPage", "Trạng thái"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(7)
        item.setText(_translate("WarrantyPage", "Lỗi báo"))
        item = self.tableWarrantyHistory.horizontalHeaderItem(8)
        item.setText(_translate("WarrantyPage", "Ghi chú KT"))
        self.btnCancelWarranty.setText(_translate("WarrantyPage", "❌ Hủy phiếu bảo hành"))
